-- =====================================================================
-- 차세대 TC Version 5.0 (Oracle) - DDL
-- (1) 모든 테이블 DROP
-- (2) 모든 테이블 CREATE + 제약/인덱스
-- =====================================================================

-- ---------------------------------------------------------------------
-- 1) DROP (존재하지 않으면 무시)
-- ---------------------------------------------------------------------
DECLARE
  PROCEDURE drop_table(p_name IN VARCHAR2) IS
  BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE ' || p_name || ' CASCADE CONSTRAINTS PURGE';
  EXCEPTION
    WHEN OTHERS THEN
      IF SQLCODE != -942 THEN -- ORA-00942: table or view does not exist
        RAISE;
      END IF;
  END;
BEGIN
  drop_table('TC_MSG_SEND_LOG');
  drop_table('TC_MSG_SEND_QUEUE');

  drop_table('TC_UI_AUTH_SESSION');
  drop_table('TC_USER_GROUP_PERMISSION');
  drop_table('TC_USER_GROUP_MEMBER');
  drop_table('TC_USER_GROUP');
  drop_table('TC_UI_PERMISSION');
  drop_table('TC_USER_INFO');

  drop_table('TC_MODEL_DCOP_ITEM');
  drop_table('TC_MODEL_MDF');
  drop_table('TC_MODEL_WORKFLOW');
  drop_table('TC_MODEL_EVENTID');
  drop_table('TC_MODEL_REPORTID');
  drop_table('TC_MODEL_VARIABLEID');
  drop_table('TC_MODEL_MES_MESSAGE');
  drop_table('TC_MODEL_SOCKET_MESSAGE');
  drop_table('TC_MODEL_SECS_MESSAGE');
  drop_table('TC_MODEL_PARAM');
  drop_table('TC_MODEL_VERSION');
  drop_table('TC_MODEL');

  drop_table('TC_WORK_PROCESSJOB_LOT_MAP');
  drop_table('TC_WORK_PROCESSJOB');
  drop_table('TC_WORK_CONTROLJOB');
  drop_table('TC_WORK_LOT');
  drop_table('TC_WORK_CARRIER_SLOT');
  drop_table('TC_WORK_CARRIER');
  drop_table('TC_WORK_PARAM');
  drop_table('TC_WORK');

  drop_table('TC_EQP_GLOBAL');
  drop_table('TC_EQP_PARAM_VERSION');
  drop_table('TC_EQP_PARAM');
  drop_table('TC_EQP_PORT_STATUS');
  drop_table('TC_EQP_LOG');
  drop_table('TC_EQP_STATE_HIST');
  drop_table('TC_EQP_STATE');
  drop_table('TC_EQP_SOCKET');
  drop_table('TC_EQP_HSMS');
  drop_table('TC_EQP');
  drop_table('TC_EQP_SOCKET_PROTOCOL_TYPE');
END;
/
-- ---------------------------------------------------------------------
-- 2) CREATE
-- ---------------------------------------------------------------------

-- =========================
-- 2.1 MODEL
-- =========================
CREATE TABLE TC_MODEL (
  model_key      NUMBER(19) GENERATED BY DEFAULT AS IDENTITY,
  model_name     VARCHAR2(128) NOT NULL,
  comm_interface VARCHAR2(16)  NOT NULL,
  maker          VARCHAR2(32)  NULL,
  created_at     TIMESTAMP(3) WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at     TIMESTAMP(3) WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_by     VARCHAR2(50) NOT NULL DEFAULT 'SYSTEM',
  updated_by     VARCHAR2(50) NOT NULL DEFAULT 'SYSTEM',

  CONSTRAINT pk_tc_model PRIMARY KEY (model_key),
  CONSTRAINT uk_tc_model_model_name UNIQUE (model_name),
  CONSTRAINT ck_tc_model_comm_interface CHECK (comm_interface IN ('HSMS','SOCKET'))
);

CREATE INDEX ix_tc_model_model_name     ON TC_MODEL (model_name);
CREATE INDEX ix_tc_model_comm_interface ON TC_MODEL (comm_interface);
CREATE INDEX ix_tc_model_maker          ON TC_MODEL (maker);

CREATE TABLE TC_MODEL_VERSION (
  model_version_key NUMBER(19) GENERATED BY DEFAULT AS IDENTITY,
  model_key         NUMBER(19) NOT NULL,
  model_version     VARCHAR2(32) NOT NULL,
  status            VARCHAR2(16) NOT NULL,
  created_at        TIMESTAMP(3) WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at        TIMESTAMP(3) WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_by        VARCHAR2(50) NOT NULL DEFAULT 'SYSTEM',
  updated_by        VARCHAR2(50) NOT NULL DEFAULT 'SYSTEM',

  CONSTRAINT pk_tc_model_version PRIMARY KEY (model_version_key),
  CONSTRAINT fk_tc_model_version_model_key__tc_model
    FOREIGN KEY (model_key) REFERENCES TC_MODEL(model_key) ON DELETE CASCADE,
  CONSTRAINT uk_tc_model_version_model_key_model_version UNIQUE (model_key, model_version),
  CONSTRAINT ck_tc_model_version_status CHECK (status IN ('DRAFT','ACTIVE','DEPRECATED'))
);

CREATE INDEX ix_tc_model_version_model_key ON TC_MODEL_VERSION (model_key);
CREATE INDEX ix_tc_model_version_status    ON TC_MODEL_VERSION (status);

CREATE TABLE TC_MODEL_PARAM (
  model_param_key NUMBER(19) GENERATED BY DEFAULT AS IDENTITY,
  model_version_key NUMBER(19) NOT NULL,
  param_name      VARCHAR2(128) NOT NULL,
  param_value     VARCHAR2(2000) NULL,
  updated_at      TIMESTAMP(3) WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

  CONSTRAINT pk_tc_model_param PRIMARY KEY (model_param_key),
  CONSTRAINT fk_tc_model_param_model_version_key__tc_model_version
    FOREIGN KEY (model_version_key) REFERENCES TC_MODEL_VERSION(model_version_key) ON DELETE CASCADE,
  CONSTRAINT uk_tc_model_param_model_version_key_param_name UNIQUE (model_version_key, param_name)
);

CREATE INDEX ix_tc_model_param_model_version_key ON TC_MODEL_PARAM (model_version_key);

CREATE TABLE TC_MODEL_SECS_MESSAGE (
  secs_msg_key   NUMBER(19) GENERATED BY DEFAULT AS IDENTITY,
  model_version_key NUMBER(19) NOT NULL,
  secs_msg_name  VARCHAR2(100) NOT NULL,
  description    VARCHAR2(2000) NULL,
  data_index     VARCHAR2(200)  NULL,
  updated_at     TIMESTAMP(3) WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

  CONSTRAINT pk_tc_model_secs_message PRIMARY KEY (secs_msg_key),
  CONSTRAINT fk_tc_model_secs_message_model_version_key__tc_model_version
    FOREIGN KEY (model_version_key) REFERENCES TC_MODEL_VERSION(model_version_key) ON DELETE CASCADE,
  CONSTRAINT uk_tc_model_secs_message_model_version_key_secs_msg_name UNIQUE (model_version_key, secs_msg_name)
);

CREATE INDEX ix_tc_model_secs_message_model_version_key ON TC_MODEL_SECS_MESSAGE (model_version_key);
CREATE INDEX ix_tc_model_secs_message_secs_msg_name ON TC_MODEL_SECS_MESSAGE (secs_msg_name);

CREATE TABLE TC_MODEL_SOCKET_MESSAGE (
  socket_msg_key  NUMBER(19) GENERATED BY DEFAULT AS IDENTITY,
  model_version_key NUMBER(19) NOT NULL,
  socket_msg_name VARCHAR2(100) NOT NULL,
  description     VARCHAR2(2000) NULL,
  data_index      VARCHAR2(200)  NULL,
  updated_at      TIMESTAMP(3) WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

  CONSTRAINT pk_tc_model_socket_message PRIMARY KEY (socket_msg_key),
  CONSTRAINT fk_tc_model_socket_message_model_version_key__tc_model_version
    FOREIGN KEY (model_version_key) REFERENCES TC_MODEL_VERSION(model_version_key) ON DELETE CASCADE,
  CONSTRAINT uk_tc_model_socket_message_model_version_key_socket_msg_name UNIQUE (model_version_key, socket_msg_name)
);

CREATE INDEX ix_tc_model_socket_message_model_version_key ON TC_MODEL_SOCKET_MESSAGE (model_version_key);
CREATE INDEX ix_tc_model_socket_message_socket_msg_name ON TC_MODEL_SOCKET_MESSAGE (socket_msg_name);

CREATE TABLE TC_MODEL_MES_MESSAGE (
  mes_msg_key       NUMBER(19) GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  model_version_key NUMBER(19) NOT NULL,
  mes_msg_name      VARCHAR2(1000) NOT NULL,
  description       VARCHAR2(2000) NULL,
  data_index        VARCHAR2(200)  NULL,
  updated_at        TIMESTAMP(3) WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

  CONSTRAINT pk_tc_model_mes_message PRIMARY KEY (mes_msg_key),
  CONSTRAINT fk_tc_model_mes_message_model_version_key__tc_model_version
    FOREIGN KEY (model_version_key) REFERENCES TC_MODEL_VERSION(model_version_key) ON DELETE CASCADE,
  CONSTRAINT uk_tc_model_mes_message_model_version_key_mes_msg_name UNIQUE (model_version_key, mes_msg_name)
);
CREATE INDEX ix_tc_model_mes_message_model_version_key ON TC_MODEL_MES_MESSAGE (model_version_key);
CREATE INDEX ix_tc_model_mes_message_mes_msg_name ON TC_MODEL_MES_MESSAGE (mes_msg_name);

CREATE TABLE TC_MODEL_VARIABLEID (
  variable_key     NUMBER(19) GENERATED BY DEFAULT AS IDENTITY,
  model_version_key NUMBER(19) NOT NULL,
  variable_id      VARCHAR2(100) NOT NULL,
  variable_id_type VARCHAR2(10) NOT NULL DEFAULT 'SVID',
  description      VARCHAR2(2000) NULL,
  updated_at       TIMESTAMP(3) WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

  CONSTRAINT pk_tc_model_variableid PRIMARY KEY (variable_key),
  CONSTRAINT fk_tc_model_variableid_model_version_key__tc_model_version
    FOREIGN KEY (model_version_key) REFERENCES TC_MODEL_VERSION(model_version_key) ON DELETE CASCADE,
  CONSTRAINT uk_tc_model_variableid_model_version_key_type_variable_id UNIQUE (model_version_key, variable_id_type, variable_id),
  CONSTRAINT ck_tc_model_variableid_type CHECK (variable_id_type IN ('SVID','DVID','ECID','CEID'))
);

CREATE INDEX ix_tc_model_variableid_model_version_key ON TC_MODEL_VARIABLEID (model_version_key);
CREATE INDEX ix_tc_model_variableid_variable_id ON TC_MODEL_VARIABLEID (variable_id);

CREATE TABLE TC_MODEL_REPORTID (
  report_key  NUMBER(19) GENERATED BY DEFAULT AS IDENTITY,
  model_version_key NUMBER(19) NOT NULL,
  report_id   VARCHAR2(100) NOT NULL,
  variable_id VARCHAR2(1000) NULL,
  enabled     NUMBER(1) NOT NULL DEFAULT 0,
  updated_at  TIMESTAMP(3) WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

  CONSTRAINT pk_tc_model_reportid PRIMARY KEY (report_key),
  CONSTRAINT fk_tc_model_reportid_model_version_key__tc_model_version
    FOREIGN KEY (model_version_key) REFERENCES TC_MODEL_VERSION(model_version_key) ON DELETE CASCADE,
  CONSTRAINT uk_tc_model_reportid_model_version_key_report_id UNIQUE (model_version_key, report_id),
  CONSTRAINT ck_tc_model_reportid_enabled CHECK (enabled IN (0,1))
);

CREATE INDEX ix_tc_model_reportid_model_version_key ON TC_MODEL_REPORTID (model_version_key);
CREATE INDEX ix_tc_model_reportid_enabled  ON TC_MODEL_REPORTID (enabled);

CREATE TABLE TC_MODEL_EVENTID (
  event_key  NUMBER(19) GENERATED BY DEFAULT AS IDENTITY,
  model_version_key NUMBER(19) NOT NULL,
  event_id   VARCHAR2(100) NOT NULL,
  report_id  VARCHAR2(1000) NULL,
  enabled    NUMBER(1) NOT NULL DEFAULT 0,
  updated_at TIMESTAMP(3) WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

  CONSTRAINT pk_tc_model_eventid PRIMARY KEY (event_key),
  CONSTRAINT fk_tc_model_eventid_model_version_key__tc_model_version
    FOREIGN KEY (model_version_key) REFERENCES TC_MODEL_VERSION(model_version_key) ON DELETE CASCADE,
  CONSTRAINT uk_tc_model_eventid_model_version_key_event_id UNIQUE (model_version_key, event_id),
  CONSTRAINT ck_tc_model_eventid_enabled CHECK (enabled IN (0,1))
);

CREATE INDEX ix_tc_model_eventid_model_version_key ON TC_MODEL_EVENTID (model_version_key);
CREATE INDEX ix_tc_model_eventid_enabled  ON TC_MODEL_EVENTID (enabled);

CREATE TABLE TC_MODEL_WORKFLOW (
  workflow_key      NUMBER(19) GENERATED BY DEFAULT AS IDENTITY,
  model_version_key NUMBER(19) NOT NULL,
  workflow_name     VARCHAR2(200) NOT NULL,
  message_name      VARCHAR2(200) NOT NULL,
  event_id          VARCHAR2(200) NULL,
  transaction_id    VARCHAR2(200) NULL,
  workflow_filter   VARCHAR2(200) NULL,
  action_name       VARCHAR2(200) NOT NULL,
  action_data_index VARCHAR2(4000) NULL,
  updated_at        TIMESTAMP(3) WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

  CONSTRAINT pk_tc_model_workflow PRIMARY KEY (workflow_key),
  CONSTRAINT fk_tc_model_workflow_model_version_key__tc_model_version
    FOREIGN KEY (model_version_key) REFERENCES TC_MODEL_VERSION(model_version_key) ON DELETE CASCADE,
  CONSTRAINT uk_tc_model_workflow_model_version_key_workflow_name_message_name UNIQUE (model_version_key, workflow_name, message_name)
);

CREATE INDEX ix_tc_model_workflow_model_version_key ON TC_MODEL_WORKFLOW (model_version_key);
CREATE INDEX ix_tc_model_workflow_workflow_name  ON TC_MODEL_WORKFLOW (workflow_name);

CREATE TABLE TC_MODEL_MDF (
  mdf_key    NUMBER(19) GENERATED BY DEFAULT AS IDENTITY,
  model_version_key NUMBER(19) NOT NULL,
  mdf_name   VARCHAR2(100) NOT NULL,
  mdf_file   BLOB NOT NULL,
  updated_at TIMESTAMP(3) WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

  CONSTRAINT pk_tc_model_mdf PRIMARY KEY (mdf_key),
  CONSTRAINT fk_tc_model_mdf_model_version_key__tc_model_version
    FOREIGN KEY (model_version_key) REFERENCES TC_MODEL_VERSION(model_version_key) ON DELETE CASCADE,
  CONSTRAINT uk_tc_model_mdf_model_version_key UNIQUE (model_version_key)
);

CREATE INDEX ix_tc_model_mdf_model_version_key ON TC_MODEL_MDF (model_version_key);

CREATE TABLE TC_MODEL_DCOP_ITEM (
  dcop_item_key     NUMBER(19) GENERATED BY DEFAULT AS IDENTITY,
  model_version_key NUMBER(19) NOT NULL,
  dcop_item_name    VARCHAR2(200) NOT NULL,
  workflow_name     VARCHAR2(200) NULL,
  event_id          VARCHAR2(100) NULL,
  variable_id       VARCHAR2(100) NULL,
  collection_rule   VARCHAR2(10)  NULL,
  calculation_rule  VARCHAR2(20)  NULL,
  order_rule        NUMBER(10)    NULL,
  updated_at        TIMESTAMP(3) WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

  CONSTRAINT pk_tc_model_dcop_item PRIMARY KEY (dcop_item_key),
  CONSTRAINT fk_tc_model_dcop_item_model_version_key__tc_model_version
    FOREIGN KEY (model_version_key) REFERENCES TC_MODEL_VERSION(model_version_key) ON DELETE CASCADE,
  CONSTRAINT uk_tc_model_dcop_item_model_version_key_dcop_item_name UNIQUE (model_version_key, dcop_item_name),
  CONSTRAINT ck_tc_model_dcop_item_order_rule CHECK (order_rule IS NULL OR order_rule >= 0)
);

CREATE INDEX ix_tc_model_dcop_item_model_version_key ON TC_MODEL_DCOP_ITEM (model_version_key);
CREATE INDEX ix_tc_model_dcop_item_event_id  ON TC_MODEL_DCOP_ITEM (event_id);

-- =========================
-- 2.2 EQP
-- =========================
CREATE TABLE TC_EQP_SOCKET_PROTOCOL_TYPE (
  socket_protocol_type      VARCHAR2(32),
  socket_protocol_type_name VARCHAR2(100) NOT NULL,
  parse_start_rule          VARCHAR2(1000) NULL,
  parse_end_rule            VARCHAR2(1000) NULL,
  parse_regex               VARCHAR2(1000) NULL,
  description               VARCHAR2(1000) NULL,

  CONSTRAINT pk_tc_eqp_socket_protocol_type PRIMARY KEY (socket_protocol_type)
);

CREATE TABLE TC_EQP (
  eqp_key        NUMBER(19) GENERATED BY DEFAULT AS IDENTITY,
  eqp_id         VARCHAR2(64) NOT NULL,
  comm_interface VARCHAR2(16) NOT NULL,
  eqp_ip         VARCHAR2(45) NOT NULL,
  eqp_port       NUMBER(10)   NOT NULL,
  model_version_key NUMBER(19) NOT NULL,
  enabled        NUMBER(1)    NOT NULL DEFAULT 1,
  created_at     TIMESTAMP(3) WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at     TIMESTAMP(3) WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_by     VARCHAR2(50) NOT NULL DEFAULT 'SYSTEM',
  updated_by     VARCHAR2(50) NOT NULL DEFAULT 'SYSTEM',

  CONSTRAINT pk_tc_eqp PRIMARY KEY (eqp_key),
  CONSTRAINT uk_tc_eqp_eqp_id UNIQUE (eqp_id),
  CONSTRAINT fk_tc_eqp_model_version_key__tc_model_version
    FOREIGN KEY (model_version_key) REFERENCES TC_MODEL_VERSION(model_version_key),
  CONSTRAINT ck_tc_eqp_comm_interface CHECK (comm_interface IN ('HSMS','SOCKET')),
  CONSTRAINT ck_tc_eqp_eqp_port CHECK (eqp_port BETWEEN 1 AND 65535),
  CONSTRAINT ck_tc_eqp_enabled CHECK (enabled IN (0,1))
);

CREATE INDEX ix_tc_eqp_enabled        ON TC_EQP (enabled);
CREATE INDEX ix_tc_eqp_model_version_key ON TC_EQP (model_version_key);
CREATE INDEX ix_tc_eqp_comm_interface ON TC_EQP (comm_interface);
CREATE INDEX ix_tc_eqp_eqp_ip_port    ON TC_EQP (eqp_ip, eqp_port);

CREATE TABLE TC_EQP_HSMS (
  eqp_key            NUMBER(19) NOT NULL,
  device_id          NUMBER(10) NOT NULL,
  connection_mode    VARCHAR2(10) NOT NULL,
  t3_timeout         NUMBER(10) NOT NULL DEFAULT 45,
  t5_timeout         NUMBER(10) NOT NULL DEFAULT 10,
  t6_timeout         NUMBER(10) NOT NULL DEFAULT 5,
  t7_timeout         NUMBER(10) NOT NULL DEFAULT 10,
  t8_timeout         NUMBER(10) NOT NULL DEFAULT 5,
  link_test_enabled  NUMBER(1)  NOT NULL DEFAULT 1,
  link_test_interval NUMBER(10) NOT NULL DEFAULT 60,
  max_msg_bytes      NUMBER(19) NOT NULL DEFAULT 10485760,
  created_at         TIMESTAMP(3) WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at         TIMESTAMP(3) WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

  CONSTRAINT pk_tc_eqp_hsms PRIMARY KEY (eqp_key),
  CONSTRAINT fk_tc_eqp_hsms_eqp_key__tc_eqp FOREIGN KEY (eqp_key) REFERENCES TC_EQP(eqp_key) ON DELETE CASCADE,
  CONSTRAINT ck_tc_eqp_hsms_device_id CHECK (device_id BETWEEN 0 AND 32767),
  CONSTRAINT ck_tc_eqp_hsms_connection_mode CHECK (connection_mode IN ('ACTIVE','PASSIVE')),
  CONSTRAINT ck_tc_eqp_hsms_t3_timeout CHECK (t3_timeout > 0),
  CONSTRAINT ck_tc_eqp_hsms_t5_timeout CHECK (t5_timeout > 0),
  CONSTRAINT ck_tc_eqp_hsms_t6_timeout CHECK (t6_timeout > 0),
  CONSTRAINT ck_tc_eqp_hsms_t7_timeout CHECK (t7_timeout > 0),
  CONSTRAINT ck_tc_eqp_hsms_t8_timeout CHECK (t8_timeout > 0),
  CONSTRAINT ck_tc_eqp_hsms_link_test_enabled CHECK (link_test_enabled IN (0,1)),
  CONSTRAINT ck_tc_eqp_hsms_link_test_interval CHECK (link_test_interval > 0),
  CONSTRAINT ck_tc_eqp_hsms_max_msg_bytes CHECK (max_msg_bytes > 0)
);

CREATE TABLE TC_EQP_SOCKET (
  eqp_key              NUMBER(19) NOT NULL,
  socket_protocol_type VARCHAR2(32) NOT NULL,
  connection_mode      VARCHAR2(10) NOT NULL,
  charset              VARCHAR2(20) NOT NULL DEFAULT 'UTF-8',
  heartbeat_enabled    NUMBER(1)  NOT NULL DEFAULT 1,
  heartbeat_interval   NUMBER(10) NOT NULL DEFAULT 30,
  read_timeout         NUMBER(10) NOT NULL DEFAULT 0,
  write_timeout        NUMBER(10) NOT NULL DEFAULT 0,
  max_frame_size_bytes NUMBER(10) NOT NULL DEFAULT 8192,
  keep_alive_enabled   NUMBER(1)  NOT NULL DEFAULT 1,
  created_at           TIMESTAMP(3) WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at           TIMESTAMP(3) WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

  CONSTRAINT pk_tc_eqp_socket PRIMARY KEY (eqp_key),
  CONSTRAINT fk_tc_eqp_socket_eqp_key__tc_eqp FOREIGN KEY (eqp_key) REFERENCES TC_EQP(eqp_key) ON DELETE CASCADE,
  CONSTRAINT fk_tc_eqp_socket_socket_protocol_type__tc_eqp_socket_protocol_type
    FOREIGN KEY (socket_protocol_type) REFERENCES TC_EQP_SOCKET_PROTOCOL_TYPE(socket_protocol_type),
  CONSTRAINT ck_tc_eqp_socket_connection_mode CHECK (connection_mode IN ('ACTIVE','PASSIVE')),
  CONSTRAINT ck_tc_eqp_socket_heartbeat_enabled CHECK (heartbeat_enabled IN (0,1)),
  CONSTRAINT ck_tc_eqp_socket_heartbeat_interval CHECK (heartbeat_interval >= 0),
  CONSTRAINT ck_tc_eqp_socket_read_timeout CHECK (read_timeout >= 0),
  CONSTRAINT ck_tc_eqp_socket_write_timeout CHECK (write_timeout >= 0),
  CONSTRAINT ck_tc_eqp_socket_max_frame_size_bytes CHECK (max_frame_size_bytes > 0),
  CONSTRAINT ck_tc_eqp_socket_keep_alive_enabled CHECK (keep_alive_enabled IN (0,1))
);

CREATE INDEX ix_tc_eqp_socket_socket_protocol_type ON TC_EQP_SOCKET (socket_protocol_type);

CREATE TABLE TC_EQP_STATE (
  eqp_key       NUMBER(19) NOT NULL,
  control_state VARCHAR2(20) NULL,
  eqp_state     VARCHAR2(20) NULL,
  since_at      TIMESTAMP(3) WITH TIME ZONE NULL,
  reason_code   VARCHAR2(50) NULL,
  reason_detail CLOB NULL,
  updated_at    TIMESTAMP(3) WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

  CONSTRAINT pk_tc_eqp_state PRIMARY KEY (eqp_key),
  CONSTRAINT fk_tc_eqp_state_eqp_key__tc_eqp FOREIGN KEY (eqp_key) REFERENCES TC_EQP(eqp_key) ON DELETE CASCADE,
  CONSTRAINT ck_tc_eqp_state_control_state CHECK (control_state IS NULL OR control_state IN ('OFFLINE','LOCAL','REMOTE')),
  CONSTRAINT ck_tc_eqp_state_eqp_state CHECK (eqp_state IS NULL OR eqp_state IN ('IDLE','RUN','DOWN','MAINTENANCE','PAUSE'))
);

CREATE TABLE TC_EQP_STATE_HIST (
  state_hist_key NUMBER(19) GENERATED BY DEFAULT AS IDENTITY,
  eqp_key        NUMBER(19) NOT NULL,
  state_type     VARCHAR2(10) NOT NULL,
  from_state     VARCHAR2(50) NULL,
  to_state       VARCHAR2(50) NULL,
  changed_at     TIMESTAMP(3) WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  reason_code    VARCHAR2(50) NULL,
  reason_detail  CLOB NULL,

  CONSTRAINT pk_tc_eqp_state_hist PRIMARY KEY (state_hist_key),
  CONSTRAINT fk_tc_eqp_state_hist_eqp_key__tc_eqp FOREIGN KEY (eqp_key) REFERENCES TC_EQP(eqp_key) ON DELETE CASCADE,
  CONSTRAINT ck_tc_eqp_state_hist_state_type CHECK (state_type IN ('OPER','CONN'))
);

CREATE INDEX ix_tc_eqp_state_hist_eqp_key_changed_at
  ON TC_EQP_STATE_HIST (eqp_key, changed_at);
CREATE INDEX ix_tc_eqp_state_hist_state_type_changed_at
  ON TC_EQP_STATE_HIST (state_type, changed_at);

CREATE TABLE TC_EQP_LOG (
  eqp_key            NUMBER(19) NOT NULL,
  log_level          VARCHAR2(10) NOT NULL DEFAULT 'INFO',
  log_retention_days NUMBER(10) NOT NULL DEFAULT 30,
  log_path           VARCHAR2(1000) NULL,
  updated_at         TIMESTAMP(3) WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

  CONSTRAINT pk_tc_eqp_log PRIMARY KEY (eqp_key),
  CONSTRAINT fk_tc_eqp_log_eqp_key__tc_eqp FOREIGN KEY (eqp_key) REFERENCES TC_EQP(eqp_key) ON DELETE CASCADE,
  CONSTRAINT ck_tc_eqp_log_log_level CHECK (log_level IN ('TRACE','DEBUG','INFO','WARN','ERROR')),
  CONSTRAINT ck_tc_eqp_log_log_retention_days CHECK (log_retention_days >= 1)
);

CREATE TABLE TC_EQP_PORT_STATUS (
  eqp_port_status_key NUMBER(19) GENERATED BY DEFAULT AS IDENTITY,
  eqp_key             NUMBER(19) NOT NULL,
  port_id             VARCHAR2(20) NOT NULL,
  port_type           VARCHAR2(20) NULL,
  port_state          VARCHAR2(20) NULL,
  carrier_id          VARCHAR2(64) NULL,
  carrier_type        VARCHAR2(20) NULL,
  carrier_state       VARCHAR2(20) NULL,
  updated_at          TIMESTAMP(3) WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

  CONSTRAINT pk_tc_eqp_port_status PRIMARY KEY (eqp_port_status_key),
  CONSTRAINT fk_tc_eqp_port_status_eqp_key__tc_eqp FOREIGN KEY (eqp_key) REFERENCES TC_EQP(eqp_key) ON DELETE CASCADE,
  CONSTRAINT uk_tc_eqp_port_status_eqp_key_port_id UNIQUE (eqp_key, port_id),
  CONSTRAINT ck_tc_eqp_port_status_port_type CHECK (port_type IS NULL OR port_type IN ('LOAD_PORT','UNLOAD_PORT','INTERNAL_BUFFER','OTHER')),
  CONSTRAINT ck_tc_eqp_port_status_port_state CHECK (port_state IS NULL OR port_state IN ('EMPTY','LOADED','READY_TO_LOAD','DOWN','IN_SERVICE','UNKNOWN')),
  CONSTRAINT ck_tc_eqp_port_status_carrier_type CHECK (carrier_type IS NULL OR carrier_type IN ('FOUP','CASSETTE','WAFER_BOX','TRAY','OTHER')),
  CONSTRAINT ck_tc_eqp_port_status_carrier_state CHECK (carrier_state IS NULL OR carrier_state IN ('CLAMPED','UNCLAMPED','OPENED','CLOSED','UNKNOWN'))
);

CREATE INDEX ix_tc_eqp_port_status_eqp_key   ON TC_EQP_PORT_STATUS (eqp_key);
CREATE INDEX ix_tc_eqp_port_status_port_id  ON TC_EQP_PORT_STATUS (port_id);
CREATE INDEX ix_tc_eqp_port_status_carrier_id ON TC_EQP_PORT_STATUS (carrier_id);

CREATE TABLE TC_EQP_PARAM (
  eqp_param_key NUMBER(19) GENERATED BY DEFAULT AS IDENTITY,
  eqp_key       NUMBER(19) NOT NULL,
  param_name    VARCHAR2(100) NOT NULL,
  param_version VARCHAR2(100) NOT NULL,
  param_value   CLOB NULL,
  updated_at    TIMESTAMP(3) WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

  CONSTRAINT pk_tc_eqp_param PRIMARY KEY (eqp_param_key),
  CONSTRAINT fk_tc_eqp_param_eqp_key__tc_eqp FOREIGN KEY (eqp_key) REFERENCES TC_EQP(eqp_key) ON DELETE CASCADE,
  CONSTRAINT uk_tc_eqp_param_eqp_key_param_name_param_version UNIQUE (eqp_key, param_name, param_version)
);

CREATE INDEX ix_tc_eqp_param_eqp_key    ON TC_EQP_PARAM (eqp_key);
CREATE INDEX ix_tc_eqp_param_param_name ON TC_EQP_PARAM (param_name);

CREATE TABLE TC_EQP_PARAM_VERSION (
  eqp_param_version_key NUMBER(19) GENERATED BY DEFAULT AS IDENTITY,
  eqp_key               NUMBER(19) NOT NULL,
  param_version         VARCHAR2(100) NOT NULL,
  version_description   VARCHAR2(2000) NULL,
  created_at            TIMESTAMP(3) WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at            TIMESTAMP(3) WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_by            VARCHAR2(50) NOT NULL DEFAULT 'SYSTEM',
  updated_by            VARCHAR2(50) NOT NULL DEFAULT 'SYSTEM',

  CONSTRAINT pk_tc_eqp_param_version PRIMARY KEY (eqp_param_version_key),
  CONSTRAINT fk_tc_eqp_param_version_eqp_key__tc_eqp FOREIGN KEY (eqp_key) REFERENCES TC_EQP(eqp_key) ON DELETE CASCADE,
  CONSTRAINT uk_tc_eqp_param_version_eqp_key_param_version UNIQUE (eqp_key, param_version)
);

CREATE INDEX ix_tc_eqp_param_version_eqp_key ON TC_EQP_PARAM_VERSION (eqp_key);

CREATE TABLE TC_EQP_GLOBAL (
  eqp_global_key NUMBER(19) GENERATED BY DEFAULT AS IDENTITY,
  eqp_key        NUMBER(19) NOT NULL,
  param_name     VARCHAR2(100) NOT NULL,
  param_value    CLOB NULL,
  updated_at     TIMESTAMP(3) WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

  CONSTRAINT pk_tc_eqp_global PRIMARY KEY (eqp_global_key),
  CONSTRAINT fk_tc_eqp_global_eqp_key__tc_eqp FOREIGN KEY (eqp_key) REFERENCES TC_EQP(eqp_key) ON DELETE CASCADE,
  CONSTRAINT uk_tc_eqp_global_eqp_key_param_name UNIQUE (eqp_key, param_name)
);

CREATE INDEX ix_tc_eqp_global_eqp_key ON TC_EQP_GLOBAL (eqp_key);

-- =========================
-- 2.3 WORK
-- =========================
CREATE TABLE TC_WORK (
  work_key    NUMBER(19) GENERATED BY DEFAULT AS IDENTITY,
  eqp_key     NUMBER(19) NOT NULL,
  work_id     VARCHAR2(64) NOT NULL,
  operator_id VARCHAR2(64) NULL,
  step_seq    NUMBER(10) NULL,
  work_state  VARCHAR2(20) NOT NULL,
  start_time  TIMESTAMP(3) WITH TIME ZONE NULL,
  end_time    TIMESTAMP(3) WITH TIME ZONE NULL,
  mes_message CLOB NULL,
  created_at  TIMESTAMP(3) WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at  TIMESTAMP(3) WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

  CONSTRAINT pk_tc_work PRIMARY KEY (work_key),
  CONSTRAINT fk_tc_work_eqp_key__tc_eqp FOREIGN KEY (eqp_key) REFERENCES TC_EQP(eqp_key),
  CONSTRAINT uk_tc_work_eqp_key_work_id UNIQUE (eqp_key, work_id),
  CONSTRAINT ck_tc_work_step_seq CHECK (step_seq IS NULL OR step_seq >= 0),
  CONSTRAINT ck_tc_work_work_state CHECK (work_state IN ('QUEUED','RUNNING','COMPLETED','ABORTED'))
);

CREATE INDEX ix_tc_work_eqp_key    ON TC_WORK (eqp_key);
CREATE INDEX ix_tc_work_work_state ON TC_WORK (work_state);
CREATE INDEX ix_tc_work_created_at ON TC_WORK (created_at);

CREATE TABLE TC_WORK_PARAM (
  work_param_key NUMBER(19) GENERATED BY DEFAULT AS IDENTITY,
  work_key       NUMBER(19) NOT NULL,
  param_name     VARCHAR2(100) NOT NULL,
  param_value    VARCHAR2(2000) NULL,
  updated_at     TIMESTAMP(3) WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

  CONSTRAINT pk_tc_work_param PRIMARY KEY (work_param_key),
  CONSTRAINT fk_tc_work_param_work_key__tc_work FOREIGN KEY (work_key) REFERENCES TC_WORK(work_key) ON DELETE CASCADE,
  CONSTRAINT uk_tc_work_param_work_key_param_name UNIQUE (work_key, param_name)
);

CREATE INDEX ix_tc_work_param_work_key ON TC_WORK_PARAM (work_key);

CREATE TABLE TC_WORK_CARRIER (
  work_carrier_key NUMBER(19) GENERATED BY DEFAULT AS IDENTITY,
  work_key         NUMBER(19) NOT NULL,
  carrier_id       VARCHAR2(64) NOT NULL,
  port_id          VARCHAR2(20) NULL,
  slot_map         VARCHAR2(255) NULL,
  total_qty        NUMBER(10) NULL,
  good_qty         NUMBER(10) NULL,
  scrap_qty        NUMBER(10) NULL,
  updated_at       TIMESTAMP(3) WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

  CONSTRAINT pk_tc_work_carrier PRIMARY KEY (work_carrier_key),
  CONSTRAINT fk_tc_work_carrier_work_key__tc_work FOREIGN KEY (work_key) REFERENCES TC_WORK(work_key) ON DELETE CASCADE,
  CONSTRAINT uk_tc_work_carrier_work_key_carrier_id UNIQUE (work_key, carrier_id),
  CONSTRAINT ck_tc_work_carrier_total_qty CHECK (total_qty IS NULL OR total_qty >= 0),
  CONSTRAINT ck_tc_work_carrier_good_qty CHECK (good_qty IS NULL OR good_qty >= 0),
  CONSTRAINT ck_tc_work_carrier_scrap_qty CHECK (scrap_qty IS NULL OR scrap_qty >= 0)
);

CREATE INDEX ix_tc_work_carrier_work_key   ON TC_WORK_CARRIER (work_key);
CREATE INDEX ix_tc_work_carrier_carrier_id ON TC_WORK_CARRIER (carrier_id);
CREATE INDEX ix_tc_work_carrier_port_id    ON TC_WORK_CARRIER (port_id);

CREATE TABLE TC_WORK_CARRIER_SLOT (
  carrier_slot_key NUMBER(19) GENERATED BY DEFAULT AS IDENTITY,
  work_carrier_key NUMBER(19) NOT NULL,
  slot_no          NUMBER(10) NOT NULL,
  slot_state       VARCHAR2(50) NOT NULL, -- CHECK 없음(정책 문자열)
  lot_id           VARCHAR2(64) NULL,
  updated_at       TIMESTAMP(3) WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

  CONSTRAINT pk_tc_work_carrier_slot PRIMARY KEY (carrier_slot_key),
  CONSTRAINT fk_tc_work_carrier_slot_work_carrier_key__tc_work_carrier
    FOREIGN KEY (work_carrier_key) REFERENCES TC_WORK_CARRIER(work_carrier_key) ON DELETE CASCADE,
  CONSTRAINT uk_tc_work_carrier_slot_work_carrier_key_slot_no UNIQUE (work_carrier_key, slot_no),
  CONSTRAINT ck_tc_work_carrier_slot_slot_no CHECK (slot_no >= 1)
);

CREATE INDEX ix_tc_work_carrier_slot_work_carrier_key ON TC_WORK_CARRIER_SLOT (work_carrier_key);
CREATE INDEX ix_tc_work_carrier_slot_lot_id           ON TC_WORK_CARRIER_SLOT (lot_id);

CREATE TABLE TC_WORK_LOT (
  work_lot_key  NUMBER(19) GENERATED BY DEFAULT AS IDENTITY,
  work_key      NUMBER(19) NOT NULL,
  carrier_id    VARCHAR2(64) NULL,
  lot_id        VARCHAR2(64) NOT NULL,
  parent_lot_id VARCHAR2(64) NULL,
  chamber_id    VARCHAR2(64) NULL,
  updated_at    TIMESTAMP(3) WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

  CONSTRAINT pk_tc_work_lot PRIMARY KEY (work_lot_key),
  CONSTRAINT fk_tc_work_lot_work_key__tc_work FOREIGN KEY (work_key) REFERENCES TC_WORK(work_key) ON DELETE CASCADE,
  CONSTRAINT uk_tc_work_lot_work_key_lot_id UNIQUE (work_key, lot_id)
);

CREATE INDEX ix_tc_work_lot_work_key   ON TC_WORK_LOT (work_key);
CREATE INDEX ix_tc_work_lot_lot_id     ON TC_WORK_LOT (lot_id);
CREATE INDEX ix_tc_work_lot_carrier_id ON TC_WORK_LOT (carrier_id);

CREATE TABLE TC_WORK_CONTROLJOB (
  control_job_key  NUMBER(19) GENERATED BY DEFAULT AS IDENTITY,
  work_key         NUMBER(19) NOT NULL,
  controljob_id    VARCHAR2(64) NOT NULL,
  controljob_state VARCHAR2(20) NOT NULL,
  created_at       TIMESTAMP(3) WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at       TIMESTAMP(3) WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

  CONSTRAINT pk_tc_work_controljob PRIMARY KEY (control_job_key),
  CONSTRAINT fk_tc_work_controljob_work_key__tc_work FOREIGN KEY (work_key) REFERENCES TC_WORK(work_key) ON DELETE CASCADE,
  CONSTRAINT uk_tc_work_controljob_work_key_controljob_id UNIQUE (work_key, controljob_id),
  CONSTRAINT ck_tc_work_controljob_state CHECK (controljob_state IN ('CREATED','QUEUED','RUNNING','PAUSED','COMPLETED','ABORTED','FAILED'))
);

CREATE INDEX ix_tc_work_controljob_work_key      ON TC_WORK_CONTROLJOB (work_key);
CREATE INDEX ix_tc_work_controljob_controljob_id ON TC_WORK_CONTROLJOB (controljob_id);

CREATE TABLE TC_WORK_PROCESSJOB (
  process_job_key  NUMBER(19) GENERATED BY DEFAULT AS IDENTITY,
  control_job_key  NUMBER(19) NOT NULL,
  processjob_id    VARCHAR2(64) NOT NULL,
  processjob_state VARCHAR2(20) NOT NULL,
  recipe_id        VARCHAR2(128) NOT NULL,
  created_at       TIMESTAMP(3) WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at       TIMESTAMP(3) WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

  CONSTRAINT pk_tc_work_processjob PRIMARY KEY (process_job_key),
  CONSTRAINT fk_tc_work_processjob_control_job_key__tc_work_controljob
    FOREIGN KEY (control_job_key) REFERENCES TC_WORK_CONTROLJOB(control_job_key) ON DELETE CASCADE,
  CONSTRAINT uk_tc_work_processjob_control_job_key_processjob_id UNIQUE (control_job_key, processjob_id),
  CONSTRAINT ck_tc_work_processjob_state CHECK (processjob_state IN ('CREATED','QUEUED','RUNNING','PAUSED','COMPLETED','ABORTED','FAILED'))
);

CREATE INDEX ix_tc_work_processjob_control_job_key ON TC_WORK_PROCESSJOB (control_job_key);
CREATE INDEX ix_tc_work_processjob_processjob_id   ON TC_WORK_PROCESSJOB (processjob_id);

CREATE TABLE TC_WORK_PROCESSJOB_LOT_MAP (
  pj_lot_map_key  NUMBER(19) GENERATED BY DEFAULT AS IDENTITY,
  process_job_key NUMBER(19) NOT NULL,
  work_lot_key    NUMBER(19) NOT NULL,
  map_role        VARCHAR2(20) NULL,
  map_order       VARCHAR2(20) NULL,
  created_at      TIMESTAMP(3) WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at      TIMESTAMP(3) WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

  CONSTRAINT pk_tc_work_processjob_lot_map PRIMARY KEY (pj_lot_map_key),
  CONSTRAINT fk_tc_work_pj_lot_map_process_job_key__tc_work_processjob
    FOREIGN KEY (process_job_key) REFERENCES TC_WORK_PROCESSJOB(process_job_key) ON DELETE CASCADE,
  CONSTRAINT fk_tc_work_pj_lot_map_work_lot_key__tc_work_lot
    FOREIGN KEY (work_lot_key) REFERENCES TC_WORK_LOT(work_lot_key) ON DELETE CASCADE,
  CONSTRAINT uk_tc_work_pj_lot_map_process_job_key_work_lot_key UNIQUE (process_job_key, work_lot_key),
  CONSTRAINT ck_tc_work_pj_lot_map_map_order CHECK (map_order IS NULL OR map_order IN ('FORWARD','REVERSE'))
);

CREATE INDEX ix_tc_work_pj_lot_map_process_job_key ON TC_WORK_PROCESSJOB_LOT_MAP (process_job_key);
CREATE INDEX ix_tc_work_pj_lot_map_work_lot_key    ON TC_WORK_PROCESSJOB_LOT_MAP (work_lot_key);

-- =========================
-- 2.4 UI / AUTH
-- =========================
CREATE TABLE TC_USER_INFO (
  user_pk       NUMBER(19) GENERATED BY DEFAULT AS IDENTITY,
  company       VARCHAR2(100) NOT NULL,
  department    VARCHAR2(100) NOT NULL,
  user_name     VARCHAR2(100) NOT NULL,
  user_id       VARCHAR2(50)  NOT NULL,
  user_id_norm  VARCHAR2(50)  NOT NULL,
  password_hash VARCHAR2(255) NOT NULL,
  email         VARCHAR2(255) NOT NULL,
  status        VARCHAR2(20)  NOT NULL DEFAULT 'ACTIVE',
  created_at    TIMESTAMP(3) WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at    TIMESTAMP(3) WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_by    VARCHAR2(50) NOT NULL DEFAULT 'SYSTEM',
  updated_by    VARCHAR2(50) NOT NULL DEFAULT 'SYSTEM',

  CONSTRAINT pk_tc_user_info PRIMARY KEY (user_pk),
  CONSTRAINT uk_tc_user_info_user_id_norm UNIQUE (user_id_norm),
  CONSTRAINT uk_tc_user_info_email UNIQUE (email),
  CONSTRAINT ck_tc_user_info_status CHECK (status IN ('ACTIVE','LOCKED','DISABLED','DELETED'))
);

CREATE INDEX ix_tc_user_info_company_department ON TC_USER_INFO (company, department);
CREATE INDEX ix_tc_user_info_status            ON TC_USER_INFO (status);
CREATE INDEX ix_tc_user_info_email             ON TC_USER_INFO (email);

CREATE TABLE TC_UI_PERMISSION (
  perm_id       NUMBER(19) GENERATED BY DEFAULT AS IDENTITY,
  perm_code     VARCHAR2(80)  NOT NULL,
  perm_name     VARCHAR2(120) NOT NULL,
  resource_type VARCHAR2(10)  NOT NULL,
  match_type    VARCHAR2(10)  NOT NULL DEFAULT 'PREFIX',
  resource      VARCHAR2(255) NOT NULL,
  http_method   VARCHAR2(10)  NULL,
  description   VARCHAR2(1000) NULL,
  is_active     NUMBER(1) NOT NULL DEFAULT 1,
  created_at    TIMESTAMP(3) WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at    TIMESTAMP(3) WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_by    VARCHAR2(50) NOT NULL DEFAULT 'SYSTEM',
  updated_by    VARCHAR2(50) NOT NULL DEFAULT 'SYSTEM',

  CONSTRAINT pk_tc_ui_permission PRIMARY KEY (perm_id),
  CONSTRAINT uk_tc_ui_permission_perm_code UNIQUE (perm_code),
  CONSTRAINT ck_tc_ui_permission_resource_type CHECK (resource_type IN ('PAGE','API')),
  CONSTRAINT ck_tc_ui_permission_match_type CHECK (match_type IN ('EXACT','PREFIX','REGEX')),
  CONSTRAINT ck_tc_ui_permission_is_active CHECK (is_active IN (0,1))
);

CREATE INDEX ix_tc_ui_permission_resource_type_resource ON TC_UI_PERMISSION (resource_type, resource);
CREATE INDEX ix_tc_ui_permission_is_active             ON TC_UI_PERMISSION (is_active);

CREATE TABLE TC_USER_GROUP (
  group_id    NUMBER(19) GENERATED BY DEFAULT AS IDENTITY,
  group_code  VARCHAR2(50)  NOT NULL,
  group_name  VARCHAR2(100) NOT NULL,
  description VARCHAR2(1000) NULL,
  is_active   NUMBER(1) NOT NULL DEFAULT 1,
  created_at  TIMESTAMP(3) WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at  TIMESTAMP(3) WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

  CONSTRAINT pk_tc_user_group PRIMARY KEY (group_id),
  CONSTRAINT uk_tc_user_group_group_code UNIQUE (group_code),
  CONSTRAINT ck_tc_user_group_is_active CHECK (is_active IN (0,1))
);

CREATE INDEX ix_tc_user_group_is_active ON TC_USER_GROUP (is_active);

CREATE TABLE TC_USER_GROUP_MEMBER (
  ugm_key     NUMBER(19) GENERATED BY DEFAULT AS IDENTITY,
  user_pk     NUMBER(19) NOT NULL,
  group_id    NUMBER(19) NOT NULL,
  granted_at  TIMESTAMP(3) WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  granted_by  VARCHAR2(50) NULL,

  CONSTRAINT pk_tc_user_group_member PRIMARY KEY (ugm_key),
  CONSTRAINT fk_tc_user_group_member_user_pk__tc_user_info
    FOREIGN KEY (user_pk) REFERENCES TC_USER_INFO(user_pk) ON DELETE CASCADE,
  CONSTRAINT fk_tc_user_group_member_group_id__tc_user_group
    FOREIGN KEY (group_id) REFERENCES TC_USER_GROUP(group_id) ON DELETE CASCADE,
  CONSTRAINT uk_tc_user_group_member_user_pk_group_id UNIQUE (user_pk, group_id)
);

CREATE INDEX ix_tc_user_group_member_group_id ON TC_USER_GROUP_MEMBER (group_id);
CREATE INDEX ix_tc_user_group_member_user_pk  ON TC_USER_GROUP_MEMBER (user_pk);

CREATE TABLE TC_USER_GROUP_PERMISSION (
  ugp_key    NUMBER(19) GENERATED BY DEFAULT AS IDENTITY,
  group_id   NUMBER(19) NOT NULL,
  perm_id    NUMBER(19) NOT NULL,
  granted_at TIMESTAMP(3) WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  granted_by VARCHAR2(50) NULL,

  CONSTRAINT pk_tc_user_group_permission PRIMARY KEY (ugp_key),
  CONSTRAINT fk_tc_user_group_permission_group_id__tc_user_group
    FOREIGN KEY (group_id) REFERENCES TC_USER_GROUP(group_id) ON DELETE CASCADE,
  CONSTRAINT fk_tc_user_group_permission_perm_id__tc_ui_permission
    FOREIGN KEY (perm_id) REFERENCES TC_UI_PERMISSION(perm_id) ON DELETE CASCADE,
  CONSTRAINT uk_tc_user_group_permission_group_id_perm_id UNIQUE (group_id, perm_id)
);

CREATE INDEX ix_tc_user_group_permission_perm_id  ON TC_USER_GROUP_PERMISSION (perm_id);
CREATE INDEX ix_tc_user_group_permission_group_id ON TC_USER_GROUP_PERMISSION (group_id);

CREATE TABLE TC_UI_AUTH_SESSION (
  token        VARCHAR2(64) NOT NULL,
  user_pk      NUMBER(19) NOT NULL,
  issued_at    TIMESTAMP(3) WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  expires_at   TIMESTAMP(3) WITH TIME ZONE NOT NULL,
  last_seen_at TIMESTAMP(3) WITH TIME ZONE NULL,
  revoked      NUMBER(1) NOT NULL DEFAULT 0,

  CONSTRAINT pk_tc_ui_auth_session PRIMARY KEY (token),
  CONSTRAINT fk_tc_ui_auth_session_user_pk__tc_user_info
    FOREIGN KEY (user_pk) REFERENCES TC_USER_INFO(user_pk),
  CONSTRAINT ck_tc_ui_auth_session_revoked CHECK (revoked IN (0,1))
);

CREATE INDEX ix_tc_ui_auth_session_user_pk               ON TC_UI_AUTH_SESSION (user_pk);
CREATE INDEX ix_tc_ui_auth_session_expires_at            ON TC_UI_AUTH_SESSION (expires_at);
CREATE INDEX ix_tc_ui_auth_session_revoked_expires_at    ON TC_UI_AUTH_SESSION (revoked, expires_at);

-- =========================
-- 2.5 OUTBOX
-- =========================
CREATE TABLE TC_MSG_SEND_QUEUE (
  msg_key         NUMBER(19) GENERATED BY DEFAULT AS IDENTITY,
  idempotency_key VARCHAR2(128) NOT NULL,
  topic           VARCHAR2(200) NOT NULL,
  message_key     VARCHAR2(200) NULL,
  headers_json    CLOB NULL,
  payload_json    CLOB NOT NULL,
  status          VARCHAR2(16) NOT NULL,
  retry_count     NUMBER(10) NOT NULL DEFAULT 0,
  next_retry_at   TIMESTAMP(3) WITH TIME ZONE NULL,
  locked_by       VARCHAR2(64) NULL,
  locked_until    TIMESTAMP(3) WITH TIME ZONE NULL,
  created_at      TIMESTAMP(3) WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at      TIMESTAMP(3) WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

  CONSTRAINT pk_tc_msg_send_queue PRIMARY KEY (msg_key),
  CONSTRAINT uk_tc_msg_send_queue_topic_idempotency_key UNIQUE (topic, idempotency_key),
  CONSTRAINT ck_tc_msg_send_queue_status CHECK (status IN ('PENDING','SENDING','SENT','FAILED','DEAD')),
  CONSTRAINT ck_tc_msg_send_queue_retry_count CHECK (retry_count >= 0)
);

CREATE INDEX ix_tc_msg_send_queue_status_next_retry_at ON TC_MSG_SEND_QUEUE (status, next_retry_at);
CREATE INDEX ix_tc_msg_send_queue_locked_until         ON TC_MSG_SEND_QUEUE (locked_until);
CREATE INDEX ix_tc_msg_send_queue_topic_status         ON TC_MSG_SEND_QUEUE (topic, status);

CREATE TABLE TC_MSG_SEND_LOG (
  send_log_key    NUMBER(19) GENERATED BY DEFAULT AS IDENTITY,
  msg_key         NUMBER(19) NOT NULL,
  attempt_no      NUMBER(10) NOT NULL,
  result          VARCHAR2(16) NOT NULL,
  kafka_partition NUMBER(10) NULL,
  kafka_offset    NUMBER(19) NULL,
  error_code      VARCHAR2(64) NULL,
  error_message   CLOB NULL,
  sent_at         TIMESTAMP(3) WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

  CONSTRAINT pk_tc_msg_send_log PRIMARY KEY (send_log_key),
  CONSTRAINT fk_tc_msg_send_log_msg_key__tc_msg_send_queue
    FOREIGN KEY (msg_key) REFERENCES TC_MSG_SEND_QUEUE(msg_key) ON DELETE CASCADE,
  CONSTRAINT ck_tc_msg_send_log_attempt_no CHECK (attempt_no >= 1),
  CONSTRAINT ck_tc_msg_send_log_result CHECK (result IN ('SUCCESS','FAIL'))
);

CREATE INDEX ix_tc_msg_send_log_msg_key_attempt_no ON TC_MSG_SEND_LOG (msg_key, attempt_no);
CREATE INDEX ix_tc_msg_send_log_sent_at           ON TC_MSG_SEND_LOG (sent_at);

COMMIT;
