-- =====================================================================
-- 차세대 TC Version 5.0 (PostgreSQL) - DDL
-- (1) 모든 테이블 DROP (CASCADE)
-- (2) 모든 테이블 CREATE + 제약/인덱스
-- 스키마: public
-- =====================================================================

BEGIN;

-- ---------------------------------------------------------------------
-- 1) DROP (의존성 고려 없이 CASCADE로 정리)
-- ---------------------------------------------------------------------
DROP TABLE IF EXISTS public.tc_msg_send_log CASCADE;
DROP TABLE IF EXISTS public.tc_msg_send_queue CASCADE;

DROP TABLE IF EXISTS public.tc_ui_auth_session CASCADE;
DROP TABLE IF EXISTS public.tc_user_group_permission CASCADE;
DROP TABLE IF EXISTS public.tc_user_group_member CASCADE;
DROP TABLE IF EXISTS public.tc_user_group CASCADE;
DROP TABLE IF EXISTS public.tc_ui_permission CASCADE;
DROP TABLE IF EXISTS public.tc_user_info CASCADE;

DROP TABLE IF EXISTS public.tc_model_dcop_item CASCADE;
DROP TABLE IF EXISTS public.tc_model_mdf CASCADE;
DROP TABLE IF EXISTS public.tc_model_workflow CASCADE;
DROP TABLE IF EXISTS public.tc_model_eventid CASCADE;
DROP TABLE IF EXISTS public.tc_model_reportid CASCADE;
DROP TABLE IF EXISTS public.tc_model_variableid CASCADE;
DROP TABLE IF EXISTS public.tc_model_socket_message CASCADE;
DROP TABLE IF EXISTS public.tc_model_secs_message CASCADE;
DROP TABLE IF EXISTS public.tc_model_param CASCADE;
DROP TABLE IF EXISTS public.tc_model_version CASCADE;
DROP TABLE IF EXISTS public.tc_model CASCADE;

DROP TABLE IF EXISTS public.tc_work_processjob_lot_map CASCADE;
DROP TABLE IF EXISTS public.tc_work_processjob CASCADE;
DROP TABLE IF EXISTS public.tc_work_controljob CASCADE;
DROP TABLE IF EXISTS public.tc_work_lot CASCADE;
DROP TABLE IF EXISTS public.tc_work_carrier_slot CASCADE;
DROP TABLE IF EXISTS public.tc_work_carrier CASCADE;
DROP TABLE IF EXISTS public.tc_work_param CASCADE;
DROP TABLE IF EXISTS public.tc_work CASCADE;

DROP TABLE IF EXISTS public.tc_eqp_global CASCADE;
DROP TABLE IF EXISTS public.tc_eqp_param CASCADE;
DROP TABLE IF EXISTS public.tc_eqp_port_status CASCADE;
DROP TABLE IF EXISTS public.tc_eqp_log CASCADE;
DROP TABLE IF EXISTS public.tc_eqp_state_hist CASCADE;
DROP TABLE IF EXISTS public.tc_eqp_state CASCADE;
DROP TABLE IF EXISTS public.tc_eqp_socket CASCADE;
DROP TABLE IF EXISTS public.tc_eqp_hsms CASCADE;
DROP TABLE IF EXISTS public.tc_eqp CASCADE;
DROP TABLE IF EXISTS public.tc_eqp_socket_protocol_type CASCADE;

DROP TABLE IF EXISTS public.tc_jar_business CASCADE;
DROP TABLE IF EXISTS public.tc_jar_gateway CASCADE;


-- ---------------------------------------------------------------------
-- 2) CREATE
-- ---------------------------------------------------------------------

-- =========================
-- 2.1 MODEL
-- =========================
CREATE TABLE public.tc_model (
    model_key      BIGINT GENERATED BY DEFAULT AS IDENTITY,
    model_name     VARCHAR(128) NOT NULL,
    comm_interface VARCHAR(16)  NOT NULL,
    maker          VARCHAR(32)  NULL,
    created_at     TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at     TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by     VARCHAR(50) NOT NULL DEFAULT 'SYSTEM',
    updated_by     VARCHAR(50) NOT NULL DEFAULT 'SYSTEM',

    CONSTRAINT pk_tc_model PRIMARY KEY (model_key),
    CONSTRAINT uk_tc_model_model_name UNIQUE (model_name),
    CONSTRAINT ck_tc_model_comm_interface CHECK (comm_interface IN ('HSMS','SOCKET'))
);

CREATE INDEX ix_tc_model_model_name     ON public.tc_model (model_name);
CREATE INDEX ix_tc_model_comm_interface ON public.tc_model (comm_interface);
CREATE INDEX ix_tc_model_maker          ON public.tc_model (maker);

CREATE TABLE public.tc_model_version (
    model_version_key BIGINT GENERATED BY DEFAULT AS IDENTITY,
    model_key         BIGINT NOT NULL,
    model_version     VARCHAR(32) NOT NULL,
    status            VARCHAR(16) NOT NULL,
    created_at        TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at        TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by        VARCHAR(50) NOT NULL DEFAULT 'SYSTEM',
    updated_by        VARCHAR(50) NOT NULL DEFAULT 'SYSTEM',

    CONSTRAINT pk_tc_model_version PRIMARY KEY (model_version_key),
    CONSTRAINT fk_tc_model_version_model_key__tc_model
        FOREIGN KEY (model_key) REFERENCES public.tc_model(model_key) ON DELETE CASCADE,
    CONSTRAINT uk_tc_model_version_model_key_model_version UNIQUE (model_key, model_version),
    CONSTRAINT ck_tc_model_version_status CHECK (status IN ('DRAFT','ACTIVE','DEPRECATED'))
);

CREATE INDEX ix_tc_model_version_model_key ON public.tc_model_version (model_key);
CREATE INDEX ix_tc_model_version_status    ON public.tc_model_version (status);

CREATE TABLE public.tc_model_param (
    model_param_key BIGINT GENERATED BY DEFAULT AS IDENTITY,
    model_version_key BIGINT NOT NULL,
    param_name      VARCHAR(128) NOT NULL,
    param_value     VARCHAR(2000) NULL,
    updated_at      TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_tc_model_param PRIMARY KEY (model_param_key),
    CONSTRAINT fk_tc_model_param_model_version_key__tc_model_version
        FOREIGN KEY (model_version_key) REFERENCES public.tc_model_version(model_version_key) ON DELETE CASCADE,
    CONSTRAINT uk_tc_model_param_model_version_key_param_name UNIQUE (model_version_key, param_name)
);

CREATE INDEX ix_tc_model_param_model_version_key ON public.tc_model_param (model_version_key);

CREATE TABLE public.tc_model_secs_message (
    secs_msg_key   BIGINT GENERATED BY DEFAULT AS IDENTITY,
    model_version_key BIGINT NOT NULL,
    secs_msg_name  VARCHAR(100) NOT NULL,
    description    VARCHAR(2000) NULL,
    data_index     VARCHAR(200)  NULL,
    updated_at     TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_tc_model_secs_message PRIMARY KEY (secs_msg_key),
    CONSTRAINT fk_tc_model_secs_message_model_version_key__tc_model_version
        FOREIGN KEY (model_version_key) REFERENCES public.tc_model_version(model_version_key) ON DELETE CASCADE,
    CONSTRAINT uk_tc_model_secs_message_model_version_key UNIQUE (model_version_key)
);

CREATE INDEX ix_tc_model_secs_message_model_version_key ON public.tc_model_secs_message (model_version_key);
CREATE INDEX ix_tc_model_secs_message_secs_msg_name ON public.tc_model_secs_message (secs_msg_name);

CREATE TABLE public.tc_model_socket_message (
    socket_msg_key  BIGINT GENERATED BY DEFAULT AS IDENTITY,
    model_version_key BIGINT NOT NULL,
    socket_msg_name VARCHAR(100) NOT NULL,
    description     VARCHAR(2000) NULL,
    data_index      VARCHAR(200)  NULL,
    updated_at      TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_tc_model_socket_message PRIMARY KEY (socket_msg_key),
    CONSTRAINT fk_tc_model_socket_message_model_version_key__tc_model_version
        FOREIGN KEY (model_version_key) REFERENCES public.tc_model_version(model_version_key) ON DELETE CASCADE,
    CONSTRAINT uk_tc_model_socket_message_model_version_key UNIQUE (model_version_key)
);

CREATE INDEX ix_tc_model_socket_message_model_version_key ON public.tc_model_socket_message (model_version_key);
CREATE INDEX ix_tc_model_socket_message_socket_msg_name ON public.tc_model_socket_message (socket_msg_name);

CREATE TABLE public.tc_model_variableid (
    variable_key     BIGINT GENERATED BY DEFAULT AS IDENTITY,
    model_version_key BIGINT NOT NULL,
    variable_id      VARCHAR(100) NOT NULL,
    variable_id_type VARCHAR(10) NOT NULL DEFAULT 'SVID',
    description      VARCHAR(2000) NULL,
    updated_at       TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_tc_model_variableid PRIMARY KEY (variable_key),
    CONSTRAINT fk_tc_model_variableid_model_version_key__tc_model_version
        FOREIGN KEY (model_version_key) REFERENCES public.tc_model_version(model_version_key) ON DELETE CASCADE,
    CONSTRAINT uk_tc_model_variableid_model_version_key_type_variable_id UNIQUE (model_version_key, variable_id_type, variable_id),
    CONSTRAINT ck_tc_model_variableid_type CHECK (variable_id_type IN ('SVID','DVID','ECID','CEID'))
);

CREATE INDEX ix_tc_model_variableid_model_version_key ON public.tc_model_variableid (model_version_key);
CREATE INDEX ix_tc_model_variableid_variable_id ON public.tc_model_variableid (variable_id);

CREATE TABLE public.tc_model_reportid (
    report_key  BIGINT GENERATED BY DEFAULT AS IDENTITY,
    model_version_key BIGINT NOT NULL,
    report_id   VARCHAR(100) NOT NULL,
    variable_id VARCHAR(1000) NULL,
    enabled     BOOLEAN NOT NULL DEFAULT FALSE,
    updated_at  TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_tc_model_reportid PRIMARY KEY (report_key),
    CONSTRAINT fk_tc_model_reportid_model_version_key__tc_model_version
        FOREIGN KEY (model_version_key) REFERENCES public.tc_model_version(model_version_key) ON DELETE CASCADE,
    CONSTRAINT uk_tc_model_reportid_model_version_key_report_id UNIQUE (model_version_key, report_id),
    CONSTRAINT ck_tc_model_reportid_enabled CHECK (enabled IN (TRUE, FALSE))
);

CREATE INDEX ix_tc_model_reportid_model_version_key ON public.tc_model_reportid (model_version_key);
CREATE INDEX ix_tc_model_reportid_enabled  ON public.tc_model_reportid (enabled);

CREATE TABLE public.tc_model_eventid (
    event_key  BIGINT GENERATED BY DEFAULT AS IDENTITY,
    model_version_key BIGINT NOT NULL,
    event_id   VARCHAR(100) NOT NULL,
    report_id  VARCHAR(1000) NULL,
    enabled    BOOLEAN NOT NULL DEFAULT FALSE,
    updated_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_tc_model_eventid PRIMARY KEY (event_key),
    CONSTRAINT fk_tc_model_eventid_model_version_key__tc_model_version
        FOREIGN KEY (model_version_key) REFERENCES public.tc_model_version(model_version_key) ON DELETE CASCADE,
    CONSTRAINT uk_tc_model_eventid_model_version_key_event_id UNIQUE (model_version_key, event_id),
    CONSTRAINT ck_tc_model_eventid_enabled CHECK (enabled IN (TRUE, FALSE))
);

CREATE INDEX ix_tc_model_eventid_model_version_key ON public.tc_model_eventid (model_version_key);
CREATE INDEX ix_tc_model_eventid_enabled  ON public.tc_model_eventid (enabled);

CREATE TABLE public.tc_model_workflow (
    workflow_key      BIGINT GENERATED BY DEFAULT AS IDENTITY,
    model_version_key BIGINT NOT NULL,
    workflow_name     VARCHAR(200) NOT NULL,
    message_name      VARCHAR(200) NOT NULL,
    event_id          VARCHAR(200) NULL,
    transaction_id    VARCHAR(200) NULL,
    workflow_filter   VARCHAR(200) NULL,
    action_name       VARCHAR(200) NOT NULL,
    action_data_index VARCHAR(1000) NULL,
    updated_at        TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_tc_model_workflow PRIMARY KEY (workflow_key),
    CONSTRAINT fk_tc_model_workflow_model_version_key__tc_model_version
        FOREIGN KEY (model_version_key) REFERENCES public.tc_model_version(model_version_key) ON DELETE CASCADE,
    CONSTRAINT uk_tc_model_workflow_model_version_key_workflow_name_message_name UNIQUE (model_version_key, workflow_name, message_name)
);

CREATE INDEX ix_tc_model_workflow_model_version_key ON public.tc_model_workflow (model_version_key);
CREATE INDEX ix_tc_model_workflow_workflow_name ON public.tc_model_workflow (workflow_name);

CREATE TABLE public.tc_model_mdf (
    mdf_key    BIGINT GENERATED BY DEFAULT AS IDENTITY,
    model_version_key BIGINT NOT NULL,
    mdf_name   VARCHAR(100) NOT NULL,
    mdf_file   BYTEA NOT NULL,
    updated_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_tc_model_mdf PRIMARY KEY (mdf_key),
    CONSTRAINT fk_tc_model_mdf_model_version_key__tc_model_version
        FOREIGN KEY (model_version_key) REFERENCES public.tc_model_version(model_version_key) ON DELETE CASCADE,
    CONSTRAINT uk_tc_model_mdf_model_version_key UNIQUE (model_version_key)
);

CREATE INDEX ix_tc_model_mdf_model_version_key ON public.tc_model_mdf (model_version_key);

CREATE TABLE public.tc_model_dcop_item (
    dcop_item_key     BIGINT GENERATED BY DEFAULT AS IDENTITY,
    model_version_key BIGINT NOT NULL,
    dcop_item_name    VARCHAR(200) NOT NULL,
    workflow_name     VARCHAR(200) NULL,
    event_id          VARCHAR(100) NULL,
    variable_id       VARCHAR(100) NULL,
    collection_rule   VARCHAR(10)  NULL,
    calculation_rule  VARCHAR(20)  NULL,
    order_rule        INT          NULL,
    updated_at        TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_tc_model_dcop_item PRIMARY KEY (dcop_item_key),
    CONSTRAINT fk_tc_model_dcop_item_model_version_key__tc_model_version
        FOREIGN KEY (model_version_key) REFERENCES public.tc_model_version(model_version_key) ON DELETE CASCADE,
    CONSTRAINT uk_tc_model_dcop_item_model_version_key_dcop_item_name UNIQUE (model_version_key, dcop_item_name),
    CONSTRAINT ck_tc_model_dcop_item_collection_rule CHECK (collection_rule IS NULL OR collection_rule IN ('FIRST','LAST')),
    CONSTRAINT ck_tc_model_dcop_item_calculation_rule CHECK (calculation_rule IS NULL OR calculation_rule IN ('ADD','MULTIPLY','SUBTRACT','NONE')),
    CONSTRAINT ck_tc_model_dcop_item_order_rule CHECK (order_rule IS NULL OR order_rule >= 0)
);

CREATE INDEX ix_tc_model_dcop_item_model_version_key ON public.tc_model_dcop_item (model_version_key);
CREATE INDEX ix_tc_model_dcop_item_event_id  ON public.tc_model_dcop_item (event_id);

-- =========================
-- 2.2 EQP
-- =========================
CREATE TABLE public.tc_eqp_socket_protocol_type (
    socket_protocol_type      VARCHAR(32),
    socket_protocol_type_name VARCHAR(100) NOT NULL,
    parse_start_rule           VARCHAR(1000) NULL,
    parse_end_rule             VARCHAR(1000) NULL,
    parse_regex                VARCHAR(1000) NULL,
    description                VARCHAR(1000) NULL,

    CONSTRAINT pk_tc_eqp_socket_protocol_type PRIMARY KEY (socket_protocol_type)
);

CREATE TABLE public.tc_eqp (
    eqp_key          BIGINT GENERATED BY DEFAULT AS IDENTITY,
    eqp_id           VARCHAR(64) NOT NULL,
    comm_interface   VARCHAR(16) NOT NULL,
    comm_mode        VARCHAR(10) NOT NULL,
    route_partition  INTEGER NULL,
    eqp_ip           VARCHAR(45) NOT NULL,
    eqp_port         INT NOT NULL,
    model_version_key BIGINT NOT NULL,
    enabled          BOOLEAN NOT NULL DEFAULT TRUE,
    created_at       TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at       TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by       VARCHAR(50) NOT NULL DEFAULT 'SYSTEM',
    updated_by       VARCHAR(50) NOT NULL DEFAULT 'SYSTEM',

    CONSTRAINT pk_tc_eqp PRIMARY KEY (eqp_key),
    CONSTRAINT uk_tc_eqp_eqp_id UNIQUE (eqp_id),
    CONSTRAINT fk_tc_eqp_model_version_key__tc_model_version
        FOREIGN KEY (model_version_key) REFERENCES public.tc_model_version(model_version_key),
    CONSTRAINT ck_tc_eqp_comm_interface CHECK (comm_interface IN ('HSMS','SOCKET')),
    CONSTRAINT ck_tc_eqp_comm_mode CHECK (comm_mode IN ('ACTIVE','PASSIVE')),
    CONSTRAINT ck_tc_eqp_route_partition CHECK (route_partition IS NULL OR route_partition >= 0),
    CONSTRAINT ck_tc_eqp_eqp_port CHECK (eqp_port BETWEEN 1 AND 65535),
    CONSTRAINT ck_tc_eqp_enabled CHECK (enabled IN (TRUE, FALSE))
);

CREATE INDEX ix_tc_eqp_enabled         ON public.tc_eqp (enabled);
CREATE INDEX ix_tc_eqp_model_version_key ON public.tc_eqp (model_version_key);
CREATE INDEX ix_tc_eqp_comm_interface  ON public.tc_eqp (comm_interface);
CREATE INDEX ix_tc_eqp_route_partition_enabled ON public.tc_eqp (route_partition, enabled);
CREATE INDEX ix_tc_eqp_eqp_ip_port     ON public.tc_eqp (eqp_ip, eqp_port);

CREATE TABLE public.tc_jar_gateway (
    eqp_key       BIGINT NOT NULL,
    jar_file_name VARCHAR(255) NOT NULL,
    jar_file      BYTEA NOT NULL,
    created_at    TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at    TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by    VARCHAR(50) NOT NULL DEFAULT 'SYSTEM',
    updated_by    VARCHAR(50) NOT NULL DEFAULT 'SYSTEM',

    CONSTRAINT pk_tc_jar_gateway PRIMARY KEY (eqp_key),
    CONSTRAINT fk_tc_jar_gateway_eqp_key__tc_eqp
        FOREIGN KEY (eqp_key) REFERENCES public.tc_eqp(eqp_key) ON DELETE CASCADE
);

CREATE TABLE public.tc_jar_business (
    eqp_key       BIGINT NOT NULL,
    jar_file_name VARCHAR(255) NOT NULL,
    jar_file      BYTEA NOT NULL,
    created_at    TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at    TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by    VARCHAR(50) NOT NULL DEFAULT 'SYSTEM',
    updated_by    VARCHAR(50) NOT NULL DEFAULT 'SYSTEM',

    CONSTRAINT pk_tc_jar_business PRIMARY KEY (eqp_key),
    CONSTRAINT fk_tc_jar_business_eqp_key__tc_eqp
        FOREIGN KEY (eqp_key) REFERENCES public.tc_eqp(eqp_key) ON DELETE CASCADE
);

CREATE TABLE public.tc_eqp_hsms (
    eqp_key            BIGINT NOT NULL,
    device_id          INT NOT NULL,
    t3_timeout         INT NOT NULL DEFAULT 45,
    t5_timeout         INT NOT NULL DEFAULT 10,
    t6_timeout         INT NOT NULL DEFAULT 5,
    t7_timeout         INT NOT NULL DEFAULT 10,
    t8_timeout         INT NOT NULL DEFAULT 5,
    link_test_enabled  BOOLEAN NOT NULL DEFAULT TRUE,
    link_test_interval INT NOT NULL DEFAULT 60,
    max_msg_bytes      BIGINT NOT NULL DEFAULT 10485760,
    created_at         TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at         TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_tc_eqp_hsms PRIMARY KEY (eqp_key),
    CONSTRAINT fk_tc_eqp_hsms_eqp_key__tc_eqp
        FOREIGN KEY (eqp_key) REFERENCES public.tc_eqp(eqp_key) ON DELETE CASCADE,
    CONSTRAINT ck_tc_eqp_hsms_device_id CHECK (device_id BETWEEN 0 AND 32767),
    CONSTRAINT ck_tc_eqp_hsms_t3_timeout CHECK (t3_timeout > 0),
    CONSTRAINT ck_tc_eqp_hsms_t5_timeout CHECK (t5_timeout > 0),
    CONSTRAINT ck_tc_eqp_hsms_t6_timeout CHECK (t6_timeout > 0),
    CONSTRAINT ck_tc_eqp_hsms_t7_timeout CHECK (t7_timeout > 0),
    CONSTRAINT ck_tc_eqp_hsms_t8_timeout CHECK (t8_timeout > 0),
    CONSTRAINT ck_tc_eqp_hsms_link_test_enabled CHECK (link_test_enabled IN (TRUE, FALSE)),
    CONSTRAINT ck_tc_eqp_hsms_link_test_interval CHECK (link_test_interval > 0),
    CONSTRAINT ck_tc_eqp_hsms_max_msg_bytes CHECK (max_msg_bytes > 0)
);

CREATE TABLE public.tc_eqp_socket (
    eqp_key               BIGINT NOT NULL,
    socket_protocol_type  VARCHAR(32) NOT NULL,
    charset               VARCHAR(20) NOT NULL DEFAULT 'UTF-8',
    heartbeat_enabled     BOOLEAN NOT NULL DEFAULT TRUE,
    heartbeat_interval    INT NOT NULL DEFAULT 30,
    read_timeout          INT NOT NULL DEFAULT 0,
    write_timeout         INT NOT NULL DEFAULT 0,
    max_frame_size_bytes  INT NOT NULL DEFAULT 8192,
    keep_alive_enabled    BOOLEAN NOT NULL DEFAULT TRUE,
    created_at            TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at            TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_tc_eqp_socket PRIMARY KEY (eqp_key),
    CONSTRAINT fk_tc_eqp_socket_eqp_key__tc_eqp
        FOREIGN KEY (eqp_key) REFERENCES public.tc_eqp(eqp_key) ON DELETE CASCADE,
    CONSTRAINT fk_tc_eqp_socket_socket_protocol_type__tc_eqp_socket_protocol_type
        FOREIGN KEY (socket_protocol_type) REFERENCES public.tc_eqp_socket_protocol_type(socket_protocol_type),
    CONSTRAINT ck_tc_eqp_socket_heartbeat_enabled CHECK (heartbeat_enabled IN (TRUE, FALSE)),
    CONSTRAINT ck_tc_eqp_socket_heartbeat_interval CHECK (heartbeat_interval >= 0),
    CONSTRAINT ck_tc_eqp_socket_read_timeout CHECK (read_timeout >= 0),
    CONSTRAINT ck_tc_eqp_socket_write_timeout CHECK (write_timeout >= 0),
    CONSTRAINT ck_tc_eqp_socket_max_frame_size_bytes CHECK (max_frame_size_bytes > 0),
    CONSTRAINT ck_tc_eqp_socket_keep_alive_enabled CHECK (keep_alive_enabled IN (TRUE, FALSE))
);

CREATE INDEX ix_tc_eqp_socket_socket_protocol_type ON public.tc_eqp_socket (socket_protocol_type);

CREATE TABLE public.tc_eqp_state (
    eqp_key        BIGINT NOT NULL,
    control_state  VARCHAR(20) NULL,
    eqp_state      VARCHAR(20) NULL,
    since_at       TIMESTAMPTZ(3) NULL,
    reason_code    VARCHAR(50) NULL,
    reason_detail  TEXT NULL,
    updated_at     TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_tc_eqp_state PRIMARY KEY (eqp_key),
    CONSTRAINT fk_tc_eqp_state_eqp_key__tc_eqp
        FOREIGN KEY (eqp_key) REFERENCES public.tc_eqp(eqp_key) ON DELETE CASCADE,
    CONSTRAINT ck_tc_eqp_state_control_state CHECK (control_state IS NULL OR control_state IN ('OFFLINE','LOCAL','REMOTE')),
    CONSTRAINT ck_tc_eqp_state_eqp_state CHECK (eqp_state IS NULL OR eqp_state IN ('IDLE','RUN','DOWN','MAINTENANCE','PAUSE'))
);

CREATE TABLE public.tc_eqp_state_hist (
    state_hist_key BIGINT GENERATED BY DEFAULT AS IDENTITY,
    eqp_key        BIGINT NOT NULL,
    state_type     VARCHAR(10) NOT NULL,
    from_state     VARCHAR(50) NULL,
    to_state       VARCHAR(50) NULL,
    changed_at     TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    reason_code    VARCHAR(50) NULL,
    reason_detail  TEXT NULL,

    CONSTRAINT pk_tc_eqp_state_hist PRIMARY KEY (state_hist_key),
    CONSTRAINT fk_tc_eqp_state_hist_eqp_key__tc_eqp
        FOREIGN KEY (eqp_key) REFERENCES public.tc_eqp(eqp_key) ON DELETE CASCADE,
    CONSTRAINT ck_tc_eqp_state_hist_state_type CHECK (state_type IN ('OPER','CONN'))
);

CREATE INDEX ix_tc_eqp_state_hist_eqp_key_changed_at
    ON public.tc_eqp_state_hist (eqp_key, changed_at);
CREATE INDEX ix_tc_eqp_state_hist_state_type_changed_at
    ON public.tc_eqp_state_hist (state_type, changed_at);

CREATE TABLE public.tc_eqp_log (
    eqp_key            BIGINT NOT NULL,
    log_level          VARCHAR(10) NOT NULL DEFAULT 'INFO',
    log_retention_days INT NOT NULL DEFAULT 30,
    log_path           VARCHAR(1000) NULL,
    updated_at         TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_tc_eqp_log PRIMARY KEY (eqp_key),
    CONSTRAINT fk_tc_eqp_log_eqp_key__tc_eqp
        FOREIGN KEY (eqp_key) REFERENCES public.tc_eqp(eqp_key) ON DELETE CASCADE,
    CONSTRAINT ck_tc_eqp_log_log_level CHECK (log_level IN ('TRACE','DEBUG','INFO','WARN','ERROR')),
    CONSTRAINT ck_tc_eqp_log_log_retention_days CHECK (log_retention_days >= 1)
);

CREATE TABLE public.tc_eqp_port_status (
    eqp_port_status_key BIGINT GENERATED BY DEFAULT AS IDENTITY,
    eqp_key             BIGINT NOT NULL,
    port_id             VARCHAR(20) NOT NULL,
    port_type           VARCHAR(20) NULL,
    port_state          VARCHAR(20) NULL,
    carrier_id          VARCHAR(64) NULL,
    carrier_type        VARCHAR(20) NULL,
    carrier_state       VARCHAR(20) NULL,
    updated_at          TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_tc_eqp_port_status PRIMARY KEY (eqp_port_status_key),
    CONSTRAINT fk_tc_eqp_port_status_eqp_key__tc_eqp
        FOREIGN KEY (eqp_key) REFERENCES public.tc_eqp(eqp_key) ON DELETE CASCADE,
    CONSTRAINT uk_tc_eqp_port_status_eqp_key_port_id UNIQUE (eqp_key, port_id),
    CONSTRAINT ck_tc_eqp_port_status_port_type CHECK (port_type IS NULL OR port_type IN ('LOAD_PORT','UNLOAD_PORT','INTERNAL_BUFFER','OTHER')),
    CONSTRAINT ck_tc_eqp_port_status_port_state CHECK (port_state IS NULL OR port_state IN ('EMPTY','LOADED','READY_TO_LOAD','DOWN','IN_SERVICE','UNKNOWN')),
    CONSTRAINT ck_tc_eqp_port_status_carrier_type CHECK (carrier_type IS NULL OR carrier_type IN ('FOUP','CASSETTE','WAFER_BOX','TRAY','OTHER')),
    CONSTRAINT ck_tc_eqp_port_status_carrier_state CHECK (carrier_state IS NULL OR carrier_state IN ('CLAMPED','UNCLAMPED','OPENED','CLOSED','UNKNOWN'))
);

CREATE INDEX ix_tc_eqp_port_status_eqp_key  ON public.tc_eqp_port_status (eqp_key);
CREATE INDEX ix_tc_eqp_port_status_port_id ON public.tc_eqp_port_status (port_id);
CREATE INDEX ix_tc_eqp_port_status_carrier_id ON public.tc_eqp_port_status (carrier_id);

CREATE TABLE public.tc_eqp_param (
    eqp_param_key BIGINT GENERATED BY DEFAULT AS IDENTITY,
    eqp_key       BIGINT NOT NULL,
    param_name    VARCHAR(100) NOT NULL,
    param_version VARCHAR(100) NOT NULL,
    param_value   TEXT NULL,
    updated_at    TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_tc_eqp_param PRIMARY KEY (eqp_param_key),
    CONSTRAINT fk_tc_eqp_param_eqp_key__tc_eqp
        FOREIGN KEY (eqp_key) REFERENCES public.tc_eqp(eqp_key) ON DELETE CASCADE,
    CONSTRAINT uk_tc_eqp_param_eqp_key_param_name_param_version UNIQUE (eqp_key, param_name, param_version)
);

CREATE INDEX ix_tc_eqp_param_eqp_key   ON public.tc_eqp_param (eqp_key);
CREATE INDEX ix_tc_eqp_param_param_name ON public.tc_eqp_param (param_name);

CREATE TABLE public.tc_eqp_global (
    eqp_global_key BIGINT GENERATED BY DEFAULT AS IDENTITY,
    eqp_key        BIGINT NOT NULL,
    param_name     VARCHAR(100) NOT NULL,
    param_value    TEXT NULL,
    updated_at     TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_tc_eqp_global PRIMARY KEY (eqp_global_key),
    CONSTRAINT fk_tc_eqp_global_eqp_key__tc_eqp
        FOREIGN KEY (eqp_key) REFERENCES public.tc_eqp(eqp_key) ON DELETE CASCADE,
    CONSTRAINT uk_tc_eqp_global_eqp_key_param_name UNIQUE (eqp_key, param_name)
);

CREATE INDEX ix_tc_eqp_global_eqp_key ON public.tc_eqp_global (eqp_key);

-- =========================
-- 2.3 WORK
-- =========================
CREATE TABLE public.tc_work (
    work_key    BIGINT GENERATED BY DEFAULT AS IDENTITY,
    eqp_key     BIGINT NOT NULL,
    work_id     VARCHAR(64) NOT NULL,
    operator_id VARCHAR(64) NULL,
    step_seq    INT NULL,
    work_state  VARCHAR(20) NOT NULL,
    start_time  TIMESTAMPTZ(3) NULL,
    end_time    TIMESTAMPTZ(3) NULL,
    mes_message TEXT NULL,
    created_at  TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_tc_work PRIMARY KEY (work_key),
    CONSTRAINT fk_tc_work_eqp_key__tc_eqp
        FOREIGN KEY (eqp_key) REFERENCES public.tc_eqp(eqp_key),
    CONSTRAINT uk_tc_work_eqp_key_work_id UNIQUE (eqp_key, work_id),
    CONSTRAINT ck_tc_work_step_seq CHECK (step_seq IS NULL OR step_seq >= 0),
    CONSTRAINT ck_tc_work_work_state CHECK (work_state IN ('QUEUED','RUNNING','COMPLETED','ABORTED'))
);

CREATE INDEX ix_tc_work_eqp_key     ON public.tc_work (eqp_key);
CREATE INDEX ix_tc_work_work_state  ON public.tc_work (work_state);
CREATE INDEX ix_tc_work_created_at  ON public.tc_work (created_at);

CREATE TABLE public.tc_work_param (
    work_param_key BIGINT GENERATED BY DEFAULT AS IDENTITY,
    work_key       BIGINT NOT NULL,
    param_name     VARCHAR(100) NOT NULL,
    param_value    VARCHAR(2000) NULL,
    updated_at     TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_tc_work_param PRIMARY KEY (work_param_key),
    CONSTRAINT fk_tc_work_param_work_key__tc_work
        FOREIGN KEY (work_key) REFERENCES public.tc_work(work_key) ON DELETE CASCADE,
    CONSTRAINT uk_tc_work_param_work_key_param_name UNIQUE (work_key, param_name)
);

CREATE INDEX ix_tc_work_param_work_key ON public.tc_work_param (work_key);

CREATE TABLE public.tc_work_carrier (
    work_carrier_key BIGINT GENERATED BY DEFAULT AS IDENTITY,
    work_key         BIGINT NOT NULL,
    carrier_id       VARCHAR(64) NOT NULL,
    port_id          VARCHAR(20) NULL,
    slot_map         VARCHAR(255) NULL,
    total_qty        INT NULL,
    good_qty         INT NULL,
    scrap_qty        INT NULL,
    updated_at       TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_tc_work_carrier PRIMARY KEY (work_carrier_key),
    CONSTRAINT fk_tc_work_carrier_work_key__tc_work
        FOREIGN KEY (work_key) REFERENCES public.tc_work(work_key) ON DELETE CASCADE,
    CONSTRAINT uk_tc_work_carrier_work_key_carrier_id UNIQUE (work_key, carrier_id),
    CONSTRAINT ck_tc_work_carrier_total_qty CHECK (total_qty IS NULL OR total_qty >= 0),
    CONSTRAINT ck_tc_work_carrier_good_qty CHECK (good_qty IS NULL OR good_qty >= 0),
    CONSTRAINT ck_tc_work_carrier_scrap_qty CHECK (scrap_qty IS NULL OR scrap_qty >= 0)
);

CREATE INDEX ix_tc_work_carrier_work_key   ON public.tc_work_carrier (work_key);
CREATE INDEX ix_tc_work_carrier_carrier_id ON public.tc_work_carrier (carrier_id);
CREATE INDEX ix_tc_work_carrier_port_id    ON public.tc_work_carrier (port_id);

CREATE TABLE public.tc_work_carrier_slot (
    carrier_slot_key  BIGINT GENERATED BY DEFAULT AS IDENTITY,
    work_carrier_key  BIGINT NOT NULL,
    slot_no           INT NOT NULL,
    slot_state        VARCHAR(50) NOT NULL, -- CHECK 없음(정책 문자열)
    lot_id            VARCHAR(64) NULL,
    updated_at        TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_tc_work_carrier_slot PRIMARY KEY (carrier_slot_key),
    CONSTRAINT fk_tc_work_carrier_slot_work_carrier_key__tc_work_carrier
        FOREIGN KEY (work_carrier_key) REFERENCES public.tc_work_carrier(work_carrier_key) ON DELETE CASCADE,
    CONSTRAINT uk_tc_work_carrier_slot_work_carrier_key_slot_no UNIQUE (work_carrier_key, slot_no),
    CONSTRAINT ck_tc_work_carrier_slot_slot_no CHECK (slot_no >= 1)
);

CREATE INDEX ix_tc_work_carrier_slot_work_carrier_key ON public.tc_work_carrier_slot (work_carrier_key);
CREATE INDEX ix_tc_work_carrier_slot_lot_id           ON public.tc_work_carrier_slot (lot_id);

CREATE TABLE public.tc_work_lot (
    work_lot_key  BIGINT GENERATED BY DEFAULT AS IDENTITY,
    work_key      BIGINT NOT NULL,
    carrier_id    VARCHAR(64) NULL,
    lot_id        VARCHAR(64) NOT NULL,
    parent_lot_id VARCHAR(64) NULL,
    chamber_id    VARCHAR(64) NULL,
    updated_at    TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_tc_work_lot PRIMARY KEY (work_lot_key),
    CONSTRAINT fk_tc_work_lot_work_key__tc_work
        FOREIGN KEY (work_key) REFERENCES public.tc_work(work_key) ON DELETE CASCADE,
    CONSTRAINT uk_tc_work_lot_work_key_lot_id UNIQUE (work_key, lot_id)
);

CREATE INDEX ix_tc_work_lot_work_key   ON public.tc_work_lot (work_key);
CREATE INDEX ix_tc_work_lot_lot_id     ON public.tc_work_lot (lot_id);
CREATE INDEX ix_tc_work_lot_carrier_id ON public.tc_work_lot (carrier_id);

CREATE TABLE public.tc_work_controljob (
    control_job_key   BIGINT GENERATED BY DEFAULT AS IDENTITY,
    work_key          BIGINT NOT NULL,
    controljob_id     VARCHAR(64) NOT NULL,
    controljob_state  VARCHAR(20) NOT NULL,
    created_at        TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at        TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_tc_work_controljob PRIMARY KEY (control_job_key),
    CONSTRAINT fk_tc_work_controljob_work_key__tc_work
        FOREIGN KEY (work_key) REFERENCES public.tc_work(work_key) ON DELETE CASCADE,
    CONSTRAINT uk_tc_work_controljob_work_key_controljob_id UNIQUE (work_key, controljob_id),
    CONSTRAINT ck_tc_work_controljob_state CHECK (controljob_state IN ('CREATED','QUEUED','RUNNING','PAUSED','COMPLETED','ABORTED','FAILED'))
);

CREATE INDEX ix_tc_work_controljob_work_key      ON public.tc_work_controljob (work_key);
CREATE INDEX ix_tc_work_controljob_controljob_id ON public.tc_work_controljob (controljob_id);

CREATE TABLE public.tc_work_processjob (
    process_job_key   BIGINT GENERATED BY DEFAULT AS IDENTITY,
    control_job_key   BIGINT NOT NULL,
    processjob_id     VARCHAR(64) NOT NULL,
    processjob_state  VARCHAR(20) NOT NULL,
    recipe_id         VARCHAR(128) NOT NULL,
    created_at        TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at        TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_tc_work_processjob PRIMARY KEY (process_job_key),
    CONSTRAINT fk_tc_work_processjob_control_job_key__tc_work_controljob
        FOREIGN KEY (control_job_key) REFERENCES public.tc_work_controljob(control_job_key) ON DELETE CASCADE,
    CONSTRAINT uk_tc_work_processjob_control_job_key_processjob_id UNIQUE (control_job_key, processjob_id),
    CONSTRAINT ck_tc_work_processjob_state CHECK (processjob_state IN ('CREATED','QUEUED','RUNNING','PAUSED','COMPLETED','ABORTED','FAILED'))
);

CREATE INDEX ix_tc_work_processjob_control_job_key ON public.tc_work_processjob (control_job_key);
CREATE INDEX ix_tc_work_processjob_processjob_id   ON public.tc_work_processjob (processjob_id);

CREATE TABLE public.tc_work_processjob_lot_map (
    pj_lot_map_key BIGINT GENERATED BY DEFAULT AS IDENTITY,
    process_job_key BIGINT NOT NULL,
    work_lot_key    BIGINT NOT NULL,
    map_role        VARCHAR(20) NULL,
    map_order       VARCHAR(20) NULL,
    created_at      TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_tc_work_processjob_lot_map PRIMARY KEY (pj_lot_map_key),
    CONSTRAINT fk_tc_work_pj_lot_map_process_job_key__tc_work_processjob
        FOREIGN KEY (process_job_key) REFERENCES public.tc_work_processjob(process_job_key) ON DELETE CASCADE,
    CONSTRAINT fk_tc_work_pj_lot_map_work_lot_key__tc_work_lot
        FOREIGN KEY (work_lot_key) REFERENCES public.tc_work_lot(work_lot_key) ON DELETE CASCADE,
    CONSTRAINT uk_tc_work_pj_lot_map_process_job_key_work_lot_key UNIQUE (process_job_key, work_lot_key),
    CONSTRAINT ck_tc_work_pj_lot_map_map_order CHECK (map_order IS NULL OR map_order IN ('FORWARD','REVERSE'))
);

CREATE INDEX ix_tc_work_pj_lot_map_process_job_key ON public.tc_work_processjob_lot_map (process_job_key);
CREATE INDEX ix_tc_work_pj_lot_map_work_lot_key    ON public.tc_work_processjob_lot_map (work_lot_key);

-- =========================
-- 2.4 UI / AUTH
-- =========================
CREATE TABLE public.tc_user_info (
    user_pk       BIGINT GENERATED BY DEFAULT AS IDENTITY,
    company       VARCHAR(100) NOT NULL,
    department    VARCHAR(100) NOT NULL,
    user_name     VARCHAR(100) NOT NULL,
    user_id       VARCHAR(50)  NOT NULL,
    user_id_norm  VARCHAR(50)  NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    email         VARCHAR(255) NOT NULL,
    status        VARCHAR(20)  NOT NULL DEFAULT 'ACTIVE',
    created_at    TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at    TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by    VARCHAR(50) NOT NULL DEFAULT 'SYSTEM',
    updated_by    VARCHAR(50) NOT NULL DEFAULT 'SYSTEM',

    CONSTRAINT pk_tc_user_info PRIMARY KEY (user_pk),
    CONSTRAINT uk_tc_user_info_user_id_norm UNIQUE (user_id_norm),
    CONSTRAINT uk_tc_user_info_email UNIQUE (email),
    CONSTRAINT ck_tc_user_info_status CHECK (status IN ('ACTIVE','LOCKED','DISABLED','DELETED'))
);

CREATE INDEX ix_tc_user_info_company_department ON public.tc_user_info (company, department);
CREATE INDEX ix_tc_user_info_status            ON public.tc_user_info (status);
CREATE INDEX ix_tc_user_info_email             ON public.tc_user_info (email);

CREATE TABLE public.tc_ui_permission (
    perm_id        BIGINT GENERATED BY DEFAULT AS IDENTITY,
    perm_code      VARCHAR(80)  NOT NULL,
    perm_name      VARCHAR(120) NOT NULL,
    resource_type  VARCHAR(10)  NOT NULL,
    match_type     VARCHAR(10)  NOT NULL DEFAULT 'PREFIX',
    resource       VARCHAR(255) NOT NULL,
    http_method    VARCHAR(10)  NULL,
    description    VARCHAR(1000) NULL,
    is_active      BOOLEAN NOT NULL DEFAULT TRUE,
    created_at     TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at     TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by     VARCHAR(50) NOT NULL DEFAULT 'SYSTEM',
    updated_by     VARCHAR(50) NOT NULL DEFAULT 'SYSTEM',

    CONSTRAINT pk_tc_ui_permission PRIMARY KEY (perm_id),
    CONSTRAINT uk_tc_ui_permission_perm_code UNIQUE (perm_code),
    CONSTRAINT ck_tc_ui_permission_resource_type CHECK (resource_type IN ('PAGE','API')),
    CONSTRAINT ck_tc_ui_permission_match_type CHECK (match_type IN ('EXACT','PREFIX','REGEX')),
    CONSTRAINT ck_tc_ui_permission_is_active CHECK (is_active IN (TRUE, FALSE))
);

CREATE INDEX ix_tc_ui_permission_resource_type_resource ON public.tc_ui_permission (resource_type, resource);
CREATE INDEX ix_tc_ui_permission_is_active             ON public.tc_ui_permission (is_active);

CREATE TABLE public.tc_user_group (
    group_id     BIGINT GENERATED BY DEFAULT AS IDENTITY,
    group_code   VARCHAR(50)  NOT NULL,
    group_name   VARCHAR(100) NOT NULL,
    description  VARCHAR(1000) NULL,
    is_active    BOOLEAN NOT NULL DEFAULT TRUE,
    created_at   TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at   TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_tc_user_group PRIMARY KEY (group_id),
    CONSTRAINT uk_tc_user_group_group_code UNIQUE (group_code),
    CONSTRAINT ck_tc_user_group_is_active CHECK (is_active IN (TRUE, FALSE))
);

CREATE INDEX ix_tc_user_group_is_active ON public.tc_user_group (is_active);

CREATE TABLE public.tc_user_group_member (
    ugm_key     BIGINT GENERATED BY DEFAULT AS IDENTITY,
    user_pk     BIGINT NOT NULL,
    group_id    BIGINT NOT NULL,
    granted_at  TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    granted_by  VARCHAR(50) NULL,

    CONSTRAINT pk_tc_user_group_member PRIMARY KEY (ugm_key),
    CONSTRAINT fk_tc_user_group_member_user_pk__tc_user_info
        FOREIGN KEY (user_pk) REFERENCES public.tc_user_info(user_pk) ON DELETE CASCADE,
    CONSTRAINT fk_tc_user_group_member_group_id__tc_user_group
        FOREIGN KEY (group_id) REFERENCES public.tc_user_group(group_id) ON DELETE CASCADE,
    CONSTRAINT uk_tc_user_group_member_user_pk_group_id UNIQUE (user_pk, group_id)
);

CREATE INDEX ix_tc_user_group_member_group_id ON public.tc_user_group_member (group_id);
CREATE INDEX ix_tc_user_group_member_user_pk  ON public.tc_user_group_member (user_pk);

CREATE TABLE public.tc_user_group_permission (
    ugp_key    BIGINT GENERATED BY DEFAULT AS IDENTITY,
    group_id   BIGINT NOT NULL,
    perm_id    BIGINT NOT NULL,
    granted_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    granted_by VARCHAR(50) NULL,

    CONSTRAINT pk_tc_user_group_permission PRIMARY KEY (ugp_key),
    CONSTRAINT fk_tc_user_group_permission_group_id__tc_user_group
        FOREIGN KEY (group_id) REFERENCES public.tc_user_group(group_id) ON DELETE CASCADE,
    CONSTRAINT fk_tc_user_group_permission_perm_id__tc_ui_permission
        FOREIGN KEY (perm_id) REFERENCES public.tc_ui_permission(perm_id) ON DELETE CASCADE,
    CONSTRAINT uk_tc_user_group_permission_group_id_perm_id UNIQUE (group_id, perm_id)
);

CREATE INDEX ix_tc_user_group_permission_perm_id  ON public.tc_user_group_permission (perm_id);
CREATE INDEX ix_tc_user_group_permission_group_id ON public.tc_user_group_permission (group_id);

CREATE TABLE public.tc_ui_auth_session (
    token        VARCHAR(64) NOT NULL,
    user_pk      BIGINT NOT NULL,
    issued_at    TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    expires_at   TIMESTAMPTZ(3) NOT NULL,
    last_seen_at TIMESTAMPTZ(3) NULL,
    revoked      BOOLEAN NOT NULL DEFAULT FALSE,

    CONSTRAINT pk_tc_ui_auth_session PRIMARY KEY (token),
    CONSTRAINT fk_tc_ui_auth_session_user_pk__tc_user_info
        FOREIGN KEY (user_pk) REFERENCES public.tc_user_info(user_pk),
    CONSTRAINT ck_tc_ui_auth_session_revoked CHECK (revoked IN (TRUE, FALSE))
);

CREATE INDEX ix_tc_ui_auth_session_user_pk          ON public.tc_ui_auth_session (user_pk);
CREATE INDEX ix_tc_ui_auth_session_expires_at       ON public.tc_ui_auth_session (expires_at);
CREATE INDEX ix_tc_ui_auth_session_revoked_expires_at ON public.tc_ui_auth_session (revoked, expires_at);

-- =========================
-- 2.5 OUTBOX
-- =========================
CREATE TABLE public.tc_msg_send_queue (
    msg_key         BIGINT GENERATED BY DEFAULT AS IDENTITY,
    idempotency_key VARCHAR(128) NOT NULL,
    topic           VARCHAR(200) NOT NULL,
    message_key     VARCHAR(200) NULL,
    headers_json    TEXT NULL,          -- JSON 문자열(검증 없음)
    payload_json    TEXT NOT NULL,      -- JSON 문자열(검증 없음)
    status          VARCHAR(16) NOT NULL,
    retry_count     INT NOT NULL DEFAULT 0,
    next_retry_at   TIMESTAMPTZ(3) NULL,
    locked_by       VARCHAR(64) NULL,
    locked_until    TIMESTAMPTZ(3) NULL,
    created_at      TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_tc_msg_send_queue PRIMARY KEY (msg_key),
    CONSTRAINT uk_tc_msg_send_queue_topic_idempotency_key UNIQUE (topic, idempotency_key),
    CONSTRAINT ck_tc_msg_send_queue_status CHECK (status IN ('PENDING','SENDING','SENT','FAILED','DEAD')),
    CONSTRAINT ck_tc_msg_send_queue_retry_count CHECK (retry_count >= 0)
);

CREATE INDEX ix_tc_msg_send_queue_status_next_retry_at ON public.tc_msg_send_queue (status, next_retry_at);
CREATE INDEX ix_tc_msg_send_queue_locked_until         ON public.tc_msg_send_queue (locked_until);
CREATE INDEX ix_tc_msg_send_queue_topic_status         ON public.tc_msg_send_queue (topic, status);

CREATE TABLE public.tc_msg_send_log (
    send_log_key    BIGINT GENERATED BY DEFAULT AS IDENTITY,
    msg_key         BIGINT NOT NULL,
    attempt_no      INT NOT NULL,
    result          VARCHAR(16) NOT NULL,
    kafka_partition INT NULL,
    kafka_offset    BIGINT NULL,
    error_code      VARCHAR(64) NULL,
    error_message   TEXT NULL,
    sent_at         TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_tc_msg_send_log PRIMARY KEY (send_log_key),
    CONSTRAINT fk_tc_msg_send_log_msg_key__tc_msg_send_queue
        FOREIGN KEY (msg_key) REFERENCES public.tc_msg_send_queue(msg_key) ON DELETE CASCADE,
    CONSTRAINT ck_tc_msg_send_log_attempt_no CHECK (attempt_no >= 1),
    CONSTRAINT ck_tc_msg_send_log_result CHECK (result IN ('SUCCESS','FAIL'))
);

CREATE INDEX ix_tc_msg_send_log_msg_key_attempt_no ON public.tc_msg_send_log (msg_key, attempt_no);
CREATE INDEX ix_tc_msg_send_log_sent_at           ON public.tc_msg_send_log (sent_at);
