package com.nori.tc.db.jpa.common.entity;

import com.nori.tc.db.jpa.common.entity.base.AbstractUpdatedEntity;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import jakarta.persistence.UniqueConstraint;

/**
 * tc_eqp_param 테이블 매핑 엔티티.
 *
 * [DB 스키마]
 * - eqp_param_key : bigint generated by default as identity (PK)
 * - eqp_key       : bigint NOT NULL (FK -> tc_eqp.eqp_key)
 * - param_name    : varchar(100) NOT NULL
 * - param_version : varchar(100) NOT NULL
 * - param_value   : text NULL
 * - updated_at    : timestamptz NOT NULL default CURRENT_TIMESTAMP
 * - Constraints   : UNIQUE (eqp_key, param_name, param_version)
 */
@Entity
@Table(
        name = "tc_eqp_param",
        uniqueConstraints = {
                @UniqueConstraint(
                        name = "uk_tc_eqp_param_eqp_key_param_name_param_version",
                        columnNames = {"eqp_key", "param_name", "param_version"}
                )
        }
)
public class TcEqpParamEntity extends AbstractUpdatedEntity {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "eqp_param_key", nullable = false)
    private Long eqpParamKey;

    @Column(name = "eqp_key", nullable = false)
    private Long eqpKey;

    @Column(name = "param_name", length = 100, nullable = false)
    private String paramName;

    @Column(name = "param_version", length = 100, nullable = false)
    private String paramVersion;

    @Column(name = "param_value", columnDefinition = "text")
    private String paramValue;

    // =========================================================================
    // Constructors (MapStruct & JPA)
    // =========================================================================

    /**
     * 기본 생성자 (필수)
     * - JPA 프록시 생성용
     * - MapStruct 타겟 객체 생성용 (public 필수)
     */
    public TcEqpParamEntity() {
    }

    /**
     * 전체 인자 생성자
     */
    public TcEqpParamEntity(Long eqpParamKey, Long eqpKey, String paramName, String paramVersion, String paramValue) {
        this.eqpParamKey = eqpParamKey;
        this.eqpKey = eqpKey;
        this.paramName = paramName;
        this.paramVersion = paramVersion;
        this.paramValue = paramValue;
    }

    // =========================================================================
    // Static Factory
    // =========================================================================

    /**
     * 신규 엔티티 생성 팩토리
     * - Unique Key(eqp_key, param_name, param_version)를 기반으로 초기화한다.
     */
    public static TcEqpParamEntity newEntity(long eqpKey, String paramName, String paramVersion) {
        if (eqpKey <= 0) {
            throw new IllegalArgumentException("eqpKey must be > 0");
        }
        if (paramName == null || paramName.isBlank()) {
            throw new IllegalArgumentException("paramName must not be null/blank");
        }
        if (paramVersion == null || paramVersion.isBlank()) {
            throw new IllegalArgumentException("paramVersion must not be null/blank");
        }

        TcEqpParamEntity e = new TcEqpParamEntity();
        e.setEqpKey(eqpKey);
        e.setParamName(paramName);
        e.setParamVersion(paramVersion);
        return e;
    }

    // =========================================================================
    // Getters & Setters
    // =========================================================================

    public Long getEqpParamKey() {
        return eqpParamKey;
    }

    public void setEqpParamKey(Long eqpParamKey) {
        this.eqpParamKey = eqpParamKey;
    }

    public Long getEqpKey() {
        return eqpKey;
    }

    public void setEqpKey(Long eqpKey) {
        this.eqpKey = eqpKey;
    }

    public String getParamName() {
        return paramName;
    }

    public void setParamName(String paramName) {
        this.paramName = paramName;
    }

    public String getParamVersion() {
        return paramVersion;
    }

    public void setParamVersion(String paramVersion) {
        this.paramVersion = paramVersion;
    }

    public String getParamValue() {
        return paramValue;
    }

    public void setParamValue(String paramValue) {
        this.paramValue = paramValue;
    }
}
