package com.nori.tc.db.jpa.common.entity;

import com.nori.tc.db.domain.common.CarrierState;
import com.nori.tc.db.domain.common.CarrierType;
import com.nori.tc.db.domain.common.PortState;
import com.nori.tc.db.domain.common.PortType;
import com.nori.tc.db.jpa.common.entity.base.AbstractUpdatedEntity;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import jakarta.persistence.UniqueConstraint;

/**
 * tc_eqp_port_status 테이블 매핑 엔티티.
 *
 * [DB 스키마]
 * - eqp_port_status_key : bigint generated by default as identity (PK)
 * - eqp_key             : bigint NOT NULL (FK)
 * - port_id             : varchar(20) NOT NULL
 * - port_type           : varchar(20)
 * - port_state          : varchar(20)
 * - carrier_id          : varchar(64)
 * - carrier_type        : varchar(20)
 * - carrier_state       : varchar(20)
 * - updated_at          : timestamptz NOT NULL (AbstractUpdatedEntity 상속)
 * - Constraints         : UNIQUE (eqp_key, port_id)
 *
 * [설계 포인트]
 * 1. MapStruct 호환성:
 * - public 생성자를 제공하여 Mapper가 객체를 생성할 수 있게 합니다.
 *
 * 2. Identity Strategy:
 * - PK(eqp_port_status_key)는 DB 자동 생성(Identity)을 따릅니다.
 */
@Entity
@Table(
        name = "tc_eqp_port_status",
        uniqueConstraints = {
                @UniqueConstraint(name = "uk_tc_eqp_port_status_eqp_key_port_id", columnNames = {"eqp_key", "port_id"})
        }
)
public class TcEqpPortStatusEntity extends AbstractUpdatedEntity {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "eqp_port_status_key", nullable = false)
    private Long eqpPortStatusKey;

    @Column(name = "eqp_key", nullable = false)
    private Long eqpKey;

    @Column(name = "port_id", length = 20, nullable = false)
    private String portId;

    @Enumerated(EnumType.STRING)
    @Column(name = "port_type", length = 20)
    private PortType portType;

    @Enumerated(EnumType.STRING)
    @Column(name = "port_state", length = 20)
    private PortState portState;

    @Column(name = "carrier_id", length = 64)
    private String carrierId;

    @Enumerated(EnumType.STRING)
    @Column(name = "carrier_type", length = 20)
    private CarrierType carrierType;

    @Enumerated(EnumType.STRING)
    @Column(name = "carrier_state", length = 20)
    private CarrierState carrierState;

    // =========================================================================
    // Constructors (MapStruct & JPA)
    // =========================================================================

    /**
     * 기본 생성자 (필수)
     * - JPA 프록시 생성용
     * - MapStruct 타겟 객체 생성용 (public 필수)
     */
    public TcEqpPortStatusEntity() {
    }

    /**
     * 전체 인자 생성자
     * - MapStruct가 Domain -> Entity 변환 시 모든 필드를 한 번에 주입할 때 사용
     */
    public TcEqpPortStatusEntity(Long eqpPortStatusKey, Long eqpKey, String portId,
                                 PortType portType, PortState portState,
                                 String carrierId, CarrierType carrierType, CarrierState carrierState) {
        this.eqpPortStatusKey = eqpPortStatusKey;
        this.eqpKey = eqpKey;
        this.portId = portId;
        this.portType = portType;
        this.portState = portState;
        this.carrierId = carrierId;
        this.carrierType = carrierType;
        this.carrierState = carrierState;
    }

    // =========================================================================
    // Static Factory
    // =========================================================================

    public static TcEqpPortStatusEntity newEntity(long eqpKey, String portId) {
        if (eqpKey <= 0) {
            throw new IllegalArgumentException("eqpKey must be > 0");
        }
        if (portId == null || portId.isBlank()) {
            throw new IllegalArgumentException("portId must not be null/blank");
        }
        TcEqpPortStatusEntity entity = new TcEqpPortStatusEntity();
        entity.setEqpKey(eqpKey);
        entity.setPortId(portId);
        return entity;
    }

    // =========================================================================
    // Getters & Setters
    // =========================================================================

    public Long getEqpPortStatusKey() {
        return eqpPortStatusKey;
    }

    public void setEqpPortStatusKey(Long eqpPortStatusKey) {
        this.eqpPortStatusKey = eqpPortStatusKey;
    }

    public Long getEqpKey() {
        return eqpKey;
    }

    public void setEqpKey(Long eqpKey) {
        this.eqpKey = eqpKey;
    }

    public String getPortId() {
        return portId;
    }

    public void setPortId(String portId) {
        this.portId = portId;
    }

    public PortType getPortType() {
        return portType;
    }

    public void setPortType(PortType portType) {
        this.portType = portType;
    }

    public PortState getPortState() {
        return portState;
    }

    public void setPortState(PortState portState) {
        this.portState = portState;
    }

    public String getCarrierId() {
        return carrierId;
    }

    public void setCarrierId(String carrierId) {
        this.carrierId = carrierId;
    }

    public CarrierType getCarrierType() {
        return carrierType;
    }

    public void setCarrierType(CarrierType carrierType) {
        this.carrierType = carrierType;
    }

    public CarrierState getCarrierState() {
        return carrierState;
    }

    public void setCarrierState(CarrierState carrierState) {
        this.carrierState = carrierState;
    }
}
