package com.nori.tc.db.jpa.common.entity;

import com.nori.tc.db.jpa.common.entity.base.AbstractUpdatedEntity;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import jakarta.persistence.UniqueConstraint;

/**
 * tc_eqp_global 테이블 매핑 엔티티.
 *
 * [DB 스키마]
 * - eqp_global_key : bigint generated by default as identity (PK)
 * - eqp_key        : bigint NOT NULL (FK -> tc_eqp.eqp_key, ON DELETE CASCADE)
 * - param_name     : varchar(100) NOT NULL
 * - param_value    : text NULL
 * - updated_at     : timestamptz NOT NULL (DEFAULT CURRENT_TIMESTAMP)
 *
 * [제약]
 * - UNIQUE (eqp_key, param_name)
 *
 * [설계 포인트]
 * 1. MapStruct 호환성:
 * - public 기본 생성자 + 전체 인자 생성자를 제공한다.
 *
 * 2. UpdatedAt 관리:
 * - AbstractUpdatedEntity를 상속하여 insert/update 시점을 자동 반영한다.
 */
@Entity
@Table(
        name = "tc_eqp_global",
        uniqueConstraints = {
                @UniqueConstraint(name = "uk_tc_eqp_global_eqp_key_param_name", columnNames = {"eqp_key", "param_name"})
        }
)
public class TcEqpGlobalEntity extends AbstractUpdatedEntity {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "eqp_global_key", nullable = false)
    private Long eqpGlobalKey;

    @Column(name = "eqp_key", nullable = false)
    private Long eqpKey;

    @Column(name = "param_name", length = 100, nullable = false)
    private String paramName;

    @Column(name = "param_value")
    private String paramValue;

    // =========================================================================
    // Constructors (MapStruct & JPA)
    // =========================================================================

    /**
     * 기본 생성자 (필수)
     */
    public TcEqpGlobalEntity() {
    }

    /**
     * 전체 인자 생성자
     */
    public TcEqpGlobalEntity(Long eqpGlobalKey, Long eqpKey, String paramName, String paramValue) {
        this.eqpGlobalKey = eqpGlobalKey;
        this.eqpKey = eqpKey;
        this.paramName = paramName;
        this.paramValue = paramValue;
    }

    // =========================================================================
    // Static Factory
    // =========================================================================

    /**
     * 신규 엔티티 생성 팩토리
     * - 유니크 키(eqpKey, paramName)가 반드시 필요하므로 null/blank 검증을 수행한다.
     */
    public static TcEqpGlobalEntity newEntity(long eqpKey, String paramName) {
        if (eqpKey <= 0) {
            throw new IllegalArgumentException("eqpKey must be positive");
        }
        if (paramName == null || paramName.isBlank()) {
            throw new IllegalArgumentException("paramName must not be null/blank");
        }
        TcEqpGlobalEntity e = new TcEqpGlobalEntity();
        e.setEqpKey(eqpKey);
        e.setParamName(paramName);
        return e;
    }

    // =========================================================================
    // Getters & Setters
    // =========================================================================

    public Long getEqpGlobalKey() {
        return eqpGlobalKey;
    }

    public void setEqpGlobalKey(Long eqpGlobalKey) {
        this.eqpGlobalKey = eqpGlobalKey;
    }

    public Long getEqpKey() {
        return eqpKey;
    }

    public void setEqpKey(Long eqpKey) {
        this.eqpKey = eqpKey;
    }

    public String getParamName() {
        return paramName;
    }

    public void setParamName(String paramName) {
        this.paramName = paramName;
    }

    public String getParamValue() {
        return paramValue;
    }

    public void setParamValue(String paramValue) {
        this.paramValue = paramValue;
    }
}
