package com.nori.tc.db.jpa.common.entity.outbox;

import java.time.OffsetDateTime;

import com.nori.tc.db.domain.common.outbox.MsgSendResult;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.PrePersist;
import jakarta.persistence.Table;

/**
 * tc_msg_send_log 테이블 매핑 엔티티.
 *
 * [DB 스키마]
 * - send_log_key    : bigint generated by default as identity (PK)
 * - msg_key         : bigint NOT NULL (FK -> tc_msg_send_queue.msg_key, ON DELETE CASCADE)
 * - attempt_no      : int NOT NULL (>= 1)
 * - result          : varchar(16) NOT NULL (SUCCESS/FAIL)
 * - kafka_partition : int NULL
 * - kafka_offset    : bigint NULL
 * - error_code      : varchar(64) NULL
 * - error_message   : text NULL
 * - sent_at         : timestamptz NOT NULL default CURRENT_TIMESTAMP
 *
 * [설계 포인트]
 * 1. MapStruct 호환성:
 * - public 생성자를 제공하여 Mapper가 객체를 생성할 수 있게 합니다.
 *
 * 2. 기본값 방어:
 * - sentAt이 null이면 현재 시각으로 보정합니다.
 */
@Entity
@Table(name = "tc_msg_send_log")
public class TcMsgSendLogEntity {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "send_log_key", nullable = false)
    private Long sendLogKey;

    @Column(name = "msg_key", nullable = false)
    private Long msgKey;

    @Column(name = "attempt_no", nullable = false)
    private Integer attemptNo;

    @Enumerated(EnumType.STRING)
    @Column(name = "result", length = 16, nullable = false)
    private MsgSendResult result;

    @Column(name = "kafka_partition")
    private Integer kafkaPartition;

    @Column(name = "kafka_offset")
    private Long kafkaOffset;

    @Column(name = "error_code", length = 64)
    private String errorCode;

    @Column(name = "error_message", columnDefinition = "text")
    private String errorMessage;

    @Column(name = "sent_at", nullable = false)
    private OffsetDateTime sentAt;

    // =========================================================================
    // Constructors (MapStruct & JPA)
    // =========================================================================

    /**
     * 기본 생성자 (필수)
     */
    public TcMsgSendLogEntity() {
    }

    /**
     * 전체 인자 생성자
     */
    public TcMsgSendLogEntity(
            Long sendLogKey,
            Long msgKey,
            Integer attemptNo,
            MsgSendResult result,
            Integer kafkaPartition,
            Long kafkaOffset,
            String errorCode,
            String errorMessage,
            OffsetDateTime sentAt
    ) {
        this.sendLogKey = sendLogKey;
        this.msgKey = msgKey;
        this.attemptNo = attemptNo;
        this.result = result;
        this.kafkaPartition = kafkaPartition;
        this.kafkaOffset = kafkaOffset;
        this.errorCode = errorCode;
        this.errorMessage = errorMessage;
        this.sentAt = sentAt;
    }

    // =========================================================================
    // Static Factory
    // =========================================================================

    
    /**
     * DB JPA 계층 규약에 맞게 데이터를 변환/구성합니다.
     *
     * <p>엔티티 생명주기 콜백과 컬럼 매핑 규칙을 기준으로 처리합니다.</p>
     * @param msgKey 대상 키 값
     * @param attemptNo DB JPA 계층 처리에 사용하는 입력 값
     * @return DB JPA 계층 처리 결과
     */
    public static TcMsgSendLogEntity newEntity(long msgKey, int attemptNo) {
        if (msgKey <= 0) {
            throw new IllegalArgumentException("msgKey must be positive");
        }
        if (attemptNo < 1) {
            throw new IllegalArgumentException("attemptNo must be >= 1");
        }
        TcMsgSendLogEntity e = new TcMsgSendLogEntity();
        e.setMsgKey(msgKey);
        e.setAttemptNo(attemptNo);
        return e;
    }

    // =========================================================================
    // Lifecycle
    // =========================================================================

    /**
     * DB Insert 전 기본값 방어
     * - sentAt이 null이면 현재 시각으로 보정합니다.
     */
    @PrePersist
    private void applyDefaults() {
        if (this.sentAt == null) {
            this.sentAt = OffsetDateTime.now();
        }
    }

    // =========================================================================
    // Getters & Setters
    // =========================================================================

    
    /**
     * DB JPA 계층의 현재 값을 조회합니다.
     *
     * <p>엔티티 생명주기 콜백과 컬럼 매핑 규칙을 기준으로 처리합니다.</p>
     * @return DB JPA 계층 처리 결과
     */
    public Long getSendLogKey() {
        return sendLogKey;
    }

    
    /**
     * DB JPA 계층 설정 값을 반영합니다.
     *
     * <p>엔티티 생명주기 콜백과 컬럼 매핑 규칙을 기준으로 처리합니다.</p>
     * @param sendLogKey 대상 키 값
     */
    public void setSendLogKey(Long sendLogKey) {
        this.sendLogKey = sendLogKey;
    }

    
    /**
     * DB JPA 계층의 현재 값을 조회합니다.
     *
     * <p>엔티티 생명주기 콜백과 컬럼 매핑 규칙을 기준으로 처리합니다.</p>
     * @return DB JPA 계층 처리 결과
     */
    public Long getMsgKey() {
        return msgKey;
    }

    
    /**
     * DB JPA 계층 설정 값을 반영합니다.
     *
     * <p>엔티티 생명주기 콜백과 컬럼 매핑 규칙을 기준으로 처리합니다.</p>
     * @param msgKey 대상 키 값
     */
    public void setMsgKey(Long msgKey) {
        this.msgKey = msgKey;
    }

    
    /**
     * DB JPA 계층의 현재 값을 조회합니다.
     *
     * <p>엔티티 생명주기 콜백과 컬럼 매핑 규칙을 기준으로 처리합니다.</p>
     * @return DB JPA 계층 처리 결과
     */
    public Integer getAttemptNo() {
        return attemptNo;
    }

    
    /**
     * DB JPA 계층 설정 값을 반영합니다.
     *
     * <p>엔티티 생명주기 콜백과 컬럼 매핑 규칙을 기준으로 처리합니다.</p>
     * @param attemptNo DB JPA 계층 처리에 사용하는 입력 값
     */
    public void setAttemptNo(Integer attemptNo) {
        this.attemptNo = attemptNo;
    }

    
    /**
     * DB JPA 계층의 현재 값을 조회합니다.
     *
     * <p>엔티티 생명주기 콜백과 컬럼 매핑 규칙을 기준으로 처리합니다.</p>
     * @return DB JPA 계층 처리 결과
     */
    public MsgSendResult getResult() {
        return result;
    }

    
    /**
     * DB JPA 계층 설정 값을 반영합니다.
     *
     * <p>엔티티 생명주기 콜백과 컬럼 매핑 규칙을 기준으로 처리합니다.</p>
     * @param result DB JPA 계층 처리에 사용하는 입력 값
     */
    public void setResult(MsgSendResult result) {
        this.result = result;
    }

    
    /**
     * DB JPA 계층의 현재 값을 조회합니다.
     *
     * <p>엔티티 생명주기 콜백과 컬럼 매핑 규칙을 기준으로 처리합니다.</p>
     * @return DB JPA 계층 처리 결과
     */
    public Integer getKafkaPartition() {
        return kafkaPartition;
    }

    
    /**
     * DB JPA 계층 설정 값을 반영합니다.
     *
     * <p>엔티티 생명주기 콜백과 컬럼 매핑 규칙을 기준으로 처리합니다.</p>
     * @param kafkaPartition DB JPA 계층 처리에 사용하는 입력 값
     */
    public void setKafkaPartition(Integer kafkaPartition) {
        this.kafkaPartition = kafkaPartition;
    }

    
    /**
     * DB JPA 계층의 현재 값을 조회합니다.
     *
     * <p>엔티티 생명주기 콜백과 컬럼 매핑 규칙을 기준으로 처리합니다.</p>
     * @return DB JPA 계층 처리 결과
     */
    public Long getKafkaOffset() {
        return kafkaOffset;
    }

    
    /**
     * DB JPA 계층 설정 값을 반영합니다.
     *
     * <p>엔티티 생명주기 콜백과 컬럼 매핑 규칙을 기준으로 처리합니다.</p>
     * @param kafkaOffset 페이징/조회 범위 조건
     */
    public void setKafkaOffset(Long kafkaOffset) {
        this.kafkaOffset = kafkaOffset;
    }

    
    /**
     * DB JPA 계층의 현재 값을 조회합니다.
     *
     * <p>엔티티 생명주기 콜백과 컬럼 매핑 규칙을 기준으로 처리합니다.</p>
     * @return DB JPA 계층 처리 결과
     */
    public String getErrorCode() {
        return errorCode;
    }

    
    /**
     * DB JPA 계층 설정 값을 반영합니다.
     *
     * <p>엔티티 생명주기 콜백과 컬럼 매핑 규칙을 기준으로 처리합니다.</p>
     * @param errorCode DB JPA 계층 처리에 사용하는 입력 값
     */
    public void setErrorCode(String errorCode) {
        this.errorCode = errorCode;
    }

    
    /**
     * DB JPA 계층의 현재 값을 조회합니다.
     *
     * <p>엔티티 생명주기 콜백과 컬럼 매핑 규칙을 기준으로 처리합니다.</p>
     * @return DB JPA 계층 처리 결과
     */
    public String getErrorMessage() {
        return errorMessage;
    }

    
    /**
     * DB JPA 계층 설정 값을 반영합니다.
     *
     * <p>엔티티 생명주기 콜백과 컬럼 매핑 규칙을 기준으로 처리합니다.</p>
     * @param errorMessage 처리할 원본 데이터
     */
    public void setErrorMessage(String errorMessage) {
        this.errorMessage = errorMessage;
    }

    
    /**
     * DB JPA 계층의 현재 값을 조회합니다.
     *
     * <p>엔티티 생명주기 콜백과 컬럼 매핑 규칙을 기준으로 처리합니다.</p>
     * @return DB JPA 계층 처리 결과
     */
    public OffsetDateTime getSentAt() {
        return sentAt;
    }

    
    /**
     * DB JPA 계층 설정 값을 반영합니다.
     *
     * <p>엔티티 생명주기 콜백과 컬럼 매핑 규칙을 기준으로 처리합니다.</p>
     * @param sentAt DB JPA 계층 처리에 사용하는 입력 값
     */
    public void setSentAt(OffsetDateTime sentAt) {
        this.sentAt = sentAt;
    }
}
