package com.nori.tc.db.jpa.common.entity.eqp;

import java.time.OffsetDateTime;

import com.nori.tc.db.domain.common.eqp.EqpStateType;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.PrePersist;
import jakarta.persistence.Table;

/**
 * tc_eqp_state_hist 테이블 매핑 엔티티.
 *
 * [DB 스키마]
 * - state_hist_key : bigint generated by default as identity (PK)
 * - eqp_key        : bigint NOT NULL (FK -> tc_eqp.eqp_key, ON DELETE CASCADE)
 * - state_type     : varchar(10) NOT NULL (OPER/CONN)
 * - from_state     : varchar(50) NULL
 * - to_state       : varchar(50) NULL
 * - changed_at     : timestamptz NOT NULL default CURRENT_TIMESTAMP
 * - reason_code    : varchar(50) NULL
 * - reason_detail  : text NULL
 *
 * [설계 포인트]
 * 1. MapStruct 호환성:
 * - public 생성자를 제공하여 Mapper가 객체를 생성할 수 있게 합니다.
 *
 * 2. 기본값 방어:
 * - changedAt이 null이면 현재 시각으로 보정합니다.
 */
@Entity
@Table(name = "tc_eqp_state_hist")
public class TcEqpStateHistEntity {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "state_hist_key", nullable = false)
    private Long stateHistKey;

    @Column(name = "eqp_key", nullable = false)
    private Long eqpKey;

    @Enumerated(EnumType.STRING)
    @Column(name = "state_type", length = 10, nullable = false)
    private EqpStateType stateType;

    @Column(name = "from_state", length = 50)
    private String fromState;

    @Column(name = "to_state", length = 50)
    private String toState;

    @Column(name = "changed_at", nullable = false)
    private OffsetDateTime changedAt;

    @Column(name = "reason_code", length = 50)
    private String reasonCode;

    @Column(name = "reason_detail", columnDefinition = "text")
    private String reasonDetail;

    // =========================================================================
    // Constructors (MapStruct & JPA)
    // =========================================================================

    /**
     * 기본 생성자 (필수)
     */
    public TcEqpStateHistEntity() {
    }

    /**
     * 전체 인자 생성자
     */
    public TcEqpStateHistEntity(
            Long stateHistKey,
            Long eqpKey,
            EqpStateType stateType,
            String fromState,
            String toState,
            OffsetDateTime changedAt,
            String reasonCode,
            String reasonDetail
    ) {
        this.stateHistKey = stateHistKey;
        this.eqpKey = eqpKey;
        this.stateType = stateType;
        this.fromState = fromState;
        this.toState = toState;
        this.changedAt = changedAt;
        this.reasonCode = reasonCode;
        this.reasonDetail = reasonDetail;
    }

    // =========================================================================
    // Static Factory
    // =========================================================================

    
    /**
     * DB JPA 계층 규약에 맞게 데이터를 변환/구성합니다.
     *
     * <p>엔티티 생명주기 콜백과 컬럼 매핑 규칙을 기준으로 처리합니다.</p>
     * @param eqpKey 설비 식별 정보
     * @param stateType DB JPA 계층 처리에 사용하는 입력 값
     * @return DB JPA 계층 처리 결과
     */
    public static TcEqpStateHistEntity newEntity(Long eqpKey, EqpStateType stateType) {
        if (eqpKey == null || eqpKey <= 0) {
            throw new IllegalArgumentException("eqpKey must be positive");
        }
        if (stateType == null) {
            throw new IllegalArgumentException("stateType must not be null");
        }
        TcEqpStateHistEntity e = new TcEqpStateHistEntity();
        e.setEqpKey(eqpKey);
        e.setStateType(stateType);
        return e;
    }

    // =========================================================================
    // Lifecycle
    // =========================================================================

    /**
     * DB Insert 전 기본값 방어
     * - changedAt이 null이면 현재 시각으로 보정합니다.
     */
    @PrePersist
    private void applyDefaults() {
        if (this.changedAt == null) {
            this.changedAt = OffsetDateTime.now();
        }
    }

    // =========================================================================
    // Getters & Setters
    // =========================================================================

    
    /**
     * DB JPA 계층의 현재 값을 조회합니다.
     *
     * <p>엔티티 생명주기 콜백과 컬럼 매핑 규칙을 기준으로 처리합니다.</p>
     * @return DB JPA 계층 처리 결과
     */
    public Long getStateHistKey() {
        return stateHistKey;
    }

    
    /**
     * DB JPA 계층 설정 값을 반영합니다.
     *
     * <p>엔티티 생명주기 콜백과 컬럼 매핑 규칙을 기준으로 처리합니다.</p>
     * @param stateHistKey 대상 키 값
     */
    public void setStateHistKey(Long stateHistKey) {
        this.stateHistKey = stateHistKey;
    }

    
    /**
     * DB JPA 계층의 현재 값을 조회합니다.
     *
     * <p>엔티티 생명주기 콜백과 컬럼 매핑 규칙을 기준으로 처리합니다.</p>
     * @return DB JPA 계층 처리 결과
     */
    public Long getEqpKey() {
        return eqpKey;
    }

    
    /**
     * DB JPA 계층 설정 값을 반영합니다.
     *
     * <p>엔티티 생명주기 콜백과 컬럼 매핑 규칙을 기준으로 처리합니다.</p>
     * @param eqpKey 설비 식별 정보
     */
    public void setEqpKey(Long eqpKey) {
        this.eqpKey = eqpKey;
    }

    
    /**
     * DB JPA 계층의 현재 값을 조회합니다.
     *
     * <p>엔티티 생명주기 콜백과 컬럼 매핑 규칙을 기준으로 처리합니다.</p>
     * @return DB JPA 계층 처리 결과
     */
    public EqpStateType getStateType() {
        return stateType;
    }

    
    /**
     * DB JPA 계층 설정 값을 반영합니다.
     *
     * <p>엔티티 생명주기 콜백과 컬럼 매핑 규칙을 기준으로 처리합니다.</p>
     * @param stateType DB JPA 계층 처리에 사용하는 입력 값
     */
    public void setStateType(EqpStateType stateType) {
        this.stateType = stateType;
    }

    
    /**
     * DB JPA 계층의 현재 값을 조회합니다.
     *
     * <p>엔티티 생명주기 콜백과 컬럼 매핑 규칙을 기준으로 처리합니다.</p>
     * @return DB JPA 계층 처리 결과
     */
    public String getFromState() {
        return fromState;
    }

    
    /**
     * DB JPA 계층 설정 값을 반영합니다.
     *
     * <p>엔티티 생명주기 콜백과 컬럼 매핑 규칙을 기준으로 처리합니다.</p>
     * @param fromState DB JPA 계층 처리에 사용하는 입력 값
     */
    public void setFromState(String fromState) {
        this.fromState = fromState;
    }

    
    /**
     * DB JPA 계층의 현재 값을 조회합니다.
     *
     * <p>엔티티 생명주기 콜백과 컬럼 매핑 규칙을 기준으로 처리합니다.</p>
     * @return DB JPA 계층 처리 결과
     */
    public String getToState() {
        return toState;
    }

    
    /**
     * DB JPA 계층 설정 값을 반영합니다.
     *
     * <p>엔티티 생명주기 콜백과 컬럼 매핑 규칙을 기준으로 처리합니다.</p>
     * @param toState DB JPA 계층 처리에 사용하는 입력 값
     */
    public void setToState(String toState) {
        this.toState = toState;
    }

    
    /**
     * DB JPA 계층의 현재 값을 조회합니다.
     *
     * <p>엔티티 생명주기 콜백과 컬럼 매핑 규칙을 기준으로 처리합니다.</p>
     * @return DB JPA 계층 처리 결과
     */
    public OffsetDateTime getChangedAt() {
        return changedAt;
    }

    
    /**
     * DB JPA 계층 설정 값을 반영합니다.
     *
     * <p>엔티티 생명주기 콜백과 컬럼 매핑 규칙을 기준으로 처리합니다.</p>
     * @param changedAt DB JPA 계층 처리에 사용하는 입력 값
     */
    public void setChangedAt(OffsetDateTime changedAt) {
        this.changedAt = changedAt;
    }

    
    /**
     * DB JPA 계층의 현재 값을 조회합니다.
     *
     * <p>엔티티 생명주기 콜백과 컬럼 매핑 규칙을 기준으로 처리합니다.</p>
     * @return DB JPA 계층 처리 결과
     */
    public String getReasonCode() {
        return reasonCode;
    }

    
    /**
     * DB JPA 계층 설정 값을 반영합니다.
     *
     * <p>엔티티 생명주기 콜백과 컬럼 매핑 규칙을 기준으로 처리합니다.</p>
     * @param reasonCode DB JPA 계층 처리에 사용하는 입력 값
     */
    public void setReasonCode(String reasonCode) {
        this.reasonCode = reasonCode;
    }

    
    /**
     * DB JPA 계층의 현재 값을 조회합니다.
     *
     * <p>엔티티 생명주기 콜백과 컬럼 매핑 규칙을 기준으로 처리합니다.</p>
     * @return DB JPA 계층 처리 결과
     */
    public String getReasonDetail() {
        return reasonDetail;
    }

    
    /**
     * DB JPA 계층 설정 값을 반영합니다.
     *
     * <p>엔티티 생명주기 콜백과 컬럼 매핑 규칙을 기준으로 처리합니다.</p>
     * @param reasonDetail DB JPA 계층 처리에 사용하는 입력 값
     */
    public void setReasonDetail(String reasonDetail) {
        this.reasonDetail = reasonDetail;
    }
}
