package com.nori.tc.db.jpa.common.entity.eqp;

import com.nori.tc.db.jpa.common.entity.base.AbstractUpdatedEntity;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.PrePersist;
import jakarta.persistence.Table;
import jakarta.persistence.UniqueConstraint;

/**
 * tc_eqp_param 테이블 매핑 엔티티.
 *
 * [DB 스키마]
 * - eqp_param_key : bigint generated by default as identity (PK)
 * - eqp_key       : bigint NOT NULL (FK -> tc_eqp.eqp_key)
 * - param_name    : varchar(100) NOT NULL
 * - param_version : varchar(100) NOT NULL
 * - param_value   : text NULL
 * - description   : varchar(2000) NULL
 * - created_by    : varchar(50) NOT NULL default 'SYSTEM'
 * - updated_at    : timestamptz NOT NULL default CURRENT_TIMESTAMP
 * - Constraints   : UNIQUE (eqp_key, param_name, param_version)
 */
@Entity
@Table(
        name = "tc_eqp_param",
        uniqueConstraints = {
                @UniqueConstraint(
                        name = "uk_tc_eqp_param_eqp_key_param_name_param_version",
                        columnNames = {"eqp_key", "param_name", "param_version"}
                )
        }
)
public class TcEqpParamEntity extends AbstractUpdatedEntity {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "eqp_param_key", nullable = false)
    private Long eqpParamKey;

    @Column(name = "eqp_key", nullable = false)
    private Long eqpKey;

    @Column(name = "param_name", length = 100, nullable = false)
    private String paramName;

    @Column(name = "param_version", length = 100, nullable = false)
    private String paramVersion;

    @Column(name = "param_value", columnDefinition = "text")
    private String paramValue;

    @Column(name = "description", length = 2000)
    private String description;

    @Column(name = "created_by", length = 50, nullable = false)
    private String createdBy;

    // =========================================================================
    // Constructors (MapStruct & JPA)
    // =========================================================================

    /**
     * 기본 생성자 (필수)
     * - JPA 프록시 생성용
     * - MapStruct 타겟 객체 생성용 (public 필수)
     */
    public TcEqpParamEntity() {
    }

    /**
     * 전체 인자 생성자
     */
    public TcEqpParamEntity(
            Long eqpParamKey,
            Long eqpKey,
            String paramName,
            String paramVersion,
            String paramValue,
            String description,
            String createdBy
    ) {
        this.eqpParamKey = eqpParamKey;
        this.eqpKey = eqpKey;
        this.paramName = paramName;
        this.paramVersion = paramVersion;
        this.paramValue = paramValue;
        this.description = description;
        this.createdBy = createdBy;
    }

    // =========================================================================
    // Static Factory
    // =========================================================================

    /**
     * 신규 엔티티 생성 팩토리
     * - Unique Key(eqp_key, param_name, param_version)를 기반으로 초기화한다.
     */
    public static TcEqpParamEntity newEntity(long eqpKey, String paramName, String paramVersion) {
        if (eqpKey <= 0) {
            throw new IllegalArgumentException("eqpKey must be > 0");
        }
        if (paramName == null || paramName.isBlank()) {
            throw new IllegalArgumentException("paramName must not be null/blank");
        }
        if (paramVersion == null || paramVersion.isBlank()) {
            throw new IllegalArgumentException("paramVersion must not be null/blank");
        }

        TcEqpParamEntity e = new TcEqpParamEntity();
        e.setEqpKey(eqpKey);
        e.setParamName(paramName);
        e.setParamVersion(paramVersion);
        return e;
    }

    /**
     * INSERT 직전에 생성자 기본값을 보정합니다.
     */
    @PrePersist
    private void applyCreatedByDefault() {
        if (this.createdBy == null || this.createdBy.isBlank()) {
            this.createdBy = "SYSTEM";
        }
    }

    // =========================================================================
    // Getters & Setters
    // =========================================================================

    
    /**
     * DB JPA 계층의 현재 값을 조회합니다.
     *
     * <p>엔티티 생명주기 콜백과 컬럼 매핑 규칙을 기준으로 처리합니다.</p>
     * @return DB JPA 계층 처리 결과
     */
    public Long getEqpParamKey() {
        return eqpParamKey;
    }

    
    /**
     * DB JPA 계층 설정 값을 반영합니다.
     *
     * <p>엔티티 생명주기 콜백과 컬럼 매핑 규칙을 기준으로 처리합니다.</p>
     * @param eqpParamKey 대상 키 값
     */
    public void setEqpParamKey(Long eqpParamKey) {
        this.eqpParamKey = eqpParamKey;
    }

    
    /**
     * DB JPA 계층의 현재 값을 조회합니다.
     *
     * <p>엔티티 생명주기 콜백과 컬럼 매핑 규칙을 기준으로 처리합니다.</p>
     * @return DB JPA 계층 처리 결과
     */
    public Long getEqpKey() {
        return eqpKey;
    }

    
    /**
     * DB JPA 계층 설정 값을 반영합니다.
     *
     * <p>엔티티 생명주기 콜백과 컬럼 매핑 규칙을 기준으로 처리합니다.</p>
     * @param eqpKey 설비 식별 정보
     */
    public void setEqpKey(Long eqpKey) {
        this.eqpKey = eqpKey;
    }

    
    /**
     * DB JPA 계층의 현재 값을 조회합니다.
     *
     * <p>엔티티 생명주기 콜백과 컬럼 매핑 규칙을 기준으로 처리합니다.</p>
     * @return DB JPA 계층 처리 결과
     */
    public String getParamName() {
        return paramName;
    }

    
    /**
     * DB JPA 계층 설정 값을 반영합니다.
     *
     * <p>엔티티 생명주기 콜백과 컬럼 매핑 규칙을 기준으로 처리합니다.</p>
     * @param paramName DB JPA 계층 처리에 사용하는 입력 값
     */
    public void setParamName(String paramName) {
        this.paramName = paramName;
    }

    
    /**
     * DB JPA 계층의 현재 값을 조회합니다.
     *
     * <p>엔티티 생명주기 콜백과 컬럼 매핑 규칙을 기준으로 처리합니다.</p>
     * @return DB JPA 계층 처리 결과
     */
    public String getParamVersion() {
        return paramVersion;
    }

    
    /**
     * DB JPA 계층 설정 값을 반영합니다.
     *
     * <p>엔티티 생명주기 콜백과 컬럼 매핑 규칙을 기준으로 처리합니다.</p>
     * @param paramVersion DB JPA 계층 처리에 사용하는 입력 값
     */
    public void setParamVersion(String paramVersion) {
        this.paramVersion = paramVersion;
    }

    
    /**
     * DB JPA 계층의 현재 값을 조회합니다.
     *
     * <p>엔티티 생명주기 콜백과 컬럼 매핑 규칙을 기준으로 처리합니다.</p>
     * @return DB JPA 계층 처리 결과
     */
    public String getParamValue() {
        return paramValue;
    }

    
    /**
     * DB JPA 계층 설정 값을 반영합니다.
     *
     * <p>엔티티 생명주기 콜백과 컬럼 매핑 규칙을 기준으로 처리합니다.</p>
     * @param paramValue DB JPA 계층 처리에 사용하는 입력 값
     */
    public void setParamValue(String paramValue) {
        this.paramValue = paramValue;
    }

    
    /**
     * DB JPA 계층의 현재 값을 조회합니다.
     *
     * <p>엔티티 생명주기 콜백과 컬럼 매핑 규칙을 기준으로 처리합니다.</p>
     * @return DB JPA 계층 처리 결과
     */
    public String getDescription() {
        return description;
    }

    
    /**
     * DB JPA 계층 설정 값을 반영합니다.
     *
     * <p>엔티티 생명주기 콜백과 컬럼 매핑 규칙을 기준으로 처리합니다.</p>
     * @param description DB JPA 계층 처리에 사용하는 입력 값
     */
    public void setDescription(String description) {
        this.description = description;
    }

    
    /**
     * DB JPA 계층의 현재 값을 조회합니다.
     *
     * <p>엔티티 생명주기 콜백과 컬럼 매핑 규칙을 기준으로 처리합니다.</p>
     * @return DB JPA 계층 처리 결과
     */
    public String getCreatedBy() {
        return createdBy;
    }

    
    /**
     * DB JPA 계층 설정 값을 반영합니다.
     *
     * <p>엔티티 생명주기 콜백과 컬럼 매핑 규칙을 기준으로 처리합니다.</p>
     * @param createdBy 생성 사용자 식별자
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }
}
