package com.nori.tc.db.jpa.common.entity.model;

import com.nori.tc.db.jpa.common.entity.base.AbstractUpdatedEntity;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import jakarta.persistence.UniqueConstraint;

/**
 * tc_model_secs_message 테이블 매핑 엔티티.
 *
 * [DB 스키마]
 * - secs_msg_key  : bigint generated by default as identity (PK)
 * - model_version_key     : bigint NOT NULL (tc_model FK, ON DELETE CASCADE)
 * - secs_msg_name : varchar(100) NOT NULL
 * - description   : varchar(2000) NULL
 * - data_index    : varchar(200) NULL
 * - updated_at    : timestamptz NOT NULL
 * - Constraints   : UNIQUE (model_version_key, secs_msg_name)
 *
 * [설계 포인트]
 * 1. MapStruct 호환성:
 * - public 생성자를 제공하여 Mapper가 객체를 생성할 수 있게 합니다.
 *
 * 2. Identity Strategy:
 * - PK(secs_msg_key)는 DB 자동 생성(Identity)을 따릅니다.
 */
@Entity
@Table(
        name = "tc_model_secs_message",
        uniqueConstraints = {
                @UniqueConstraint(
                        name = "uk_tc_model_secs_message_model_version_key_secs_msg_name",
                        columnNames = {"model_version_key", "secs_msg_name"}
                )
        }
)
public class TcModelSecsMessageEntity extends AbstractUpdatedEntity {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "secs_msg_key", nullable = false)
    private Long secsMsgKey;

    @Column(name = "model_version_key", nullable = false)
    private Long modelVersionKey;

    @Column(name = "secs_msg_name", length = 100, nullable = false)
    private String secsMsgName;

    @Column(name = "description", length = 2000)
    private String description;

    @Column(name = "data_index", length = 200)
    private String dataIndex;

    // =========================================================================
    // Constructors (MapStruct & JPA)
    // =========================================================================

    /**
     * 기본 생성자 (필수)
     */
    public TcModelSecsMessageEntity() {
    }

    /**
     * 전체 인자 생성자
     */
    public TcModelSecsMessageEntity(
            Long secsMsgKey,
            Long modelVersionKey,
            String secsMsgName,
            String description,
            String dataIndex
    ) {
        this.secsMsgKey = secsMsgKey;
        this.modelVersionKey = modelVersionKey;
        this.secsMsgName = secsMsgName;
        this.description = description;
        this.dataIndex = dataIndex;
    }

    // =========================================================================
    // Static Factory
    // =========================================================================

    
    /**
     * DB JPA 계층 규약에 맞게 데이터를 변환/구성합니다.
     *
     * <p>엔티티 생명주기 콜백과 컬럼 매핑 규칙을 기준으로 처리합니다.</p>
     * @param modelVersionKey 대상 키 값
     * @param secsMsgName DB JPA 계층 처리에 사용하는 입력 값
     * @return DB JPA 계층 처리 결과
     */
    public static TcModelSecsMessageEntity newEntity(Long modelVersionKey, String secsMsgName) {
        if (modelVersionKey == null || modelVersionKey <= 0) {
            throw new IllegalArgumentException("modelVersionKey must be positive");
        }
        if (secsMsgName == null || secsMsgName.isBlank()) {
            throw new IllegalArgumentException("secsMsgName must not be null/blank");
        }
        TcModelSecsMessageEntity e = new TcModelSecsMessageEntity();
        e.setModelVersionKey(modelVersionKey);
        e.setSecsMsgName(secsMsgName);
        return e;
    }

    // =========================================================================
    // Getters & Setters
    // =========================================================================

    
    /**
     * DB JPA 계층의 현재 값을 조회합니다.
     *
     * <p>엔티티 생명주기 콜백과 컬럼 매핑 규칙을 기준으로 처리합니다.</p>
     * @return DB JPA 계층 처리 결과
     */
    public Long getSecsMsgKey() {
        return secsMsgKey;
    }

    
    /**
     * DB JPA 계층 설정 값을 반영합니다.
     *
     * <p>엔티티 생명주기 콜백과 컬럼 매핑 규칙을 기준으로 처리합니다.</p>
     * @param secsMsgKey 대상 키 값
     */
    public void setSecsMsgKey(Long secsMsgKey) {
        this.secsMsgKey = secsMsgKey;
    }

    
    /**
     * DB JPA 계층의 현재 값을 조회합니다.
     *
     * <p>엔티티 생명주기 콜백과 컬럼 매핑 규칙을 기준으로 처리합니다.</p>
     * @return DB JPA 계층 처리 결과
     */
    public Long getModelVersionKey() {
        return modelVersionKey;
    }

    
    /**
     * DB JPA 계층 설정 값을 반영합니다.
     *
     * <p>엔티티 생명주기 콜백과 컬럼 매핑 규칙을 기준으로 처리합니다.</p>
     * @param modelVersionKey 대상 키 값
     */
    public void setModelVersionKey(Long modelVersionKey) {
        this.modelVersionKey = modelVersionKey;
    }

    
    /**
     * DB JPA 계층의 현재 값을 조회합니다.
     *
     * <p>엔티티 생명주기 콜백과 컬럼 매핑 규칙을 기준으로 처리합니다.</p>
     * @return DB JPA 계층 처리 결과
     */
    public String getSecsMsgName() {
        return secsMsgName;
    }

    
    /**
     * DB JPA 계층 설정 값을 반영합니다.
     *
     * <p>엔티티 생명주기 콜백과 컬럼 매핑 규칙을 기준으로 처리합니다.</p>
     * @param secsMsgName DB JPA 계층 처리에 사용하는 입력 값
     */
    public void setSecsMsgName(String secsMsgName) {
        this.secsMsgName = secsMsgName;
    }

    
    /**
     * DB JPA 계층의 현재 값을 조회합니다.
     *
     * <p>엔티티 생명주기 콜백과 컬럼 매핑 규칙을 기준으로 처리합니다.</p>
     * @return DB JPA 계층 처리 결과
     */
    public String getDescription() {
        return description;
    }

    
    /**
     * DB JPA 계층 설정 값을 반영합니다.
     *
     * <p>엔티티 생명주기 콜백과 컬럼 매핑 규칙을 기준으로 처리합니다.</p>
     * @param description DB JPA 계층 처리에 사용하는 입력 값
     */
    public void setDescription(String description) {
        this.description = description;
    }

    
    /**
     * DB JPA 계층의 현재 값을 조회합니다.
     *
     * <p>엔티티 생명주기 콜백과 컬럼 매핑 규칙을 기준으로 처리합니다.</p>
     * @return DB JPA 계층 처리 결과
     */
    public String getDataIndex() {
        return dataIndex;
    }

    
    /**
     * DB JPA 계층 설정 값을 반영합니다.
     *
     * <p>엔티티 생명주기 콜백과 컬럼 매핑 규칙을 기준으로 처리합니다.</p>
     * @param dataIndex 처리할 원본 데이터
     */
    public void setDataIndex(String dataIndex) {
        this.dataIndex = dataIndex;
    }
}
