package com.nori.tc.db.jpa.common.entity.model;

import com.nori.tc.db.jpa.common.entity.base.AbstractUpdatedEntity;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import jakarta.persistence.UniqueConstraint;

/**
 * tc_model_socket_message 테이블 매핑 엔티티.
 *
 * [DB 스키마]
 * - socket_msg_key  : bigint generated by default as identity (PK)
 * - model_key       : bigint NOT NULL (FK -> tc_model.model_key, ON DELETE CASCADE)
 * - socket_msg_name : varchar(100) NOT NULL
 * - description     : varchar(2000) NULL
 * - data_index      : varchar(200) NULL
 * - updated_at      : timestamptz NOT NULL (AbstractUpdatedEntity 상속)
 * - Constraints     : UNIQUE (model_key, socket_msg_name)
 *
 * [설계 포인트]
 * 1. MapStruct 호환성:
 * - public 생성자를 제공하여 Mapper가 객체를 생성할 수 있게 합니다.
 *
 * 2. Identity Strategy:
 * - PK(socket_msg_key)는 DB 자동 생성(Identity)을 따릅니다.
 */
@Entity
@Table(
        name = "tc_model_socket_message",
        uniqueConstraints = {
                @UniqueConstraint(name = "uk_tc_model_socket_message_model_key_socket_msg_name", columnNames = {"model_key", "socket_msg_name"})
        }
)
public class TcModelSocketMessageEntity extends AbstractUpdatedEntity {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "socket_msg_key", nullable = false)
    private Long socketMsgKey;

    @Column(name = "model_key", nullable = false)
    private Long modelKey;

    @Column(name = "socket_msg_name", length = 100, nullable = false)
    private String socketMsgName;

    @Column(name = "description", length = 2000)
    private String description;

    @Column(name = "data_index", length = 200)
    private String dataIndex;

    // =========================================================================
    // Constructors (MapStruct & JPA)
    // =========================================================================

    /**
     * 기본 생성자 (필수)
     * - JPA 프록시 생성용
     * - MapStruct 타겟 객체 생성용 (public 필수)
     */
    public TcModelSocketMessageEntity() {
    }

    /**
     * 전체 인자 생성자
     * - MapStruct가 Domain -> Entity 변환 시 모든 필드를 한 번에 주입할 때 사용
     */
    public TcModelSocketMessageEntity(
            Long socketMsgKey,
            Long modelKey,
            String socketMsgName,
            String description,
            String dataIndex
    ) {
        this.socketMsgKey = socketMsgKey;
        this.modelKey = modelKey;
        this.socketMsgName = socketMsgName;
        this.description = description;
        this.dataIndex = dataIndex;
    }

    // =========================================================================
    // Static Factory
    // =========================================================================

    public static TcModelSocketMessageEntity newEntity(long modelKey, String socketMsgName) {
        if (modelKey <= 0) {
            throw new IllegalArgumentException("modelKey must be > 0");
        }
        if (socketMsgName == null || socketMsgName.isBlank()) {
            throw new IllegalArgumentException("socketMsgName must not be null/blank");
        }
        TcModelSocketMessageEntity entity = new TcModelSocketMessageEntity();
        entity.setModelKey(modelKey);
        entity.setSocketMsgName(socketMsgName);
        return entity;
    }

    // =========================================================================
    // Getters & Setters
    // =========================================================================

    public Long getSocketMsgKey() {
        return socketMsgKey;
    }

    public void setSocketMsgKey(Long socketMsgKey) {
        this.socketMsgKey = socketMsgKey;
    }

    public Long getModelKey() {
        return modelKey;
    }

    public void setModelKey(Long modelKey) {
        this.modelKey = modelKey;
    }

    public String getSocketMsgName() {
        return socketMsgName;
    }

    public void setSocketMsgName(String socketMsgName) {
        this.socketMsgName = socketMsgName;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getDataIndex() {
        return dataIndex;
    }

    public void setDataIndex(String dataIndex) {
        this.dataIndex = dataIndex;
    }
}
