package com.nori.tc.db.jpa.common.entity.model;

import com.nori.tc.db.jpa.common.entity.base.AbstractUpdatedEntity;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import jakarta.persistence.UniqueConstraint;

/**
 * tc_model_secs_message 테이블 매핑 엔티티.
 *
 * [DB 스키마]
 * - secs_msg_key  : bigint generated by default as identity (PK)
 * - model_key     : bigint NOT NULL (tc_model FK, ON DELETE CASCADE)
 * - secs_msg_name : varchar(100) NOT NULL
 * - description   : varchar(2000) NULL
 * - data_index    : varchar(200) NULL
 * - updated_at    : timestamptz NOT NULL
 * - Constraints   : UNIQUE (model_key, secs_msg_name)
 *
 * [설계 포인트]
 * 1. MapStruct 호환성:
 * - public 생성자를 제공하여 Mapper가 객체를 생성할 수 있게 합니다.
 *
 * 2. Identity Strategy:
 * - PK(secs_msg_key)는 DB 자동 생성(Identity)을 따릅니다.
 */
@Entity
@Table(
        name = "tc_model_secs_message",
        uniqueConstraints = {
                @UniqueConstraint(
                        name = "uk_tc_model_secs_message_model_key_secs_msg_name",
                        columnNames = {"model_key", "secs_msg_name"}
                )
        }
)
public class TcModelSecsMessageEntity extends AbstractUpdatedEntity {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "secs_msg_key", nullable = false)
    private Long secsMsgKey;

    @Column(name = "model_key", nullable = false)
    private Long modelKey;

    @Column(name = "secs_msg_name", length = 100, nullable = false)
    private String secsMsgName;

    @Column(name = "description", length = 2000)
    private String description;

    @Column(name = "data_index", length = 200)
    private String dataIndex;

    // =========================================================================
    // Constructors (MapStruct & JPA)
    // =========================================================================

    /**
     * 기본 생성자 (필수)
     */
    public TcModelSecsMessageEntity() {
    }

    /**
     * 전체 인자 생성자
     */
    public TcModelSecsMessageEntity(
            Long secsMsgKey,
            Long modelKey,
            String secsMsgName,
            String description,
            String dataIndex
    ) {
        this.secsMsgKey = secsMsgKey;
        this.modelKey = modelKey;
        this.secsMsgName = secsMsgName;
        this.description = description;
        this.dataIndex = dataIndex;
    }

    // =========================================================================
    // Static Factory
    // =========================================================================

    public static TcModelSecsMessageEntity newEntity(Long modelKey, String secsMsgName) {
        if (modelKey == null || modelKey <= 0) {
            throw new IllegalArgumentException("modelKey must be positive");
        }
        if (secsMsgName == null || secsMsgName.isBlank()) {
            throw new IllegalArgumentException("secsMsgName must not be null/blank");
        }
        TcModelSecsMessageEntity e = new TcModelSecsMessageEntity();
        e.setModelKey(modelKey);
        e.setSecsMsgName(secsMsgName);
        return e;
    }

    // =========================================================================
    // Getters & Setters
    // =========================================================================

    public Long getSecsMsgKey() {
        return secsMsgKey;
    }

    public void setSecsMsgKey(Long secsMsgKey) {
        this.secsMsgKey = secsMsgKey;
    }

    public Long getModelKey() {
        return modelKey;
    }

    public void setModelKey(Long modelKey) {
        this.modelKey = modelKey;
    }

    public String getSecsMsgName() {
        return secsMsgName;
    }

    public void setSecsMsgName(String secsMsgName) {
        this.secsMsgName = secsMsgName;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getDataIndex() {
        return dataIndex;
    }

    public void setDataIndex(String dataIndex) {
        this.dataIndex = dataIndex;
    }
}
