package com.nori.tc.db.jpa.common.entity.model;

import com.nori.tc.db.jpa.common.entity.base.AbstractUpdatedEntity;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import jakarta.persistence.UniqueConstraint;

/**
 * tc_model_param 테이블 매핑 엔티티.
 *
 * [DB 스키마]
 * - model_param_key : bigint generated by default as identity (PK)
 * - model_version_key       : bigint NOT NULL (FK -> tc_model_version.model_version_key)
 * - param_name      : varchar(128) NOT NULL
 * - param_value     : varchar(2000) NULL
 * - description     : varchar(2000) NULL
 * - updated_at      : timestamptz NOT NULL default CURRENT_TIMESTAMP
 * - Constraints     : UNIQUE (model_version_key, param_name)
 */
@Entity
@Table(
        name = "tc_model_param",
        uniqueConstraints = {
                @UniqueConstraint(
                        name = "uk_tc_model_param_model_version_key_param_name",
                        columnNames = {"model_version_key", "param_name"}
                )
        }
)
public class TcModelParamEntity extends AbstractUpdatedEntity {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "model_param_key", nullable = false)
    private Long modelParamKey;

    @Column(name = "model_version_key", nullable = false)
    private Long modelVersionKey;

    @Column(name = "param_name", length = 128, nullable = false)
    private String paramName;

    @Column(name = "param_value", length = 2000)
    private String paramValue;

    @Column(name = "description", length = 2000)
    private String description;

    // =========================================================================
    // Constructors (MapStruct & JPA)
    // =========================================================================

    /**
     * 기본 생성자 (필수)
     * - JPA 프록시 생성용
     * - MapStruct 타겟 객체 생성용 (public 필수)
     */
    public TcModelParamEntity() {
    }

    /**
     * 전체 인자 생성자
     */
    public TcModelParamEntity(
            Long modelParamKey,
            Long modelVersionKey,
            String paramName,
            String paramValue,
            String description
    ) {
        this.modelParamKey = modelParamKey;
        this.modelVersionKey = modelVersionKey;
        this.paramName = paramName;
        this.paramValue = paramValue;
        this.description = description;
    }

    // =========================================================================
    // Static Factory
    // =========================================================================

    /**
     * 신규 엔티티 생성 팩토리
     * - Unique Key(model_version_key, param_name)를 기반으로 초기화한다.
     */
    public static TcModelParamEntity newEntity(long modelVersionKey, String paramName) {
        if (modelVersionKey <= 0) {
            throw new IllegalArgumentException("modelVersionKey must be > 0");
        }
        if (paramName == null || paramName.isBlank()) {
            throw new IllegalArgumentException("paramName must not be null/blank");
        }

        TcModelParamEntity e = new TcModelParamEntity();
        e.setModelVersionKey(modelVersionKey);
        e.setParamName(paramName);
        return e;
    }

    // =========================================================================
    // Getters & Setters
    // =========================================================================

    
    /**
     * DB JPA 계층의 현재 값을 조회합니다.
     *
     * <p>엔티티 생명주기 콜백과 컬럼 매핑 규칙을 기준으로 처리합니다.</p>
     * @return DB JPA 계층 처리 결과
     */
    public Long getModelParamKey() {
        return modelParamKey;
    }

    
    /**
     * DB JPA 계층 설정 값을 반영합니다.
     *
     * <p>엔티티 생명주기 콜백과 컬럼 매핑 규칙을 기준으로 처리합니다.</p>
     * @param modelParamKey 대상 키 값
     */
    public void setModelParamKey(Long modelParamKey) {
        this.modelParamKey = modelParamKey;
    }

    
    /**
     * DB JPA 계층의 현재 값을 조회합니다.
     *
     * <p>엔티티 생명주기 콜백과 컬럼 매핑 규칙을 기준으로 처리합니다.</p>
     * @return DB JPA 계층 처리 결과
     */
    public Long getModelVersionKey() {
        return modelVersionKey;
    }

    
    /**
     * DB JPA 계층 설정 값을 반영합니다.
     *
     * <p>엔티티 생명주기 콜백과 컬럼 매핑 규칙을 기준으로 처리합니다.</p>
     * @param modelVersionKey 대상 키 값
     */
    public void setModelVersionKey(Long modelVersionKey) {
        this.modelVersionKey = modelVersionKey;
    }

    
    /**
     * DB JPA 계층의 현재 값을 조회합니다.
     *
     * <p>엔티티 생명주기 콜백과 컬럼 매핑 규칙을 기준으로 처리합니다.</p>
     * @return DB JPA 계층 처리 결과
     */
    public String getParamName() {
        return paramName;
    }

    
    /**
     * DB JPA 계층 설정 값을 반영합니다.
     *
     * <p>엔티티 생명주기 콜백과 컬럼 매핑 규칙을 기준으로 처리합니다.</p>
     * @param paramName DB JPA 계층 처리에 사용하는 입력 값
     */
    public void setParamName(String paramName) {
        this.paramName = paramName;
    }

    
    /**
     * DB JPA 계층의 현재 값을 조회합니다.
     *
     * <p>엔티티 생명주기 콜백과 컬럼 매핑 규칙을 기준으로 처리합니다.</p>
     * @return DB JPA 계층 처리 결과
     */
    public String getParamValue() {
        return paramValue;
    }

    
    /**
     * DB JPA 계층 설정 값을 반영합니다.
     *
     * <p>엔티티 생명주기 콜백과 컬럼 매핑 규칙을 기준으로 처리합니다.</p>
     * @param paramValue DB JPA 계층 처리에 사용하는 입력 값
     */
    public void setParamValue(String paramValue) {
        this.paramValue = paramValue;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }
}
