package com.nori.tc.db.jpa.common.entity.model;

import com.nori.tc.db.jpa.common.entity.base.AbstractUpdatedEntity;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import jakarta.persistence.UniqueConstraint;

/**
 * tc_model_workflow 테이블 매핑 엔티티.
 *
 * [DB 스키마]
 * - workflow_key      : bigint generated by default as identity (PK)
 * - model_key         : bigint NOT NULL (tc_model FK, ON DELETE CASCADE)
 * - workflow_name     : varchar(200) NOT NULL
 * - message_name      : varchar(200) NOT NULL
 * - event_id          : varchar(200) NULL
 * - transaction_id    : varchar(200) NULL
 * - workflow_filter   : varchar(200) NULL
 * - action_name       : varchar(200) NOT NULL
 * - action_data_index : varchar(1000) NULL
 * - updated_at        : timestamptz NOT NULL (AbstractUpdatedEntity 상속)
 * - Constraints       : UNIQUE (model_key, workflow_name, message_name)
 *
 * [설계 포인트]
 * 1. MapStruct 호환성:
 * - public 생성자를 제공하여 Mapper가 객체를 생성할 수 있게 합니다.
 *
 * 2. Identity Strategy:
 * - PK(workflow_key)는 DB 자동 생성(Identity)을 따릅니다.
 */
@Entity
@Table(
        name = "tc_model_workflow",
        uniqueConstraints = {
                @UniqueConstraint(
                        name = "uk_tc_model_workflow_model_key_workflow_name_message_name",
                        columnNames = {"model_key", "workflow_name", "message_name"}
                )
        }
)
public class TcModelWorkflowEntity extends AbstractUpdatedEntity {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "workflow_key", nullable = false)
    private Long workflowKey;

    @Column(name = "model_key", nullable = false)
    private Long modelKey;

    @Column(name = "workflow_name", length = 200, nullable = false)
    private String workflowName;

    @Column(name = "message_name", length = 200, nullable = false)
    private String messageName;

    @Column(name = "event_id", length = 200)
    private String eventId;

    @Column(name = "transaction_id", length = 200)
    private String transactionId;

    @Column(name = "workflow_filter", length = 200)
    private String workflowFilter;

    @Column(name = "action_name", length = 200, nullable = false)
    private String actionName;

    @Column(name = "action_data_index", length = 1000)
    private String actionDataIndex;

    // =========================================================================
    // Constructors (MapStruct & JPA)
    // =========================================================================

    /**
     * 기본 생성자 (필수)
     */
    public TcModelWorkflowEntity() {
    }

    /**
     * 전체 인자 생성자
     */
    public TcModelWorkflowEntity(
            Long workflowKey,
            Long modelKey,
            String workflowName,
            String messageName,
            String eventId,
            String transactionId,
            String workflowFilter,
            String actionName,
            String actionDataIndex
    ) {
        this.workflowKey = workflowKey;
        this.modelKey = modelKey;
        this.workflowName = workflowName;
        this.messageName = messageName;
        this.eventId = eventId;
        this.transactionId = transactionId;
        this.workflowFilter = workflowFilter;
        this.actionName = actionName;
        this.actionDataIndex = actionDataIndex;
    }

    // =========================================================================
    // Static Factory
    // =========================================================================

    public static TcModelWorkflowEntity newEntity(long modelKey, String workflowName, String messageName) {
        if (modelKey <= 0) {
            throw new IllegalArgumentException("modelKey must be > 0");
        }
        if (workflowName == null || workflowName.isBlank()) {
            throw new IllegalArgumentException("workflowName must not be null/blank");
        }
        if (messageName == null || messageName.isBlank()) {
            throw new IllegalArgumentException("messageName must not be null/blank");
        }
        TcModelWorkflowEntity e = new TcModelWorkflowEntity();
        e.setModelKey(modelKey);
        e.setWorkflowName(workflowName);
        e.setMessageName(messageName);
        return e;
    }

    // =========================================================================
    // Getters & Setters
    // =========================================================================

    public Long getWorkflowKey() {
        return workflowKey;
    }

    public void setWorkflowKey(Long workflowKey) {
        this.workflowKey = workflowKey;
    }

    public Long getModelKey() {
        return modelKey;
    }

    public void setModelKey(Long modelKey) {
        this.modelKey = modelKey;
    }

    public String getWorkflowName() {
        return workflowName;
    }

    public void setWorkflowName(String workflowName) {
        this.workflowName = workflowName;
    }

    public String getMessageName() {
        return messageName;
    }

    public void setMessageName(String messageName) {
        this.messageName = messageName;
    }

    public String getEventId() {
        return eventId;
    }

    public void setEventId(String eventId) {
        this.eventId = eventId;
    }

    public String getTransactionId() {
        return transactionId;
    }

    public void setTransactionId(String transactionId) {
        this.transactionId = transactionId;
    }

    public String getWorkflowFilter() {
        return workflowFilter;
    }

    public void setWorkflowFilter(String workflowFilter) {
        this.workflowFilter = workflowFilter;
    }

    public String getActionName() {
        return actionName;
    }

    public void setActionName(String actionName) {
        this.actionName = actionName;
    }

    public String getActionDataIndex() {
        return actionDataIndex;
    }

    public void setActionDataIndex(String actionDataIndex) {
        this.actionDataIndex = actionDataIndex;
    }
}
