package com.nori.tc.db.jpa.common.entity.model;

import com.nori.tc.db.jpa.common.entity.base.AbstractUpdatedEntity;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import jakarta.persistence.UniqueConstraint;

/**
 * tc_model_socket_message 테이블 매핑 엔티티.
 *
 * [DB 스키마]
 * - socket_msg_key  : bigint generated by default as identity (PK)
 * - model_version_key       : bigint NOT NULL (FK -> tc_model_version.model_version_key, ON DELETE CASCADE)
 * - socket_msg_name : varchar(1000) NOT NULL
 * - description     : varchar(2000) NULL
 * - data_index      : varchar(200) NULL
 * - updated_at      : timestamptz NOT NULL (AbstractUpdatedEntity 상속)
 * - Constraints     : UNIQUE (model_version_key, socket_msg_name)
 *
 * [설계 포인트]
 * 1. MapStruct 호환성:
 * - public 생성자를 제공하여 Mapper가 객체를 생성할 수 있게 합니다.
 *
 * 2. Identity Strategy:
 * - PK(socket_msg_key)는 DB 자동 생성(Identity)을 따릅니다.
 */
@Entity
@Table(
        name = "tc_model_socket_message",
        uniqueConstraints = {
                @UniqueConstraint(name = "uk_tc_model_socket_message_model_version_key_socket_msg_name", columnNames = {"model_version_key", "socket_msg_name"})
        }
)
public class TcModelSocketMessageEntity extends AbstractUpdatedEntity {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "socket_msg_key", nullable = false)
    private Long socketMsgKey;

    @Column(name = "model_version_key", nullable = false)
    private Long modelVersionKey;

    @Column(name = "socket_msg_name", length = 1000, nullable = false)
    private String socketMsgName;

    @Column(name = "description", length = 2000)
    private String description;

    @Column(name = "data_index", length = 200)
    private String dataIndex;

    // =========================================================================
    // Constructors (MapStruct & JPA)
    // =========================================================================

    /**
     * 기본 생성자 (필수)
     * - JPA 프록시 생성용
     * - MapStruct 타겟 객체 생성용 (public 필수)
     */
    public TcModelSocketMessageEntity() {
    }

    /**
     * 전체 인자 생성자
     * - MapStruct가 Domain -> Entity 변환 시 모든 필드를 한 번에 주입할 때 사용
     */
    public TcModelSocketMessageEntity(
            Long socketMsgKey,
            Long modelVersionKey,
            String socketMsgName,
            String description,
            String dataIndex
    ) {
        this.socketMsgKey = socketMsgKey;
        this.modelVersionKey = modelVersionKey;
        this.socketMsgName = socketMsgName;
        this.description = description;
        this.dataIndex = dataIndex;
    }

    // =========================================================================
    // Static Factory
    // =========================================================================

    
    /**
     * DB JPA 계층 규약에 맞게 데이터를 변환/구성합니다.
     *
     * <p>엔티티 생명주기 콜백과 컬럼 매핑 규칙을 기준으로 처리합니다.</p>
     * @param modelVersionKey 대상 키 값
     * @param socketMsgName 통신 채널/세션 정보
     * @return DB JPA 계층 처리 결과
     */
    public static TcModelSocketMessageEntity newEntity(long modelVersionKey, String socketMsgName) {
        if (modelVersionKey <= 0) {
            throw new IllegalArgumentException("modelVersionKey must be > 0");
        }
        if (socketMsgName == null || socketMsgName.isBlank()) {
            throw new IllegalArgumentException("socketMsgName must not be null/blank");
        }
        TcModelSocketMessageEntity entity = new TcModelSocketMessageEntity();
        entity.setModelVersionKey(modelVersionKey);
        entity.setSocketMsgName(socketMsgName);
        return entity;
    }

    // =========================================================================
    // Getters & Setters
    // =========================================================================

    
    /**
     * DB JPA 계층의 현재 값을 조회합니다.
     *
     * <p>엔티티 생명주기 콜백과 컬럼 매핑 규칙을 기준으로 처리합니다.</p>
     * @return DB JPA 계층 처리 결과
     */
    public Long getSocketMsgKey() {
        return socketMsgKey;
    }

    
    /**
     * DB JPA 계층 설정 값을 반영합니다.
     *
     * <p>엔티티 생명주기 콜백과 컬럼 매핑 규칙을 기준으로 처리합니다.</p>
     * @param socketMsgKey 대상 키 값
     */
    public void setSocketMsgKey(Long socketMsgKey) {
        this.socketMsgKey = socketMsgKey;
    }

    
    /**
     * DB JPA 계층의 현재 값을 조회합니다.
     *
     * <p>엔티티 생명주기 콜백과 컬럼 매핑 규칙을 기준으로 처리합니다.</p>
     * @return DB JPA 계층 처리 결과
     */
    public Long getModelVersionKey() {
        return modelVersionKey;
    }

    
    /**
     * DB JPA 계층 설정 값을 반영합니다.
     *
     * <p>엔티티 생명주기 콜백과 컬럼 매핑 규칙을 기준으로 처리합니다.</p>
     * @param modelVersionKey 대상 키 값
     */
    public void setModelVersionKey(Long modelVersionKey) {
        this.modelVersionKey = modelVersionKey;
    }

    
    /**
     * DB JPA 계층의 현재 값을 조회합니다.
     *
     * <p>엔티티 생명주기 콜백과 컬럼 매핑 규칙을 기준으로 처리합니다.</p>
     * @return DB JPA 계층 처리 결과
     */
    public String getSocketMsgName() {
        return socketMsgName;
    }

    
    /**
     * DB JPA 계층 설정 값을 반영합니다.
     *
     * <p>엔티티 생명주기 콜백과 컬럼 매핑 규칙을 기준으로 처리합니다.</p>
     * @param socketMsgName 통신 채널/세션 정보
     */
    public void setSocketMsgName(String socketMsgName) {
        this.socketMsgName = socketMsgName;
    }

    
    /**
     * DB JPA 계층의 현재 값을 조회합니다.
     *
     * <p>엔티티 생명주기 콜백과 컬럼 매핑 규칙을 기준으로 처리합니다.</p>
     * @return DB JPA 계층 처리 결과
     */
    public String getDescription() {
        return description;
    }

    
    /**
     * DB JPA 계층 설정 값을 반영합니다.
     *
     * <p>엔티티 생명주기 콜백과 컬럼 매핑 규칙을 기준으로 처리합니다.</p>
     * @param description DB JPA 계층 처리에 사용하는 입력 값
     */
    public void setDescription(String description) {
        this.description = description;
    }

    
    /**
     * DB JPA 계층의 현재 값을 조회합니다.
     *
     * <p>엔티티 생명주기 콜백과 컬럼 매핑 규칙을 기준으로 처리합니다.</p>
     * @return DB JPA 계층 처리 결과
     */
    public String getDataIndex() {
        return dataIndex;
    }

    
    /**
     * DB JPA 계층 설정 값을 반영합니다.
     *
     * <p>엔티티 생명주기 콜백과 컬럼 매핑 규칙을 기준으로 처리합니다.</p>
     * @param dataIndex 처리할 원본 데이터
     */
    public void setDataIndex(String dataIndex) {
        this.dataIndex = dataIndex;
    }
}
