package com.nori.tc.db.jpa.common.entity.model;

import com.nori.tc.db.jpa.common.entity.base.AbstractUpdatedEntity;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import jakarta.persistence.UniqueConstraint;

/**
 * tc_model_mes_message 테이블 매핑 엔티티.
 *
 * [DB 스키마]
 * - mes_msg_key       : bigint generated by default as identity (PK)
 * - model_version_key : bigint NOT NULL (tc_model_version FK, ON DELETE CASCADE)
 * - mes_msg_name      : varchar(1000) NOT NULL
 * - description       : varchar(2000) NULL
 * - data_index        : varchar(200) NULL
 * - updated_at        : timestamptz NOT NULL
 * - Constraints       : UNIQUE (model_version_key, mes_msg_name)
 *
 * [설계 포인트]
 * 1. MapStruct 호환성:
 * - public 생성자를 제공하여 Mapper가 객체를 생성할 수 있게 합니다.
 *
 * 2. Identity Strategy:
 * - PK(mes_msg_key)는 DB 자동 생성(Identity)을 따릅니다.
 */
@Entity
@Table(
        name = "tc_model_mes_message",
        uniqueConstraints = {
                @UniqueConstraint(
                        name = "uk_tc_model_mes_message_model_version_key_mes_msg_name",
                        columnNames = {"model_version_key", "mes_msg_name"}
                )
        }
)
public class TcModelMesMessageEntity extends AbstractUpdatedEntity {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "mes_msg_key", nullable = false)
    private Long mesMsgKey;

    @Column(name = "model_version_key", nullable = false)
    private Long modelVersionKey;

    @Column(name = "mes_msg_name", length = 1000, nullable = false)
    private String mesMsgName;

    @Column(name = "description", length = 2000)
    private String description;

    @Column(name = "data_index", length = 200)
    private String dataIndex;

    // =========================================================================
    // Constructors (MapStruct & JPA)
    // =========================================================================

    /**
     * 기본 생성자 (필수)
     */
    public TcModelMesMessageEntity() {
    }

    /**
     * 전체 인자 생성자
     */
    public TcModelMesMessageEntity(
            Long mesMsgKey,
            Long modelVersionKey,
            String mesMsgName,
            String description,
            String dataIndex
    ) {
        this.mesMsgKey = mesMsgKey;
        this.modelVersionKey = modelVersionKey;
        this.mesMsgName = mesMsgName;
        this.description = description;
        this.dataIndex = dataIndex;
    }

    // =========================================================================
    // Static Factory
    // =========================================================================

    /**
     * 신규 엔티티를 생성합니다.
     *
     * @param modelVersionKey 모델 버전 키
     * @param mesMsgName      MES 메시지 이름
     * @return 초기화된 엔티티 (PK 미지정)
     */
    public static TcModelMesMessageEntity newEntity(Long modelVersionKey, String mesMsgName) {
        if (modelVersionKey == null || modelVersionKey <= 0) {
            throw new IllegalArgumentException("modelVersionKey must be positive");
        }
        if (mesMsgName == null || mesMsgName.isBlank()) {
            throw new IllegalArgumentException("mesMsgName must not be null/blank");
        }
        TcModelMesMessageEntity e = new TcModelMesMessageEntity();
        e.setModelVersionKey(modelVersionKey);
        e.setMesMsgName(mesMsgName);
        return e;
    }

    // =========================================================================
    // Getters & Setters
    // =========================================================================

    public Long getMesMsgKey() {
        return mesMsgKey;
    }

    public void setMesMsgKey(Long mesMsgKey) {
        this.mesMsgKey = mesMsgKey;
    }

    public Long getModelVersionKey() {
        return modelVersionKey;
    }

    public void setModelVersionKey(Long modelVersionKey) {
        this.modelVersionKey = modelVersionKey;
    }

    public String getMesMsgName() {
        return mesMsgName;
    }

    public void setMesMsgName(String mesMsgName) {
        this.mesMsgName = mesMsgName;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getDataIndex() {
        return dataIndex;
    }

    public void setDataIndex(String dataIndex) {
        this.dataIndex = dataIndex;
    }
}
