package com.nori.tc.db.jpa.common.entity.model;

import com.nori.tc.db.jpa.common.entity.base.AbstractUpdatedEntity;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import jakarta.persistence.UniqueConstraint;

/**
 * tc_model_mdf 테이블 매핑 엔티티.
 *
 * [DB 스키마]
 * - mdf_key    : bigint generated by default as identity (PK)
 * - model_version_key  : bigint NOT NULL (FK -> tc_model_version.model_version_key)
 * - mdf_name   : varchar(100) NOT NULL
 * - mdf_file   : bytea NOT NULL
 * - updated_at : timestamp with time zone NOT NULL
 * - Constraints: UNIQUE (model_version_key, mdf_name)
 *
 * [설계 포인트]
 * 1. MapStruct 호환성:
 * - public 기본 생성자 + 전체 인자 생성자를 제공하여 Mapper가 객체를 생성할 수 있게 합니다.
 * 2. Binary 컬럼 처리:
 * - mdf_file은 PostgreSQL bytea 컬럼이므로 columnDefinition=bytea를 명시하여
 *   Hibernate가 OID(BLOB) 대신 bytea(BINARY)로 해석하도록 고정합니다.
 */
@Entity
@Table(
        name = "tc_model_mdf",
        uniqueConstraints = {
                @UniqueConstraint(name = "uk_tc_model_mdf_model_version_key_mdf_name", columnNames = {"model_version_key", "mdf_name"})
        }
)
public class TcModelMdfEntity extends AbstractUpdatedEntity {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "mdf_key", nullable = false)
    private Long mdfKey;

    @Column(name = "model_version_key", nullable = false)
    private Long modelVersionKey;

    @Column(name = "mdf_name", length = 100, nullable = false)
    private String mdfName;

    /**
     * PostgreSQL bytea 컬럼 매핑.
     *
     * <p>@Lob를 사용하면 Hibernate가 OID(BLOB)로 해석할 수 있으므로,
     * DB 스키마(bytea)와 일치시키기 위해 columnDefinition을 명시합니다.</p>
     */
    @Column(name = "mdf_file", nullable = false, columnDefinition = "bytea")
    private byte[] mdfFile;

    // =========================================================================
    // Constructors (MapStruct & JPA)
    // =========================================================================

    /**
     * 기본 생성자 (필수)
     */
    public TcModelMdfEntity() {
    }

    /**
     * 전체 인자 생성자
     */
    public TcModelMdfEntity(Long mdfKey, Long modelVersionKey, String mdfName, byte[] mdfFile) {
        this.mdfKey = mdfKey;
        this.modelVersionKey = modelVersionKey;
        this.mdfName = mdfName;
        this.mdfFile = mdfFile;
    }

    // =========================================================================
    // Static Factory
    // =========================================================================

    
    /**
     * DB JPA 계층 규약에 맞게 데이터를 변환/구성합니다.
     *
     * <p>엔티티 생명주기 콜백과 컬럼 매핑 규칙을 기준으로 처리합니다.</p>
     * @param modelVersionKey 대상 키 값
     * @param mdfName DB JPA 계층 처리에 사용하는 입력 값
     * @param mdfFile DB JPA 계층 처리에 사용하는 입력 값
     * @return DB JPA 계층 처리 결과
     */
    public static TcModelMdfEntity newEntity(long modelVersionKey, String mdfName, byte[] mdfFile) {
        if (modelVersionKey <= 0) {
            throw new IllegalArgumentException("modelVersionKey must be > 0");
        }
        if (mdfName == null || mdfName.isBlank()) {
            throw new IllegalArgumentException("mdfName must not be null/blank");
        }
        if (mdfFile == null || mdfFile.length == 0) {
            throw new IllegalArgumentException("mdfFile must not be null/empty");
        }
        TcModelMdfEntity e = new TcModelMdfEntity();
        e.setModelVersionKey(modelVersionKey);
        e.setMdfName(mdfName);
        e.setMdfFile(mdfFile);
        return e;
    }

    // =========================================================================
    // Getters & Setters
    // =========================================================================

    
    /**
     * DB JPA 계층의 현재 값을 조회합니다.
     *
     * <p>엔티티 생명주기 콜백과 컬럼 매핑 규칙을 기준으로 처리합니다.</p>
     * @return DB JPA 계층 처리 결과
     */
    public Long getMdfKey() {
        return mdfKey;
    }

    
    /**
     * DB JPA 계층 설정 값을 반영합니다.
     *
     * <p>엔티티 생명주기 콜백과 컬럼 매핑 규칙을 기준으로 처리합니다.</p>
     * @param mdfKey 대상 키 값
     */
    public void setMdfKey(Long mdfKey) {
        this.mdfKey = mdfKey;
    }

    
    /**
     * DB JPA 계층의 현재 값을 조회합니다.
     *
     * <p>엔티티 생명주기 콜백과 컬럼 매핑 규칙을 기준으로 처리합니다.</p>
     * @return DB JPA 계층 처리 결과
     */
    public Long getModelVersionKey() {
        return modelVersionKey;
    }

    
    /**
     * DB JPA 계층 설정 값을 반영합니다.
     *
     * <p>엔티티 생명주기 콜백과 컬럼 매핑 규칙을 기준으로 처리합니다.</p>
     * @param modelVersionKey 대상 키 값
     */
    public void setModelVersionKey(Long modelVersionKey) {
        this.modelVersionKey = modelVersionKey;
    }

    
    /**
     * DB JPA 계층의 현재 값을 조회합니다.
     *
     * <p>엔티티 생명주기 콜백과 컬럼 매핑 규칙을 기준으로 처리합니다.</p>
     * @return DB JPA 계층 처리 결과
     */
    public String getMdfName() {
        return mdfName;
    }

    
    /**
     * DB JPA 계층 설정 값을 반영합니다.
     *
     * <p>엔티티 생명주기 콜백과 컬럼 매핑 규칙을 기준으로 처리합니다.</p>
     * @param mdfName DB JPA 계층 처리에 사용하는 입력 값
     */
    public void setMdfName(String mdfName) {
        this.mdfName = mdfName;
    }

    
    /**
     * DB JPA 계층의 현재 값을 조회합니다.
     *
     * <p>엔티티 생명주기 콜백과 컬럼 매핑 규칙을 기준으로 처리합니다.</p>
     * @return DB JPA 계층 처리 결과
     */
    public byte[] getMdfFile() {
        return mdfFile;
    }

    
    /**
     * DB JPA 계층 설정 값을 반영합니다.
     *
     * <p>엔티티 생명주기 콜백과 컬럼 매핑 규칙을 기준으로 처리합니다.</p>
     * @param mdfFile DB JPA 계층 처리에 사용하는 입력 값
     */
    public void setMdfFile(byte[] mdfFile) {
        this.mdfFile = mdfFile;
    }
}
