package com.nori.tc.db.jpa.common.entity.model;

import com.nori.tc.db.domain.common.DcopCalculationRule;
import com.nori.tc.db.domain.common.DcopCollectionRule;
import com.nori.tc.db.jpa.common.entity.base.AbstractUpdatedEntity;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import jakarta.persistence.UniqueConstraint;

/**
 * tc_model_dcop_item 테이블 매핑 엔티티.
 *
 * [DB 스키마]
 * - dcop_item_key    : bigint generated by default as identity (PK)
 * - model_key        : bigint NOT NULL (FK -> tc_model.model_key)
 * - dcop_item_name   : varchar(200) NOT NULL
 * - workflow_name    : varchar(200) NULL
 * - event_id         : varchar(100) NULL
 * - variable_id      : varchar(100) NULL
 * - collection_rule  : varchar(10) NULL (FIRST/LAST)
 * - calculation_rule : varchar(20) NULL (ADD/MULTIPLY/SUBTRACT/NONE)
 * - order_rule       : int NULL (>= 0)
 * - updated_at       : timestamptz NOT NULL default CURRENT_TIMESTAMP
 * - Constraints      : UNIQUE (model_key, dcop_item_name)
 */
@Entity
@Table(
        name = "tc_model_dcop_item",
        uniqueConstraints = {
                @UniqueConstraint(
                        name = "uk_tc_model_dcop_item_model_key_dcop_item_name",
                        columnNames = {"model_key", "dcop_item_name"}
                )
        }
)
public class TcModelDcopItemEntity extends AbstractUpdatedEntity {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "dcop_item_key", nullable = false)
    private Long dcopItemKey;

    @Column(name = "model_key", nullable = false)
    private Long modelKey;

    @Column(name = "dcop_item_name", length = 200, nullable = false)
    private String dcopItemName;

    @Column(name = "workflow_name", length = 200)
    private String workflowName;

    @Column(name = "event_id", length = 100)
    private String eventId;

    @Column(name = "variable_id", length = 100)
    private String variableId;

    @Enumerated(EnumType.STRING)
    @Column(name = "collection_rule", length = 10)
    private DcopCollectionRule collectionRule;

    @Enumerated(EnumType.STRING)
    @Column(name = "calculation_rule", length = 20)
    private DcopCalculationRule calculationRule;

    @Column(name = "order_rule")
    private Integer orderRule;

    // =========================================================================
    // Constructors (MapStruct & JPA)
    // =========================================================================

    /**
     * 기본 생성자 (필수)
     * - JPA 프록시 생성용
     * - MapStruct 타겟 객체 생성용 (public 필수)
     */
    public TcModelDcopItemEntity() {
    }

    /**
     * 전체 인자 생성자
     */
    public TcModelDcopItemEntity(
            Long dcopItemKey,
            Long modelKey,
            String dcopItemName,
            String workflowName,
            String eventId,
            String variableId,
            DcopCollectionRule collectionRule,
            DcopCalculationRule calculationRule,
            Integer orderRule
    ) {
        this.dcopItemKey = dcopItemKey;
        this.modelKey = modelKey;
        this.dcopItemName = dcopItemName;
        this.workflowName = workflowName;
        this.eventId = eventId;
        this.variableId = variableId;
        this.collectionRule = collectionRule;
        this.calculationRule = calculationRule;
        this.orderRule = orderRule;
    }

    // =========================================================================
    // Static Factory
    // =========================================================================

    /**
     * 신규 엔티티 생성 팩토리
     * - Unique Key(model_key, dcop_item_name)를 기반으로 초기화한다.
     */
    public static TcModelDcopItemEntity newEntity(long modelKey, String dcopItemName) {
        if (modelKey <= 0) {
            throw new IllegalArgumentException("modelKey must be > 0");
        }
        if (dcopItemName == null || dcopItemName.isBlank()) {
            throw new IllegalArgumentException("dcopItemName must not be null/blank");
        }
        TcModelDcopItemEntity e = new TcModelDcopItemEntity();
        e.setModelKey(modelKey);
        e.setDcopItemName(dcopItemName);
        return e;
    }

    // =========================================================================
    // Getters & Setters
    // =========================================================================

    public Long getDcopItemKey() {
        return dcopItemKey;
    }

    public void setDcopItemKey(Long dcopItemKey) {
        this.dcopItemKey = dcopItemKey;
    }

    public Long getModelKey() {
        return modelKey;
    }

    public void setModelKey(Long modelKey) {
        this.modelKey = modelKey;
    }

    public String getDcopItemName() {
        return dcopItemName;
    }

    public void setDcopItemName(String dcopItemName) {
        this.dcopItemName = dcopItemName;
    }

    public String getWorkflowName() {
        return workflowName;
    }

    public void setWorkflowName(String workflowName) {
        this.workflowName = workflowName;
    }

    public String getEventId() {
        return eventId;
    }

    public void setEventId(String eventId) {
        this.eventId = eventId;
    }

    public String getVariableId() {
        return variableId;
    }

    public void setVariableId(String variableId) {
        this.variableId = variableId;
    }

    public DcopCollectionRule getCollectionRule() {
        return collectionRule;
    }

    public void setCollectionRule(DcopCollectionRule collectionRule) {
        this.collectionRule = collectionRule;
    }

    public DcopCalculationRule getCalculationRule() {
        return calculationRule;
    }

    public void setCalculationRule(DcopCalculationRule calculationRule) {
        this.calculationRule = calculationRule;
    }

    public Integer getOrderRule() {
        return orderRule;
    }

    public void setOrderRule(Integer orderRule) {
        this.orderRule = orderRule;
    }
}
