package com.nori.tc.db.jpa.common.entity.model;

import com.nori.tc.db.domain.common.model.DcopCalculationRule;
import com.nori.tc.db.domain.common.model.DcopCollectionRule;
import com.nori.tc.db.jpa.common.entity.base.AbstractUpdatedEntity;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import jakarta.persistence.UniqueConstraint;

/**
 * tc_model_dcop_item 테이블 매핑 엔티티.
 *
 * [DB 스키마]
 * - dcop_item_key    : bigint generated by default as identity (PK)
 * - model_version_key        : bigint NOT NULL (FK -> tc_model_version.model_version_key)
 * - dcop_item_name   : varchar(1000) NOT NULL
 * - workflow_name    : varchar(1000) NULL
 * - event_id         : varchar(100) NULL
 * - variable_id      : varchar(1000) NULL
 * - collection_rule  : varchar(10) NULL (FIRST/LAST)
 * - calculation_rule : varchar(2000) NULL (ADD/MULTIPLY/SUBTRACT/NONE)
 * - order_rule       : int NULL (>= 0)
 * - updated_at       : timestamptz NOT NULL default CURRENT_TIMESTAMP
 * - Constraints      : UNIQUE (model_version_key, dcop_item_name)
 */
@Entity
@Table(
        name = "tc_model_dcop_item",
        uniqueConstraints = {
                @UniqueConstraint(
                        name = "uk_tc_model_dcop_item_model_version_key_dcop_item_name",
                        columnNames = {"model_version_key", "dcop_item_name"}
                )
        }
)
public class TcModelDcopItemEntity extends AbstractUpdatedEntity {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "dcop_item_key", nullable = false)
    private Long dcopItemKey;

    @Column(name = "model_version_key", nullable = false)
    private Long modelVersionKey;

    @Column(name = "dcop_item_name", length = 1000, nullable = false)
    private String dcopItemName;

    @Column(name = "workflow_name", length = 1000)
    private String workflowName;

    @Column(name = "event_id", length = 100)
    private String eventId;

    @Column(name = "variable_id", length = 1000)
    private String variableId;

    @Enumerated(EnumType.STRING)
    @Column(name = "collection_rule", length = 10)
    private DcopCollectionRule collectionRule;

    @Enumerated(EnumType.STRING)
    @Column(name = "calculation_rule", length = 2000)
    private DcopCalculationRule calculationRule;

    @Column(name = "order_rule")
    private Integer orderRule;

    // =========================================================================
    // Constructors (MapStruct & JPA)
    // =========================================================================

    /**
     * 기본 생성자 (필수)
     * - JPA 프록시 생성용
     * - MapStruct 타겟 객체 생성용 (public 필수)
     */
    public TcModelDcopItemEntity() {
    }

    /**
     * 전체 인자 생성자
     */
    public TcModelDcopItemEntity(
            Long dcopItemKey,
            Long modelVersionKey,
            String dcopItemName,
            String workflowName,
            String eventId,
            String variableId,
            DcopCollectionRule collectionRule,
            DcopCalculationRule calculationRule,
            Integer orderRule
    ) {
        this.dcopItemKey = dcopItemKey;
        this.modelVersionKey = modelVersionKey;
        this.dcopItemName = dcopItemName;
        this.workflowName = workflowName;
        this.eventId = eventId;
        this.variableId = variableId;
        this.collectionRule = collectionRule;
        this.calculationRule = calculationRule;
        this.orderRule = orderRule;
    }

    // =========================================================================
    // Static Factory
    // =========================================================================

    /**
     * 신규 엔티티 생성 팩토리
     * - Unique Key(model_version_key, dcop_item_name)를 기반으로 초기화한다.
     */
    public static TcModelDcopItemEntity newEntity(long modelVersionKey, String dcopItemName) {
        if (modelVersionKey <= 0) {
            throw new IllegalArgumentException("modelVersionKey must be > 0");
        }
        if (dcopItemName == null || dcopItemName.isBlank()) {
            throw new IllegalArgumentException("dcopItemName must not be null/blank");
        }
        TcModelDcopItemEntity e = new TcModelDcopItemEntity();
        e.setModelVersionKey(modelVersionKey);
        e.setDcopItemName(dcopItemName);
        return e;
    }

    // =========================================================================
    // Getters & Setters
    // =========================================================================

    
    /**
     * DB JPA 계층의 현재 값을 조회합니다.
     *
     * <p>엔티티 생명주기 콜백과 컬럼 매핑 규칙을 기준으로 처리합니다.</p>
     * @return DB JPA 계층 처리 결과
     */
    public Long getDcopItemKey() {
        return dcopItemKey;
    }

    
    /**
     * DB JPA 계층 설정 값을 반영합니다.
     *
     * <p>엔티티 생명주기 콜백과 컬럼 매핑 규칙을 기준으로 처리합니다.</p>
     * @param dcopItemKey 대상 키 값
     */
    public void setDcopItemKey(Long dcopItemKey) {
        this.dcopItemKey = dcopItemKey;
    }

    
    /**
     * DB JPA 계층의 현재 값을 조회합니다.
     *
     * <p>엔티티 생명주기 콜백과 컬럼 매핑 규칙을 기준으로 처리합니다.</p>
     * @return DB JPA 계층 처리 결과
     */
    public Long getModelVersionKey() {
        return modelVersionKey;
    }

    
    /**
     * DB JPA 계층 설정 값을 반영합니다.
     *
     * <p>엔티티 생명주기 콜백과 컬럼 매핑 규칙을 기준으로 처리합니다.</p>
     * @param modelVersionKey 대상 키 값
     */
    public void setModelVersionKey(Long modelVersionKey) {
        this.modelVersionKey = modelVersionKey;
    }

    
    /**
     * DB JPA 계층의 현재 값을 조회합니다.
     *
     * <p>엔티티 생명주기 콜백과 컬럼 매핑 규칙을 기준으로 처리합니다.</p>
     * @return DB JPA 계층 처리 결과
     */
    public String getDcopItemName() {
        return dcopItemName;
    }

    
    /**
     * DB JPA 계층 설정 값을 반영합니다.
     *
     * <p>엔티티 생명주기 콜백과 컬럼 매핑 규칙을 기준으로 처리합니다.</p>
     * @param dcopItemName DB JPA 계층 처리에 사용하는 입력 값
     */
    public void setDcopItemName(String dcopItemName) {
        this.dcopItemName = dcopItemName;
    }

    
    /**
     * DB JPA 계층의 현재 값을 조회합니다.
     *
     * <p>엔티티 생명주기 콜백과 컬럼 매핑 규칙을 기준으로 처리합니다.</p>
     * @return DB JPA 계층 처리 결과
     */
    public String getWorkflowName() {
        return workflowName;
    }

    
    /**
     * DB JPA 계층 설정 값을 반영합니다.
     *
     * <p>엔티티 생명주기 콜백과 컬럼 매핑 규칙을 기준으로 처리합니다.</p>
     * @param workflowName DB JPA 계층 처리에 사용하는 입력 값
     */
    public void setWorkflowName(String workflowName) {
        this.workflowName = workflowName;
    }

    
    /**
     * DB JPA 계층의 현재 값을 조회합니다.
     *
     * <p>엔티티 생명주기 콜백과 컬럼 매핑 규칙을 기준으로 처리합니다.</p>
     * @return DB JPA 계층 처리 결과
     */
    public String getEventId() {
        return eventId;
    }

    
    /**
     * DB JPA 계층 설정 값을 반영합니다.
     *
     * <p>엔티티 생명주기 콜백과 컬럼 매핑 규칙을 기준으로 처리합니다.</p>
     * @param eventId 처리할 이벤트 정보
     */
    public void setEventId(String eventId) {
        this.eventId = eventId;
    }

    
    /**
     * DB JPA 계층의 현재 값을 조회합니다.
     *
     * <p>엔티티 생명주기 콜백과 컬럼 매핑 규칙을 기준으로 처리합니다.</p>
     * @return DB JPA 계층 처리 결과
     */
    public String getVariableId() {
        return variableId;
    }

    
    /**
     * DB JPA 계층 설정 값을 반영합니다.
     *
     * <p>엔티티 생명주기 콜백과 컬럼 매핑 규칙을 기준으로 처리합니다.</p>
     * @param variableId DB JPA 계층 처리에 사용하는 입력 값
     */
    public void setVariableId(String variableId) {
        this.variableId = variableId;
    }

    
    /**
     * DB JPA 계층의 현재 값을 조회합니다.
     *
     * <p>엔티티 생명주기 콜백과 컬럼 매핑 규칙을 기준으로 처리합니다.</p>
     * @return DB JPA 계층 처리 결과
     */
    public DcopCollectionRule getCollectionRule() {
        return collectionRule;
    }

    
    /**
     * DB JPA 계층 설정 값을 반영합니다.
     *
     * <p>엔티티 생명주기 콜백과 컬럼 매핑 규칙을 기준으로 처리합니다.</p>
     * @param collectionRule DB JPA 계층 처리에 사용하는 입력 값
     */
    public void setCollectionRule(DcopCollectionRule collectionRule) {
        this.collectionRule = collectionRule;
    }

    
    /**
     * DB JPA 계층의 현재 값을 조회합니다.
     *
     * <p>엔티티 생명주기 콜백과 컬럼 매핑 규칙을 기준으로 처리합니다.</p>
     * @return DB JPA 계층 처리 결과
     */
    public DcopCalculationRule getCalculationRule() {
        return calculationRule;
    }

    
    /**
     * DB JPA 계층 설정 값을 반영합니다.
     *
     * <p>엔티티 생명주기 콜백과 컬럼 매핑 규칙을 기준으로 처리합니다.</p>
     * @param calculationRule DB JPA 계층 처리에 사용하는 입력 값
     */
    public void setCalculationRule(DcopCalculationRule calculationRule) {
        this.calculationRule = calculationRule;
    }

    
    /**
     * DB JPA 계층의 현재 값을 조회합니다.
     *
     * <p>엔티티 생명주기 콜백과 컬럼 매핑 규칙을 기준으로 처리합니다.</p>
     * @return DB JPA 계층 처리 결과
     */
    public Integer getOrderRule() {
        return orderRule;
    }

    
    /**
     * DB JPA 계층 설정 값을 반영합니다.
     *
     * <p>엔티티 생명주기 콜백과 컬럼 매핑 규칙을 기준으로 처리합니다.</p>
     * @param orderRule DB JPA 계층 처리에 사용하는 입력 값
     */
    public void setOrderRule(Integer orderRule) {
        this.orderRule = orderRule;
    }
}
