package com.nori.tc.db.jpa.common.entity.model;

import com.nori.tc.db.jpa.common.entity.base.AbstractUpdatedEntity;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import jakarta.persistence.UniqueConstraint;

/**
 * tc_model_param 테이블 매핑 엔티티.
 *
 * [DB 스키마]
 * - model_param_key : bigint generated by default as identity (PK)
 * - model_key       : bigint NOT NULL (FK -> tc_model.model_key)
 * - param_name      : varchar(128) NOT NULL
 * - param_value     : varchar(2000) NULL
 * - updated_at      : timestamptz NOT NULL default CURRENT_TIMESTAMP
 * - Constraints     : UNIQUE (model_key, param_name)
 */
@Entity
@Table(
        name = "tc_model_param",
        uniqueConstraints = {
                @UniqueConstraint(
                        name = "uk_tc_model_param_model_key_param_name",
                        columnNames = {"model_key", "param_name"}
                )
        }
)
public class TcModelParamEntity extends AbstractUpdatedEntity {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "model_param_key", nullable = false)
    private Long modelParamKey;

    @Column(name = "model_key", nullable = false)
    private Long modelKey;

    @Column(name = "param_name", length = 128, nullable = false)
    private String paramName;

    @Column(name = "param_value", length = 2000)
    private String paramValue;

    // =========================================================================
    // Constructors (MapStruct & JPA)
    // =========================================================================

    /**
     * 기본 생성자 (필수)
     * - JPA 프록시 생성용
     * - MapStruct 타겟 객체 생성용 (public 필수)
     */
    public TcModelParamEntity() {
    }

    /**
     * 전체 인자 생성자
     */
    public TcModelParamEntity(Long modelParamKey, Long modelKey, String paramName, String paramValue) {
        this.modelParamKey = modelParamKey;
        this.modelKey = modelKey;
        this.paramName = paramName;
        this.paramValue = paramValue;
    }

    // =========================================================================
    // Static Factory
    // =========================================================================

    /**
     * 신규 엔티티 생성 팩토리
     * - Unique Key(model_key, param_name)를 기반으로 초기화한다.
     */
    public static TcModelParamEntity newEntity(long modelKey, String paramName) {
        if (modelKey <= 0) {
            throw new IllegalArgumentException("modelKey must be > 0");
        }
        if (paramName == null || paramName.isBlank()) {
            throw new IllegalArgumentException("paramName must not be null/blank");
        }

        TcModelParamEntity e = new TcModelParamEntity();
        e.setModelKey(modelKey);
        e.setParamName(paramName);
        return e;
    }

    // =========================================================================
    // Getters & Setters
    // =========================================================================

    public Long getModelParamKey() {
        return modelParamKey;
    }

    public void setModelParamKey(Long modelParamKey) {
        this.modelParamKey = modelParamKey;
    }

    public Long getModelKey() {
        return modelKey;
    }

    public void setModelKey(Long modelKey) {
        this.modelKey = modelKey;
    }

    public String getParamName() {
        return paramName;
    }

    public void setParamName(String paramName) {
        this.paramName = paramName;
    }

    public String getParamValue() {
        return paramValue;
    }

    public void setParamValue(String paramValue) {
        this.paramValue = paramValue;
    }
}
