package com.nori.tc.db.jpa.common.entity.model;

import com.nori.tc.db.jpa.common.entity.base.AbstractUpdatedEntity;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.PrePersist;
import jakarta.persistence.Table;
import jakarta.persistence.UniqueConstraint;

/**
 * tc_model_reportid 테이블 매핑 엔티티.
 *
 * [DB 스키마]
 * - report_key  : bigint generated by default as identity (PK)
 * - model_key   : bigint NOT NULL (FK -> tc_model.model_key)
 * - report_id   : varchar(100) NOT NULL
 * - variable_id : varchar(1000) NULL
 * - enabled     : boolean NOT NULL default false
 * - updated_at  : timestamptz NOT NULL default CURRENT_TIMESTAMP
 * - Constraints : UNIQUE (model_key, report_id)
 */
@Entity
@Table(
        name = "tc_model_reportid",
        uniqueConstraints = {
                @UniqueConstraint(
                        name = "uk_tc_model_reportid_model_key_report_id",
                        columnNames = {"model_key", "report_id"}
                )
        }
)
public class TcModelReportIdEntity extends AbstractUpdatedEntity {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "report_key", nullable = false)
    private Long reportKey;

    @Column(name = "model_key", nullable = false)
    private Long modelKey;

    @Column(name = "report_id", length = 100, nullable = false)
    private String reportId;

    @Column(name = "variable_id", length = 1000)
    private String variableId;

    @Column(name = "enabled", nullable = false)
    private Boolean enabled;

    // =========================================================================
    // Constructors (MapStruct & JPA)
    // =========================================================================

    /**
     * 기본 생성자 (필수)
     * - JPA 프록시 생성용
     * - MapStruct 타겟 객체 생성용 (public 필수)
     */
    public TcModelReportIdEntity() {
    }

    /**
     * 전체 인자 생성자
     */
    public TcModelReportIdEntity(
            Long reportKey,
            Long modelKey,
            String reportId,
            String variableId,
            Boolean enabled
    ) {
        this.reportKey = reportKey;
        this.modelKey = modelKey;
        this.reportId = reportId;
        this.variableId = variableId;
        this.enabled = enabled;
    }

    // =========================================================================
    // Lifecycle
    // =========================================================================

    
    /**
     * DB JPA 계층 감사/상태 필드를 최신 값으로 갱신합니다.
     *
     * <p>엔티티 생명주기 콜백과 컬럼 매핑 규칙을 기준으로 처리합니다.</p>
     */
    @PrePersist
    protected void onCreate() {
        if (this.enabled == null) {
            this.enabled = Boolean.FALSE;
        }
    }

    // =========================================================================
    // Static Factory
    // =========================================================================

    /**
     * 신규 엔티티 생성 팩토리
     * - Unique Key(model_key, report_id)를 기반으로 초기화한다.
     */
    public static TcModelReportIdEntity newEntity(long modelKey, String reportId) {
        if (modelKey <= 0) {
            throw new IllegalArgumentException("modelKey must be > 0");
        }
        if (reportId == null || reportId.isBlank()) {
            throw new IllegalArgumentException("reportId must not be null/blank");
        }

        TcModelReportIdEntity e = new TcModelReportIdEntity();
        e.setModelKey(modelKey);
        e.setReportId(reportId);
        return e;
    }

    // =========================================================================
    // Getters & Setters
    // =========================================================================

    
    /**
     * DB JPA 계층의 현재 값을 조회합니다.
     *
     * <p>엔티티 생명주기 콜백과 컬럼 매핑 규칙을 기준으로 처리합니다.</p>
     * @return DB JPA 계층 처리 결과
     */
    public Long getReportKey() {
        return reportKey;
    }

    
    /**
     * DB JPA 계층 설정 값을 반영합니다.
     *
     * <p>엔티티 생명주기 콜백과 컬럼 매핑 규칙을 기준으로 처리합니다.</p>
     * @param reportKey 대상 키 값
     */
    public void setReportKey(Long reportKey) {
        this.reportKey = reportKey;
    }

    
    /**
     * DB JPA 계층의 현재 값을 조회합니다.
     *
     * <p>엔티티 생명주기 콜백과 컬럼 매핑 규칙을 기준으로 처리합니다.</p>
     * @return DB JPA 계층 처리 결과
     */
    public Long getModelKey() {
        return modelKey;
    }

    
    /**
     * DB JPA 계층 설정 값을 반영합니다.
     *
     * <p>엔티티 생명주기 콜백과 컬럼 매핑 규칙을 기준으로 처리합니다.</p>
     * @param modelKey 대상 키 값
     */
    public void setModelKey(Long modelKey) {
        this.modelKey = modelKey;
    }

    
    /**
     * DB JPA 계층의 현재 값을 조회합니다.
     *
     * <p>엔티티 생명주기 콜백과 컬럼 매핑 규칙을 기준으로 처리합니다.</p>
     * @return DB JPA 계층 처리 결과
     */
    public String getReportId() {
        return reportId;
    }

    
    /**
     * DB JPA 계층 설정 값을 반영합니다.
     *
     * <p>엔티티 생명주기 콜백과 컬럼 매핑 규칙을 기준으로 처리합니다.</p>
     * @param reportId DB JPA 계층 처리에 사용하는 입력 값
     */
    public void setReportId(String reportId) {
        this.reportId = reportId;
    }

    
    /**
     * DB JPA 계층의 현재 값을 조회합니다.
     *
     * <p>엔티티 생명주기 콜백과 컬럼 매핑 규칙을 기준으로 처리합니다.</p>
     * @return DB JPA 계층 처리 결과
     */
    public String getVariableId() {
        return variableId;
    }

    
    /**
     * DB JPA 계층 설정 값을 반영합니다.
     *
     * <p>엔티티 생명주기 콜백과 컬럼 매핑 규칙을 기준으로 처리합니다.</p>
     * @param variableId DB JPA 계층 처리에 사용하는 입력 값
     */
    public void setVariableId(String variableId) {
        this.variableId = variableId;
    }

    
    /**
     * DB JPA 계층의 현재 값을 조회합니다.
     *
     * <p>엔티티 생명주기 콜백과 컬럼 매핑 규칙을 기준으로 처리합니다.</p>
     * @return 처리 성공 여부
     */
    public Boolean getEnabled() {
        return enabled;
    }

    
    /**
     * DB JPA 계층 설정 값을 반영합니다.
     *
     * <p>엔티티 생명주기 콜백과 컬럼 매핑 규칙을 기준으로 처리합니다.</p>
     * @param enabled DB JPA 계층 처리에 사용하는 입력 값
     */
    public void setEnabled(Boolean enabled) {
        this.enabled = enabled;
    }
}
