package com.nori.tc.db.jpa.common.entity.model;

import com.nori.tc.db.jpa.common.entity.base.AbstractUpdatedEntity;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import jakarta.persistence.UniqueConstraint;

/**
 * tc_model_workflow 테이블 매핑 엔티티.
 *
 * [DB 스키마]
 * - workflow_key      : bigint generated by default as identity (PK)
 * - model_version_key         : bigint NOT NULL (tc_model FK, ON DELETE CASCADE)
 * - workflow_name     : varchar(1000) NOT NULL
 * - message_name      : varchar(1000) NOT NULL
 * - event_id          : varchar(200) NULL
 * - transaction_id    : varchar(2000) NULL
 * - workflow_filter   : varchar(4000) NULL
 * - action_name       : varchar(200) NOT NULL
 * - action_data_index : varchar(4000) NULL
 * - updated_at        : timestamptz NOT NULL (AbstractUpdatedEntity 상속)
 * - Constraints       : UNIQUE (model_version_key, workflow_name, message_name)
 *
 * [설계 포인트]
 * 1. MapStruct 호환성:
 * - public 생성자를 제공하여 Mapper가 객체를 생성할 수 있게 합니다.
 *
 * 2. Identity Strategy:
 * - PK(workflow_key)는 DB 자동 생성(Identity)을 따릅니다.
 */
@Entity
@Table(
        name = "tc_model_workflow",
        uniqueConstraints = {
                @UniqueConstraint(
                        name = "uk_tc_model_workflow_model_version_key_workflow_name_message_name",
                        columnNames = {"model_version_key", "workflow_name", "message_name"}
                )
        }
)
public class TcModelWorkflowEntity extends AbstractUpdatedEntity {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "workflow_key", nullable = false)
    private Long workflowKey;

    @Column(name = "model_version_key", nullable = false)
    private Long modelVersionKey;

    @Column(name = "workflow_name", length = 1000, nullable = false)
    private String workflowName;

    @Column(name = "message_name", length = 1000, nullable = false)
    private String messageName;

    @Column(name = "event_id", length = 200)
    private String eventId;

    @Column(name = "transaction_id", length = 2000)
    private String transactionId;

    @Column(name = "workflow_filter", length = 4000)
    private String workflowFilter;

    @Column(name = "action_name", length = 200, nullable = false)
    private String actionName;

    @Column(name = "action_data_index", length = 4000)
    private String actionDataIndex;

    // =========================================================================
    // Constructors (MapStruct & JPA)
    // =========================================================================

    /**
     * 기본 생성자 (필수)
     */
    public TcModelWorkflowEntity() {
    }

    /**
     * 전체 인자 생성자
     */
    public TcModelWorkflowEntity(
            Long workflowKey,
            Long modelVersionKey,
            String workflowName,
            String messageName,
            String eventId,
            String transactionId,
            String workflowFilter,
            String actionName,
            String actionDataIndex
    ) {
        this.workflowKey = workflowKey;
        this.modelVersionKey = modelVersionKey;
        this.workflowName = workflowName;
        this.messageName = messageName;
        this.eventId = eventId;
        this.transactionId = transactionId;
        this.workflowFilter = workflowFilter;
        this.actionName = actionName;
        this.actionDataIndex = actionDataIndex;
    }

    // =========================================================================
    // Static Factory
    // =========================================================================

    
    /**
     * DB JPA 계층 규약에 맞게 데이터를 변환/구성합니다.
     *
     * <p>엔티티 생명주기 콜백과 컬럼 매핑 규칙을 기준으로 처리합니다.</p>
     * @param modelVersionKey 대상 키 값
     * @param workflowName DB JPA 계층 처리에 사용하는 입력 값
     * @param messageName 처리할 원본 데이터
     * @return DB JPA 계층 처리 결과
     */
    public static TcModelWorkflowEntity newEntity(long modelVersionKey, String workflowName, String messageName) {
        if (modelVersionKey <= 0) {
            throw new IllegalArgumentException("modelVersionKey must be > 0");
        }
        if (workflowName == null || workflowName.isBlank()) {
            throw new IllegalArgumentException("workflowName must not be null/blank");
        }
        if (messageName == null || messageName.isBlank()) {
            throw new IllegalArgumentException("messageName must not be null/blank");
        }
        TcModelWorkflowEntity e = new TcModelWorkflowEntity();
        e.setModelVersionKey(modelVersionKey);
        e.setWorkflowName(workflowName);
        e.setMessageName(messageName);
        return e;
    }

    // =========================================================================
    // Getters & Setters
    // =========================================================================

    
    /**
     * DB JPA 계층의 현재 값을 조회합니다.
     *
     * <p>엔티티 생명주기 콜백과 컬럼 매핑 규칙을 기준으로 처리합니다.</p>
     * @return DB JPA 계층 처리 결과
     */
    public Long getWorkflowKey() {
        return workflowKey;
    }

    
    /**
     * DB JPA 계층 설정 값을 반영합니다.
     *
     * <p>엔티티 생명주기 콜백과 컬럼 매핑 규칙을 기준으로 처리합니다.</p>
     * @param workflowKey 대상 키 값
     */
    public void setWorkflowKey(Long workflowKey) {
        this.workflowKey = workflowKey;
    }

    
    /**
     * DB JPA 계층의 현재 값을 조회합니다.
     *
     * <p>엔티티 생명주기 콜백과 컬럼 매핑 규칙을 기준으로 처리합니다.</p>
     * @return DB JPA 계층 처리 결과
     */
    public Long getModelVersionKey() {
        return modelVersionKey;
    }

    
    /**
     * DB JPA 계층 설정 값을 반영합니다.
     *
     * <p>엔티티 생명주기 콜백과 컬럼 매핑 규칙을 기준으로 처리합니다.</p>
     * @param modelVersionKey 대상 키 값
     */
    public void setModelVersionKey(Long modelVersionKey) {
        this.modelVersionKey = modelVersionKey;
    }

    
    /**
     * DB JPA 계층의 현재 값을 조회합니다.
     *
     * <p>엔티티 생명주기 콜백과 컬럼 매핑 규칙을 기준으로 처리합니다.</p>
     * @return DB JPA 계층 처리 결과
     */
    public String getWorkflowName() {
        return workflowName;
    }

    
    /**
     * DB JPA 계층 설정 값을 반영합니다.
     *
     * <p>엔티티 생명주기 콜백과 컬럼 매핑 규칙을 기준으로 처리합니다.</p>
     * @param workflowName DB JPA 계층 처리에 사용하는 입력 값
     */
    public void setWorkflowName(String workflowName) {
        this.workflowName = workflowName;
    }

    
    /**
     * DB JPA 계층의 현재 값을 조회합니다.
     *
     * <p>엔티티 생명주기 콜백과 컬럼 매핑 규칙을 기준으로 처리합니다.</p>
     * @return DB JPA 계층 처리 결과
     */
    public String getMessageName() {
        return messageName;
    }

    
    /**
     * DB JPA 계층 설정 값을 반영합니다.
     *
     * <p>엔티티 생명주기 콜백과 컬럼 매핑 규칙을 기준으로 처리합니다.</p>
     * @param messageName 처리할 원본 데이터
     */
    public void setMessageName(String messageName) {
        this.messageName = messageName;
    }

    
    /**
     * DB JPA 계층의 현재 값을 조회합니다.
     *
     * <p>엔티티 생명주기 콜백과 컬럼 매핑 규칙을 기준으로 처리합니다.</p>
     * @return DB JPA 계층 처리 결과
     */
    public String getEventId() {
        return eventId;
    }

    
    /**
     * DB JPA 계층 설정 값을 반영합니다.
     *
     * <p>엔티티 생명주기 콜백과 컬럼 매핑 규칙을 기준으로 처리합니다.</p>
     * @param eventId 처리할 이벤트 정보
     */
    public void setEventId(String eventId) {
        this.eventId = eventId;
    }

    
    /**
     * DB JPA 계층의 현재 값을 조회합니다.
     *
     * <p>엔티티 생명주기 콜백과 컬럼 매핑 규칙을 기준으로 처리합니다.</p>
     * @return DB JPA 계층 처리 결과
     */
    public String getTransactionId() {
        return transactionId;
    }

    
    /**
     * DB JPA 계층 설정 값을 반영합니다.
     *
     * <p>엔티티 생명주기 콜백과 컬럼 매핑 규칙을 기준으로 처리합니다.</p>
     * @param transactionId DB JPA 계층 처리에 사용하는 입력 값
     */
    public void setTransactionId(String transactionId) {
        this.transactionId = transactionId;
    }

    
    /**
     * DB JPA 계층의 현재 값을 조회합니다.
     *
     * <p>엔티티 생명주기 콜백과 컬럼 매핑 규칙을 기준으로 처리합니다.</p>
     * @return DB JPA 계층 처리 결과
     */
    public String getWorkflowFilter() {
        return workflowFilter;
    }

    
    /**
     * DB JPA 계층 설정 값을 반영합니다.
     *
     * <p>엔티티 생명주기 콜백과 컬럼 매핑 규칙을 기준으로 처리합니다.</p>
     * @param workflowFilter DB JPA 계층 처리에 사용하는 입력 값
     */
    public void setWorkflowFilter(String workflowFilter) {
        this.workflowFilter = workflowFilter;
    }

    
    /**
     * DB JPA 계층의 현재 값을 조회합니다.
     *
     * <p>엔티티 생명주기 콜백과 컬럼 매핑 규칙을 기준으로 처리합니다.</p>
     * @return DB JPA 계층 처리 결과
     */
    public String getActionName() {
        return actionName;
    }

    
    /**
     * DB JPA 계층 설정 값을 반영합니다.
     *
     * <p>엔티티 생명주기 콜백과 컬럼 매핑 규칙을 기준으로 처리합니다.</p>
     * @param actionName DB JPA 계층 처리에 사용하는 입력 값
     */
    public void setActionName(String actionName) {
        this.actionName = actionName;
    }

    
    /**
     * DB JPA 계층의 현재 값을 조회합니다.
     *
     * <p>엔티티 생명주기 콜백과 컬럼 매핑 규칙을 기준으로 처리합니다.</p>
     * @return DB JPA 계층 처리 결과
     */
    public String getActionDataIndex() {
        return actionDataIndex;
    }

    
    /**
     * DB JPA 계층 설정 값을 반영합니다.
     *
     * <p>엔티티 생명주기 콜백과 컬럼 매핑 규칙을 기준으로 처리합니다.</p>
     * @param actionDataIndex 처리할 원본 데이터
     */
    public void setActionDataIndex(String actionDataIndex) {
        this.actionDataIndex = actionDataIndex;
    }
}
