package com.nori.tc.db.jpa.common.entity.model;

import com.nori.tc.db.domain.common.VariableIdType;
import com.nori.tc.db.jpa.common.entity.base.AbstractUpdatedEntity;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import jakarta.persistence.UniqueConstraint;

/**
 * tc_model_variableid 테이블 매핑 엔티티.
 *
 * [DB 스키마]
 * - variable_key     : bigint generated by default as identity (PK)
 * - model_key        : bigint NOT NULL (FK -> tc_model.model_key)
 * - variable_id      : varchar(100) NOT NULL
 * - variable_id_type : varchar(10) NOT NULL default 'SVID'
 * - description      : varchar(2000)
 * - updated_at       : timestamptz NOT NULL
 * - Constraints      : UNIQUE (model_key, variable_id_type, variable_id)
 * - Check            : variable_id_type IN (SVID, DVID, ECID, CEID)
 *
 * [설계 포인트]
 * 1. Unique Key 기반 Upsert:
 * - model_key + variable_id_type + variable_id 조합을 기준으로 upsert한다.
 * - variable_key는 DB가 생성한다.
 */
@Entity
@Table(
        name = "tc_model_variableid",
        uniqueConstraints = {
                @UniqueConstraint(name = "uk_tc_model_variableid_model_key_type_variable_id",
                        columnNames = {"model_key", "variable_id_type", "variable_id"})
        }
)
public class TcModelVariableIdEntity extends AbstractUpdatedEntity {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "variable_key", nullable = false)
    private Long variableKey;

    @Column(name = "model_key", nullable = false)
    private Long modelKey;

    @Column(name = "variable_id", length = 100, nullable = false)
    private String variableId;

    @Enumerated(EnumType.STRING)
    @Column(name = "variable_id_type", length = 10, nullable = false)
    private VariableIdType variableIdType;

    @Column(name = "description", length = 2000)
    private String description;

    // =========================================================================
    // Constructors (MapStruct & JPA)
    // =========================================================================

    /**
     * 기본 생성자 (필수)
     */
    public TcModelVariableIdEntity() {
    }

    /**
     * 전체 인자 생성자
     */
    public TcModelVariableIdEntity(
            Long variableKey,
            Long modelKey,
            String variableId,
            VariableIdType variableIdType,
            String description
    ) {
        this.variableKey = variableKey;
        this.modelKey = modelKey;
        this.variableId = variableId;
        this.variableIdType = variableIdType;
        this.description = description;
    }

    // =========================================================================
    // Static Factory
    // =========================================================================

    public static TcModelVariableIdEntity newEntity(long modelKey, VariableIdType variableIdType, String variableId) {
        if (modelKey <= 0) {
            throw new IllegalArgumentException("modelKey must be > 0");
        }
        if (variableIdType == null) {
            throw new IllegalArgumentException("variableIdType must not be null");
        }
        if (variableId == null || variableId.isBlank()) {
            throw new IllegalArgumentException("variableId must not be null/blank");
        }

        TcModelVariableIdEntity e = new TcModelVariableIdEntity();
        e.setModelKey(modelKey);
        e.setVariableIdType(variableIdType);
        e.setVariableId(variableId);
        return e;
    }

    // =========================================================================
    // Getters & Setters
    // =========================================================================

    public Long getVariableKey() {
        return variableKey;
    }

    public void setVariableKey(Long variableKey) {
        this.variableKey = variableKey;
    }

    public Long getModelKey() {
        return modelKey;
    }

    public void setModelKey(Long modelKey) {
        this.modelKey = modelKey;
    }

    public String getVariableId() {
        return variableId;
    }

    public void setVariableId(String variableId) {
        this.variableId = variableId;
    }

    public VariableIdType getVariableIdType() {
        return variableIdType;
    }

    public void setVariableIdType(VariableIdType variableIdType) {
        this.variableIdType = variableIdType;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }
}
