package com.nori.tc.db.jpa.common.entity.model;

import com.nori.tc.db.domain.common.model.VariableIdType;
import com.nori.tc.db.jpa.common.entity.base.AbstractUpdatedEntity;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import jakarta.persistence.UniqueConstraint;

/**
 * tc_model_variableid 테이블 매핑 엔티티.
 *
 * [DB 스키마]
 * - variable_key     : bigint generated by default as identity (PK)
 * - model_version_key        : bigint NOT NULL (FK -> tc_model_version.model_version_key)
 * - variable_id      : varchar(1000) NOT NULL
 * - variable_id_type : varchar(10) NOT NULL default 'SVID'
 * - description      : varchar(2000)
 * - updated_at       : timestamptz NOT NULL
 * - Constraints      : UNIQUE (model_version_key, variable_id_type, variable_id)
 * - Check            : variable_id_type IN (SVID, DVID, ECID, CEID)
 *
 * [설계 포인트]
 * 1. Unique Key 기반 Upsert:
 * - model_version_key + variable_id_type + variable_id 조합을 기준으로 upsert한다.
 * - variable_key는 DB가 생성한다.
 */
@Entity
@Table(
        name = "tc_model_variableid",
        uniqueConstraints = {
                @UniqueConstraint(name = "uk_tc_model_variableid_model_version_key_type_variable_id",
                        columnNames = {"model_version_key", "variable_id_type", "variable_id"})
        }
)
public class TcModelVariableIdEntity extends AbstractUpdatedEntity {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "variable_key", nullable = false)
    private Long variableKey;

    @Column(name = "model_version_key", nullable = false)
    private Long modelVersionKey;

    @Column(name = "variable_id", length = 1000, nullable = false)
    private String variableId;

    @Enumerated(EnumType.STRING)
    @Column(name = "variable_id_type", length = 10, nullable = false)
    private VariableIdType variableIdType;

    @Column(name = "description", length = 2000)
    private String description;

    // =========================================================================
    // Constructors (MapStruct & JPA)
    // =========================================================================

    /**
     * 기본 생성자 (필수)
     */
    public TcModelVariableIdEntity() {
    }

    /**
     * 전체 인자 생성자
     */
    public TcModelVariableIdEntity(
            Long variableKey,
            Long modelVersionKey,
            String variableId,
            VariableIdType variableIdType,
            String description
    ) {
        this.variableKey = variableKey;
        this.modelVersionKey = modelVersionKey;
        this.variableId = variableId;
        this.variableIdType = variableIdType;
        this.description = description;
    }

    // =========================================================================
    // Static Factory
    // =========================================================================

    
    /**
     * DB JPA 계층 규약에 맞게 데이터를 변환/구성합니다.
     *
     * <p>엔티티 생명주기 콜백과 컬럼 매핑 규칙을 기준으로 처리합니다.</p>
     * @param modelVersionKey 대상 키 값
     * @param variableIdType DB JPA 계층 처리에 사용하는 입력 값
     * @param variableId DB JPA 계층 처리에 사용하는 입력 값
     * @return DB JPA 계층 처리 결과
     */
    public static TcModelVariableIdEntity newEntity(long modelVersionKey, VariableIdType variableIdType, String variableId) {
        if (modelVersionKey <= 0) {
            throw new IllegalArgumentException("modelVersionKey must be > 0");
        }
        if (variableIdType == null) {
            throw new IllegalArgumentException("variableIdType must not be null");
        }
        if (variableId == null || variableId.isBlank()) {
            throw new IllegalArgumentException("variableId must not be null/blank");
        }

        TcModelVariableIdEntity e = new TcModelVariableIdEntity();
        e.setModelVersionKey(modelVersionKey);
        e.setVariableIdType(variableIdType);
        e.setVariableId(variableId);
        return e;
    }

    // =========================================================================
    // Getters & Setters
    // =========================================================================

    
    /**
     * DB JPA 계층의 현재 값을 조회합니다.
     *
     * <p>엔티티 생명주기 콜백과 컬럼 매핑 규칙을 기준으로 처리합니다.</p>
     * @return DB JPA 계층 처리 결과
     */
    public Long getVariableKey() {
        return variableKey;
    }

    
    /**
     * DB JPA 계층 설정 값을 반영합니다.
     *
     * <p>엔티티 생명주기 콜백과 컬럼 매핑 규칙을 기준으로 처리합니다.</p>
     * @param variableKey 대상 키 값
     */
    public void setVariableKey(Long variableKey) {
        this.variableKey = variableKey;
    }

    
    /**
     * DB JPA 계층의 현재 값을 조회합니다.
     *
     * <p>엔티티 생명주기 콜백과 컬럼 매핑 규칙을 기준으로 처리합니다.</p>
     * @return DB JPA 계층 처리 결과
     */
    public Long getModelVersionKey() {
        return modelVersionKey;
    }

    
    /**
     * DB JPA 계층 설정 값을 반영합니다.
     *
     * <p>엔티티 생명주기 콜백과 컬럼 매핑 규칙을 기준으로 처리합니다.</p>
     * @param modelVersionKey 대상 키 값
     */
    public void setModelVersionKey(Long modelVersionKey) {
        this.modelVersionKey = modelVersionKey;
    }

    
    /**
     * DB JPA 계층의 현재 값을 조회합니다.
     *
     * <p>엔티티 생명주기 콜백과 컬럼 매핑 규칙을 기준으로 처리합니다.</p>
     * @return DB JPA 계층 처리 결과
     */
    public String getVariableId() {
        return variableId;
    }

    
    /**
     * DB JPA 계층 설정 값을 반영합니다.
     *
     * <p>엔티티 생명주기 콜백과 컬럼 매핑 규칙을 기준으로 처리합니다.</p>
     * @param variableId DB JPA 계층 처리에 사용하는 입력 값
     */
    public void setVariableId(String variableId) {
        this.variableId = variableId;
    }

    
    /**
     * DB JPA 계층의 현재 값을 조회합니다.
     *
     * <p>엔티티 생명주기 콜백과 컬럼 매핑 규칙을 기준으로 처리합니다.</p>
     * @return DB JPA 계층 처리 결과
     */
    public VariableIdType getVariableIdType() {
        return variableIdType;
    }

    
    /**
     * DB JPA 계층 설정 값을 반영합니다.
     *
     * <p>엔티티 생명주기 콜백과 컬럼 매핑 규칙을 기준으로 처리합니다.</p>
     * @param variableIdType DB JPA 계층 처리에 사용하는 입력 값
     */
    public void setVariableIdType(VariableIdType variableIdType) {
        this.variableIdType = variableIdType;
    }

    
    /**
     * DB JPA 계층의 현재 값을 조회합니다.
     *
     * <p>엔티티 생명주기 콜백과 컬럼 매핑 규칙을 기준으로 처리합니다.</p>
     * @return DB JPA 계층 처리 결과
     */
    public String getDescription() {
        return description;
    }

    
    /**
     * DB JPA 계층 설정 값을 반영합니다.
     *
     * <p>엔티티 생명주기 콜백과 컬럼 매핑 규칙을 기준으로 처리합니다.</p>
     * @param description DB JPA 계층 처리에 사용하는 입력 값
     */
    public void setDescription(String description) {
        this.description = description;
    }
}
