package com.nori.tc.db.jpa.common.entity.user;

import java.time.OffsetDateTime;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.PrePersist;
import jakarta.persistence.Table;
import jakarta.persistence.UniqueConstraint;

/**
 * tc_user_group_member 테이블 매핑 엔티티.
 *
 * <p>
 * [DB 스키마]
 * - ugm_key    : bigint generated by default as identity (PK)
 * - user_pk    : bigint NOT NULL
 * - group_id   : bigint NOT NULL
 * - granted_at : timestamptz NOT NULL default CURRENT_TIMESTAMP
 * - granted_by : varchar(50) NULL
 * - Constraints: UNIQUE (user_pk, group_id)
 * </p>
 *
 * <p>
 * [설계 포인트]
 * 1) MapStruct 호환성:
 * - public 기본 생성자와 전체 인자 생성자를 제공한다.
 *
 * 2) 기본값 방어:
 * - granted_at이 null이면 현재 시각으로 보정한다.
 * </p>
 */
@Entity
@Table(
        name = "tc_user_group_member",
        uniqueConstraints = {
                @UniqueConstraint(
                        name = "uk_tc_user_group_member_user_pk_group_id",
                        columnNames = {"user_pk", "group_id"}
                )
        }
)
public class TcUserGroupMemberEntity {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "ugm_key", nullable = false)
    private Long ugmKey;

    @Column(name = "user_pk", nullable = false)
    private Long userPk;

    @Column(name = "group_id", nullable = false)
    private Long groupId;

    @Column(name = "granted_at", nullable = false)
    private OffsetDateTime grantedAt;

    @Column(name = "granted_by", length = 50)
    private String grantedBy;

    // =========================================================================
    // Constructors (MapStruct & JPA)
    // =========================================================================

    /**
     * 기본 생성자 (필수)
     */
    public TcUserGroupMemberEntity() {
    }

    /**
     * 전체 인자 생성자
     */
    public TcUserGroupMemberEntity(
            Long ugmKey,
            Long userPk,
            Long groupId,
            OffsetDateTime grantedAt,
            String grantedBy
    ) {
        this.ugmKey = ugmKey;
        this.userPk = userPk;
        this.groupId = groupId;
        this.grantedAt = grantedAt;
        this.grantedBy = grantedBy;
    }

    // =========================================================================
    // Static Factory
    // =========================================================================

    /**
     * 유니크 키(user_pk, group_id) 기반 신규 엔티티 생성.
     */
    public static TcUserGroupMemberEntity newEntity(long userPk, long groupId) {
        if (userPk <= 0) {
            throw new IllegalArgumentException("userPk must be > 0");
        }
        if (groupId <= 0) {
            throw new IllegalArgumentException("groupId must be > 0");
        }
        TcUserGroupMemberEntity e = new TcUserGroupMemberEntity();
        e.setUserPk(userPk);
        e.setGroupId(groupId);
        return e;
    }

    // =========================================================================
    // Lifecycle
    // =========================================================================

    /**
     * DB Insert 전 기본값 방어.
     * - granted_at이 null이면 현재 시각으로 보정한다.
     */
    @PrePersist
    private void applyDefaults() {
        if (this.grantedAt == null) {
            this.grantedAt = OffsetDateTime.now();
        }
    }

    // =========================================================================
    // Getters & Setters
    // =========================================================================

    
    /**
     * DB JPA 계층의 현재 값을 조회합니다.
     *
     * <p>엔티티 생명주기 콜백과 컬럼 매핑 규칙을 기준으로 처리합니다.</p>
     * @return DB JPA 계층 처리 결과
     */
    public Long getUgmKey() {
        return ugmKey;
    }

    
    /**
     * DB JPA 계층 설정 값을 반영합니다.
     *
     * <p>엔티티 생명주기 콜백과 컬럼 매핑 규칙을 기준으로 처리합니다.</p>
     * @param ugmKey 대상 키 값
     */
    public void setUgmKey(Long ugmKey) {
        this.ugmKey = ugmKey;
    }

    
    /**
     * DB JPA 계층의 현재 값을 조회합니다.
     *
     * <p>엔티티 생명주기 콜백과 컬럼 매핑 규칙을 기준으로 처리합니다.</p>
     * @return DB JPA 계층 처리 결과
     */
    public Long getUserPk() {
        return userPk;
    }

    
    /**
     * DB JPA 계층 설정 값을 반영합니다.
     *
     * <p>엔티티 생명주기 콜백과 컬럼 매핑 규칙을 기준으로 처리합니다.</p>
     * @param userPk DB JPA 계층 처리에 사용하는 입력 값
     */
    public void setUserPk(Long userPk) {
        this.userPk = userPk;
    }

    
    /**
     * DB JPA 계층의 현재 값을 조회합니다.
     *
     * <p>엔티티 생명주기 콜백과 컬럼 매핑 규칙을 기준으로 처리합니다.</p>
     * @return DB JPA 계층 처리 결과
     */
    public Long getGroupId() {
        return groupId;
    }

    
    /**
     * DB JPA 계층 설정 값을 반영합니다.
     *
     * <p>엔티티 생명주기 콜백과 컬럼 매핑 규칙을 기준으로 처리합니다.</p>
     * @param groupId DB JPA 계층 처리에 사용하는 입력 값
     */
    public void setGroupId(Long groupId) {
        this.groupId = groupId;
    }

    
    /**
     * DB JPA 계층의 현재 값을 조회합니다.
     *
     * <p>엔티티 생명주기 콜백과 컬럼 매핑 규칙을 기준으로 처리합니다.</p>
     * @return DB JPA 계층 처리 결과
     */
    public OffsetDateTime getGrantedAt() {
        return grantedAt;
    }

    
    /**
     * DB JPA 계층 설정 값을 반영합니다.
     *
     * <p>엔티티 생명주기 콜백과 컬럼 매핑 규칙을 기준으로 처리합니다.</p>
     * @param grantedAt DB JPA 계층 처리에 사용하는 입력 값
     */
    public void setGrantedAt(OffsetDateTime grantedAt) {
        this.grantedAt = grantedAt;
    }

    
    /**
     * DB JPA 계층의 현재 값을 조회합니다.
     *
     * <p>엔티티 생명주기 콜백과 컬럼 매핑 규칙을 기준으로 처리합니다.</p>
     * @return DB JPA 계층 처리 결과
     */
    public String getGrantedBy() {
        return grantedBy;
    }

    
    /**
     * DB JPA 계층 설정 값을 반영합니다.
     *
     * <p>엔티티 생명주기 콜백과 컬럼 매핑 규칙을 기준으로 처리합니다.</p>
     * @param grantedBy DB JPA 계층 처리에 사용하는 입력 값
     */
    public void setGrantedBy(String grantedBy) {
        this.grantedBy = grantedBy;
    }
}
