package com.nori.tc.db.jpa.common.entity.user;

import java.time.OffsetDateTime;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.PrePersist;
import jakarta.persistence.PreUpdate;
import jakarta.persistence.Table;
import jakarta.persistence.UniqueConstraint;

/**
 * tc_user_group_permission 테이블 매핑 엔티티.
 *
 * <pre>
 * [DB 스키마]
 * - ugp_key    : bigint generated by default as identity (PK)
 * - group_id   : bigint NOT NULL (FK -> tc_user_group.group_id)
 * - perm_id    : bigint NOT NULL (FK -> tc_ui_permission.perm_id)
 * - granted_at : timestamptz NOT NULL (default CURRENT_TIMESTAMP)
 * - granted_by : varchar(50) NULL
 * - Constraints: UNIQUE (group_id, perm_id)
 * </pre>
 *
 * <p>
 * [설계 포인트]
 * <ul>
 * <li>PK는 DB IDENTITY를 사용하며 JPA는 GenerationType.IDENTITY로 매핑합니다.</li>
 * <li>granted_at은 생성/갱신 시점에 현재 시각으로 설정되도록 엔티티 레벨에서 보정합니다.</li>
 * <li>MapStruct 호환성을 위해 public 생성자를 제공합니다.</li>
 * </ul>
 * </p>
 */
@Entity
@Table(
        name = "tc_user_group_permission",
        uniqueConstraints = {
                @UniqueConstraint(name = "uk_tc_user_group_permission_group_id_perm_id", columnNames = {"group_id", "perm_id"})
        }
)
public class TcUserGroupPermissionEntity {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "ugp_key", nullable = false)
    private Long ugpKey;

    @Column(name = "group_id", nullable = false)
    private Long groupId;

    @Column(name = "perm_id", nullable = false)
    private Long permId;

    @Column(name = "granted_at", nullable = false)
    private OffsetDateTime grantedAt;

    @Column(name = "granted_by", length = 50)
    private String grantedBy;

    // =========================================================================
    // Constructors (MapStruct & JPA)
    // =========================================================================

    /**
     * 기본 생성자 (필수)
     * - JPA 프록시 생성용
     * - MapStruct 타겟 객체 생성용 (public 필수)
     */
    public TcUserGroupPermissionEntity() {
    }

    /**
     * 전체 인자 생성자
     * - MapStruct가 Domain -> Entity 변환 시 모든 필드를 한 번에 주입할 때 사용
     */
    public TcUserGroupPermissionEntity(Long ugpKey, Long groupId, Long permId, OffsetDateTime grantedAt, String grantedBy) {
        this.ugpKey = ugpKey;
        this.groupId = groupId;
        this.permId = permId;
        this.grantedAt = grantedAt;
        this.grantedBy = grantedBy;
    }

    // =========================================================================
    // Lifecycle hooks
    // =========================================================================

    
    /**
     * DB JPA 계층 감사/상태 필드를 최신 값으로 갱신합니다.
     *
     * <p>엔티티 생명주기 콜백과 컬럼 매핑 규칙을 기준으로 처리합니다.</p>
     */
    @PrePersist
    protected void onCreate() {
        if (this.grantedAt == null) {
            this.grantedAt = OffsetDateTime.now();
        }
    }

    
    /**
     * DB JPA 계층 감사/상태 필드를 최신 값으로 갱신합니다.
     *
     * <p>엔티티 생명주기 콜백과 컬럼 매핑 규칙을 기준으로 처리합니다.</p>
     */
    @PreUpdate
    protected void onUpdate() {
        this.grantedAt = OffsetDateTime.now();
    }

    // =========================================================================
    // Static Factory
    // =========================================================================

    
    /**
     * DB JPA 계층 규약에 맞게 데이터를 변환/구성합니다.
     *
     * <p>엔티티 생명주기 콜백과 컬럼 매핑 규칙을 기준으로 처리합니다.</p>
     * @param groupId DB JPA 계층 처리에 사용하는 입력 값
     * @param permId DB JPA 계층 처리에 사용하는 입력 값
     * @return DB JPA 계층 처리 결과
     */
    public static TcUserGroupPermissionEntity newEntity(long groupId, long permId) {
        if (groupId <= 0) {
            throw new IllegalArgumentException("groupId must be > 0");
        }
        if (permId <= 0) {
            throw new IllegalArgumentException("permId must be > 0");
        }
        TcUserGroupPermissionEntity entity = new TcUserGroupPermissionEntity();
        entity.setGroupId(groupId);
        entity.setPermId(permId);
        return entity;
    }

    // =========================================================================
    // Getters & Setters
    // =========================================================================

    
    /**
     * DB JPA 계층의 현재 값을 조회합니다.
     *
     * <p>엔티티 생명주기 콜백과 컬럼 매핑 규칙을 기준으로 처리합니다.</p>
     * @return DB JPA 계층 처리 결과
     */
    public Long getUgpKey() {
        return ugpKey;
    }

    
    /**
     * DB JPA 계층 설정 값을 반영합니다.
     *
     * <p>엔티티 생명주기 콜백과 컬럼 매핑 규칙을 기준으로 처리합니다.</p>
     * @param ugpKey 대상 키 값
     */
    public void setUgpKey(Long ugpKey) {
        this.ugpKey = ugpKey;
    }

    
    /**
     * DB JPA 계층의 현재 값을 조회합니다.
     *
     * <p>엔티티 생명주기 콜백과 컬럼 매핑 규칙을 기준으로 처리합니다.</p>
     * @return DB JPA 계층 처리 결과
     */
    public Long getGroupId() {
        return groupId;
    }

    
    /**
     * DB JPA 계층 설정 값을 반영합니다.
     *
     * <p>엔티티 생명주기 콜백과 컬럼 매핑 규칙을 기준으로 처리합니다.</p>
     * @param groupId DB JPA 계층 처리에 사용하는 입력 값
     */
    public void setGroupId(Long groupId) {
        this.groupId = groupId;
    }

    
    /**
     * DB JPA 계층의 현재 값을 조회합니다.
     *
     * <p>엔티티 생명주기 콜백과 컬럼 매핑 규칙을 기준으로 처리합니다.</p>
     * @return DB JPA 계층 처리 결과
     */
    public Long getPermId() {
        return permId;
    }

    
    /**
     * DB JPA 계층 설정 값을 반영합니다.
     *
     * <p>엔티티 생명주기 콜백과 컬럼 매핑 규칙을 기준으로 처리합니다.</p>
     * @param permId DB JPA 계층 처리에 사용하는 입력 값
     */
    public void setPermId(Long permId) {
        this.permId = permId;
    }

    
    /**
     * DB JPA 계층의 현재 값을 조회합니다.
     *
     * <p>엔티티 생명주기 콜백과 컬럼 매핑 규칙을 기준으로 처리합니다.</p>
     * @return DB JPA 계층 처리 결과
     */
    public OffsetDateTime getGrantedAt() {
        return grantedAt;
    }

    
    /**
     * DB JPA 계층 설정 값을 반영합니다.
     *
     * <p>엔티티 생명주기 콜백과 컬럼 매핑 규칙을 기준으로 처리합니다.</p>
     * @param grantedAt DB JPA 계층 처리에 사용하는 입력 값
     */
    public void setGrantedAt(OffsetDateTime grantedAt) {
        this.grantedAt = grantedAt;
    }

    
    /**
     * DB JPA 계층의 현재 값을 조회합니다.
     *
     * <p>엔티티 생명주기 콜백과 컬럼 매핑 규칙을 기준으로 처리합니다.</p>
     * @return DB JPA 계층 처리 결과
     */
    public String getGrantedBy() {
        return grantedBy;
    }

    
    /**
     * DB JPA 계층 설정 값을 반영합니다.
     *
     * <p>엔티티 생명주기 콜백과 컬럼 매핑 규칙을 기준으로 처리합니다.</p>
     * @param grantedBy DB JPA 계층 처리에 사용하는 입력 값
     */
    public void setGrantedBy(String grantedBy) {
        this.grantedBy = grantedBy;
    }
}
