package com.nori.tc.db.jpa.common.entity.user;

import com.nori.tc.db.jpa.common.entity.base.AbstractCreatedUpdatedEntity;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.PrePersist;
import jakarta.persistence.Table;
import jakarta.persistence.UniqueConstraint;

/**
 * tc_user_group 테이블 매핑 엔티티.
 *
 * <p>
 * [DB 스키마]
 * </p>
 * <ul>
 *     <li>group_id    : bigint generated by default as identity (PK)</li>
 *     <li>group_code  : varchar(50) NOT NULL (UNIQUE)</li>
 *     <li>group_name  : varchar(100) NOT NULL</li>
 *     <li>description : varchar(1000)</li>
 *     <li>is_active   : boolean NOT NULL default true</li>
 *     <li>created_at  : timestamptz NOT NULL</li>
 *     <li>updated_at  : timestamptz NOT NULL</li>
 * </ul>
 *
 * <p>
 * [설계 포인트]
 * </p>
 * <ul>
 *     <li>MapStruct 호환성을 위해 public 기본 생성자 및 전체 인자 생성자를 제공합니다.</li>
 *     <li>is_active는 null로 들어오면 true로 보정합니다.</li>
 * </ul>
 */
@Entity
@Table(
        name = "tc_user_group",
        uniqueConstraints = {
                @UniqueConstraint(name = "uk_tc_user_group_group_code", columnNames = {"group_code"})
        }
)
public class TcUserGroupEntity extends AbstractCreatedUpdatedEntity {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "group_id", nullable = false)
    private Long groupId;

    @Column(name = "group_code", length = 50, nullable = false)
    private String groupCode;

    @Column(name = "group_name", length = 100, nullable = false)
    private String groupName;

    @Column(name = "description", length = 1000)
    private String description;

    @Column(name = "is_active", nullable = false)
    private Boolean isActive;

    // =========================================================================
    // Constructors (MapStruct & JPA)
    // =========================================================================

    /**
     * 기본 생성자 (필수)
     */
    public TcUserGroupEntity() {
    }

    /**
     * 전체 인자 생성자
     */
    public TcUserGroupEntity(Long groupId, String groupCode, String groupName, String description, Boolean isActive) {
        this.groupId = groupId;
        this.groupCode = groupCode;
        this.groupName = groupName;
        this.description = description;
        this.isActive = isActive;
    }

    // =========================================================================
    // Static Factory
    // =========================================================================

    /**
     * 신규 그룹 생성용 팩토리.
     *
     * @param groupCode 유니크 그룹 코드
     * @param groupName 그룹명
     * @return 기본값이 적용된 TcUserGroupEntity
     */
    public static TcUserGroupEntity newEntity(String groupCode, String groupName) {
        if (groupCode == null || groupCode.isBlank()) {
            throw new IllegalArgumentException("groupCode must not be null/blank");
        }
        if (groupName == null || groupName.isBlank()) {
            throw new IllegalArgumentException("groupName must not be null/blank");
        }
        TcUserGroupEntity entity = new TcUserGroupEntity();
        entity.setGroupCode(groupCode);
        entity.setGroupName(groupName);
        return entity;
    }

    /**
     * DB Insert 전 데이터 보정.
     * - is_active가 비어있으면 true로 세팅
     */
    @PrePersist
    private void applyDefaults() {
        if (this.isActive == null) {
            this.isActive = Boolean.TRUE;
        }
    }

    // =========================================================================
    // Getters & Setters
    // =========================================================================

    
    /**
     * DB JPA 계층의 현재 값을 조회합니다.
     *
     * <p>엔티티 생명주기 콜백과 컬럼 매핑 규칙을 기준으로 처리합니다.</p>
     * @return DB JPA 계층 처리 결과
     */
    public Long getGroupId() {
        return groupId;
    }

    
    /**
     * DB JPA 계층 설정 값을 반영합니다.
     *
     * <p>엔티티 생명주기 콜백과 컬럼 매핑 규칙을 기준으로 처리합니다.</p>
     * @param groupId DB JPA 계층 처리에 사용하는 입력 값
     */
    public void setGroupId(Long groupId) {
        this.groupId = groupId;
    }

    
    /**
     * DB JPA 계층의 현재 값을 조회합니다.
     *
     * <p>엔티티 생명주기 콜백과 컬럼 매핑 규칙을 기준으로 처리합니다.</p>
     * @return DB JPA 계층 처리 결과
     */
    public String getGroupCode() {
        return groupCode;
    }

    
    /**
     * DB JPA 계층 설정 값을 반영합니다.
     *
     * <p>엔티티 생명주기 콜백과 컬럼 매핑 규칙을 기준으로 처리합니다.</p>
     * @param groupCode DB JPA 계층 처리에 사용하는 입력 값
     */
    public void setGroupCode(String groupCode) {
        this.groupCode = groupCode;
    }

    
    /**
     * DB JPA 계층의 현재 값을 조회합니다.
     *
     * <p>엔티티 생명주기 콜백과 컬럼 매핑 규칙을 기준으로 처리합니다.</p>
     * @return DB JPA 계층 처리 결과
     */
    public String getGroupName() {
        return groupName;
    }

    
    /**
     * DB JPA 계층 설정 값을 반영합니다.
     *
     * <p>엔티티 생명주기 콜백과 컬럼 매핑 규칙을 기준으로 처리합니다.</p>
     * @param groupName DB JPA 계층 처리에 사용하는 입력 값
     */
    public void setGroupName(String groupName) {
        this.groupName = groupName;
    }

    
    /**
     * DB JPA 계층의 현재 값을 조회합니다.
     *
     * <p>엔티티 생명주기 콜백과 컬럼 매핑 규칙을 기준으로 처리합니다.</p>
     * @return DB JPA 계층 처리 결과
     */
    public String getDescription() {
        return description;
    }

    
    /**
     * DB JPA 계층 설정 값을 반영합니다.
     *
     * <p>엔티티 생명주기 콜백과 컬럼 매핑 규칙을 기준으로 처리합니다.</p>
     * @param description DB JPA 계층 처리에 사용하는 입력 값
     */
    public void setDescription(String description) {
        this.description = description;
    }

    
    /**
     * DB JPA 계층의 현재 값을 조회합니다.
     *
     * <p>엔티티 생명주기 콜백과 컬럼 매핑 규칙을 기준으로 처리합니다.</p>
     * @return 처리 성공 여부
     */
    public Boolean getIsActive() {
        return isActive;
    }

    
    /**
     * DB JPA 계층 설정 값을 반영합니다.
     *
     * <p>엔티티 생명주기 콜백과 컬럼 매핑 규칙을 기준으로 처리합니다.</p>
     * @param isActive DB JPA 계층 처리에 사용하는 입력 값
     */
    public void setIsActive(Boolean isActive) {
        this.isActive = isActive;
    }
}
