package com.nori.tc.db.jpa.common.entity.work;

import com.nori.tc.db.jpa.common.entity.base.AbstractUpdatedEntity;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import jakarta.persistence.UniqueConstraint;

/**
 * tc_work_carrier_slot 테이블 매핑 엔티티.
 *
 * [DB 스키마]
 * - carrier_slot_key : bigint generated by default as identity (PK)
 * - work_carrier_key : bigint NOT NULL (FK)
 * - slot_no          : int NOT NULL (check: slot_no >= 1)
 * - slot_state       : varchar(50) NOT NULL
 * - lot_id           : varchar(64)
 * - updated_at       : timestamptz NOT NULL (AbstractUpdatedEntity 상속)
 * - Constraints      : UNIQUE (work_carrier_key, slot_no)
 *
 * [설계 포인트]
 * 1. MapStruct 호환성:
 * - public 생성자를 제공하여 Mapper가 객체를 생성할 수 있게 합니다.
 *
 * 2. Identity Strategy:
 * - PK(carrier_slot_key)는 DB 자동 생성(Identity)을 따릅니다.
 */
@Entity
@Table(
        name = "tc_work_carrier_slot",
        uniqueConstraints = {
                @UniqueConstraint(name = "uk_tc_work_carrier_slot_work_carrier_key_slot_no", columnNames = {"work_carrier_key", "slot_no"})
        }
)
public class TcWorkCarrierSlotEntity extends AbstractUpdatedEntity {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "carrier_slot_key", nullable = false)
    private Long carrierSlotKey;

    @Column(name = "work_carrier_key", nullable = false)
    private Long workCarrierKey;

    @Column(name = "slot_no", nullable = false)
    private Integer slotNo;

    @Column(name = "slot_state", length = 50, nullable = false)
    private String slotState;

    @Column(name = "lot_id", length = 64)
    private String lotId;

    // =========================================================================
    // Constructors (MapStruct & JPA)
    // =========================================================================

    /**
     * 기본 생성자 (필수)
     * - JPA 프록시 생성용
     * - MapStruct 타겟 객체 생성용 (public 필수)
     */
    public TcWorkCarrierSlotEntity() {
    }

    /**
     * 전체 인자 생성자
     * - MapStruct가 Domain -> Entity 변환 시 모든 필드를 한 번에 주입할 때 사용
     */
    public TcWorkCarrierSlotEntity(Long carrierSlotKey, Long workCarrierKey, Integer slotNo, String slotState, String lotId) {
        this.carrierSlotKey = carrierSlotKey;
        this.workCarrierKey = workCarrierKey;
        this.slotNo = slotNo;
        this.slotState = slotState;
        this.lotId = lotId;
    }

    // =========================================================================
    // Static Factory
    // =========================================================================

    public static TcWorkCarrierSlotEntity newEntity(long workCarrierKey, int slotNo) {
        if (workCarrierKey <= 0) {
            throw new IllegalArgumentException("workCarrierKey must be > 0");
        }
        if (slotNo < 1) {
            throw new IllegalArgumentException("slotNo must be >= 1");
        }
        TcWorkCarrierSlotEntity entity = new TcWorkCarrierSlotEntity();
        entity.setWorkCarrierKey(workCarrierKey);
        entity.setSlotNo(slotNo);
        return entity;
    }

    // =========================================================================
    // Getters & Setters
    // =========================================================================

    public Long getCarrierSlotKey() {
        return carrierSlotKey;
    }

    public void setCarrierSlotKey(Long carrierSlotKey) {
        this.carrierSlotKey = carrierSlotKey;
    }

    public Long getWorkCarrierKey() {
        return workCarrierKey;
    }

    public void setWorkCarrierKey(Long workCarrierKey) {
        this.workCarrierKey = workCarrierKey;
    }

    public Integer getSlotNo() {
        return slotNo;
    }

    public void setSlotNo(Integer slotNo) {
        this.slotNo = slotNo;
    }

    public String getSlotState() {
        return slotState;
    }

    public void setSlotState(String slotState) {
        this.slotState = slotState;
    }

    public String getLotId() {
        return lotId;
    }

    public void setLotId(String lotId) {
        this.lotId = lotId;
    }
}
