package com.nori.tc.db.jpa.common.entity.work;

import com.nori.tc.db.jpa.common.entity.base.AbstractUpdatedEntity;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import jakarta.persistence.UniqueConstraint;

/**
 * tc_work_lot 테이블 매핑 엔티티.
 *
 * [DB 스키마]
 * - work_lot_key  : bigint generated by default as identity (PK)
 * - work_key      : bigint NOT NULL (FK -> tc_work.work_key)
 * - carrier_id    : varchar(64) NULL
 * - lot_id        : varchar(64) NOT NULL
 * - parent_lot_id : varchar(64) NULL
 * - chamber_id    : varchar(64) NULL
 * - updated_at    : timestamptz NOT NULL default CURRENT_TIMESTAMP
 * - Constraints   : UNIQUE (work_key, lot_id)
 */
@Entity
@Table(
        name = "tc_work_lot",
        uniqueConstraints = {
                @UniqueConstraint(
                        name = "uk_tc_work_lot_work_key_lot_id",
                        columnNames = {"work_key", "lot_id"}
                )
        }
)
public class TcWorkLotEntity extends AbstractUpdatedEntity {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "work_lot_key", nullable = false)
    private Long workLotKey;

    @Column(name = "work_key", nullable = false)
    private Long workKey;

    @Column(name = "carrier_id", length = 64)
    private String carrierId;

    @Column(name = "lot_id", length = 64, nullable = false)
    private String lotId;

    @Column(name = "parent_lot_id", length = 64)
    private String parentLotId;

    @Column(name = "chamber_id", length = 64)
    private String chamberId;

    // =========================================================================
    // Constructors (MapStruct & JPA)
    // =========================================================================

    /**
     * 기본 생성자 (필수)
     * - JPA 프록시 생성용
     * - MapStruct 타겟 객체 생성용 (public 필수)
     */
    public TcWorkLotEntity() {
    }

    /**
     * 전체 인자 생성자
     */
    public TcWorkLotEntity(
            Long workLotKey,
            Long workKey,
            String carrierId,
            String lotId,
            String parentLotId,
            String chamberId
    ) {
        this.workLotKey = workLotKey;
        this.workKey = workKey;
        this.carrierId = carrierId;
        this.lotId = lotId;
        this.parentLotId = parentLotId;
        this.chamberId = chamberId;
    }

    // =========================================================================
    // Static Factory
    // =========================================================================

    /**
     * 신규 엔티티 생성 팩토리
     * - Unique Key(work_key, lot_id)를 기반으로 초기화한다.
     */
    public static TcWorkLotEntity newEntity(long workKey, String lotId) {
        if (workKey <= 0) {
            throw new IllegalArgumentException("workKey must be > 0");
        }
        if (lotId == null || lotId.isBlank()) {
            throw new IllegalArgumentException("lotId must not be null/blank");
        }

        TcWorkLotEntity e = new TcWorkLotEntity();
        e.setWorkKey(workKey);
        e.setLotId(lotId);
        return e;
    }

    // =========================================================================
    // Getters & Setters
    // =========================================================================

    
    /**
     * DB JPA 계층의 현재 값을 조회합니다.
     *
     * <p>엔티티 생명주기 콜백과 컬럼 매핑 규칙을 기준으로 처리합니다.</p>
     * @return DB JPA 계층 처리 결과
     */
    public Long getWorkLotKey() {
        return workLotKey;
    }

    
    /**
     * DB JPA 계층 설정 값을 반영합니다.
     *
     * <p>엔티티 생명주기 콜백과 컬럼 매핑 규칙을 기준으로 처리합니다.</p>
     * @param workLotKey 대상 키 값
     */
    public void setWorkLotKey(Long workLotKey) {
        this.workLotKey = workLotKey;
    }

    
    /**
     * DB JPA 계층의 현재 값을 조회합니다.
     *
     * <p>엔티티 생명주기 콜백과 컬럼 매핑 규칙을 기준으로 처리합니다.</p>
     * @return DB JPA 계층 처리 결과
     */
    public Long getWorkKey() {
        return workKey;
    }

    
    /**
     * DB JPA 계층 설정 값을 반영합니다.
     *
     * <p>엔티티 생명주기 콜백과 컬럼 매핑 규칙을 기준으로 처리합니다.</p>
     * @param workKey 대상 키 값
     */
    public void setWorkKey(Long workKey) {
        this.workKey = workKey;
    }

    
    /**
     * DB JPA 계층의 현재 값을 조회합니다.
     *
     * <p>엔티티 생명주기 콜백과 컬럼 매핑 규칙을 기준으로 처리합니다.</p>
     * @return DB JPA 계층 처리 결과
     */
    public String getCarrierId() {
        return carrierId;
    }

    
    /**
     * DB JPA 계층 설정 값을 반영합니다.
     *
     * <p>엔티티 생명주기 콜백과 컬럼 매핑 규칙을 기준으로 처리합니다.</p>
     * @param carrierId DB JPA 계층 처리에 사용하는 입력 값
     */
    public void setCarrierId(String carrierId) {
        this.carrierId = carrierId;
    }

    
    /**
     * DB JPA 계층의 현재 값을 조회합니다.
     *
     * <p>엔티티 생명주기 콜백과 컬럼 매핑 규칙을 기준으로 처리합니다.</p>
     * @return DB JPA 계층 처리 결과
     */
    public String getLotId() {
        return lotId;
    }

    
    /**
     * DB JPA 계층 설정 값을 반영합니다.
     *
     * <p>엔티티 생명주기 콜백과 컬럼 매핑 규칙을 기준으로 처리합니다.</p>
     * @param lotId DB JPA 계층 처리에 사용하는 입력 값
     */
    public void setLotId(String lotId) {
        this.lotId = lotId;
    }

    
    /**
     * DB JPA 계층의 현재 값을 조회합니다.
     *
     * <p>엔티티 생명주기 콜백과 컬럼 매핑 규칙을 기준으로 처리합니다.</p>
     * @return DB JPA 계층 처리 결과
     */
    public String getParentLotId() {
        return parentLotId;
    }

    
    /**
     * DB JPA 계층 설정 값을 반영합니다.
     *
     * <p>엔티티 생명주기 콜백과 컬럼 매핑 규칙을 기준으로 처리합니다.</p>
     * @param parentLotId DB JPA 계층 처리에 사용하는 입력 값
     */
    public void setParentLotId(String parentLotId) {
        this.parentLotId = parentLotId;
    }

    
    /**
     * DB JPA 계층의 현재 값을 조회합니다.
     *
     * <p>엔티티 생명주기 콜백과 컬럼 매핑 규칙을 기준으로 처리합니다.</p>
     * @return DB JPA 계층 처리 결과
     */
    public String getChamberId() {
        return chamberId;
    }

    
    /**
     * DB JPA 계층 설정 값을 반영합니다.
     *
     * <p>엔티티 생명주기 콜백과 컬럼 매핑 규칙을 기준으로 처리합니다.</p>
     * @param chamberId DB JPA 계층 처리에 사용하는 입력 값
     */
    public void setChamberId(String chamberId) {
        this.chamberId = chamberId;
    }
}
