package com.nori.tc.db.jpa.common.entity.work;

import com.nori.tc.db.jpa.common.entity.base.AbstractUpdatedEntity;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import jakarta.persistence.UniqueConstraint;

/**
 * tc_work_param 테이블 매핑 엔티티.
 *
 * <p>
 * [DB 스키마]
 * - work_param_key : bigint generated by default as identity (PK)
 * - work_key       : bigint NOT NULL (FK -> tc_work.work_key)
 * - param_name     : varchar(100) NOT NULL
 * - param_value    : varchar(2000) NULL
 * - updated_at     : timestamptz NOT NULL default CURRENT_TIMESTAMP
 * - Constraints    : UNIQUE (work_key, param_name)
 * </p>
 */
@Entity
@Table(
        name = "tc_work_param",
        uniqueConstraints = {
                @UniqueConstraint(
                        name = "uk_tc_work_param_work_key_param_name",
                        columnNames = {"work_key", "param_name"}
                )
        }
)
public class TcWorkParamEntity extends AbstractUpdatedEntity {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "work_param_key", nullable = false)
    private Long workParamKey;

    @Column(name = "work_key", nullable = false)
    private Long workKey;

    @Column(name = "param_name", length = 100, nullable = false)
    private String paramName;

    @Column(name = "param_value", length = 2000)
    private String paramValue;

    // =========================================================================
    // Constructors (MapStruct & JPA)
    // =========================================================================

    /**
     * 기본 생성자 (필수)
     * - JPA 프록시 생성용
     * - MapStruct 타겟 객체 생성용 (public 필수)
     */
    public TcWorkParamEntity() {
    }

    /**
     * 전체 인자 생성자
     */
    public TcWorkParamEntity(Long workParamKey, Long workKey, String paramName, String paramValue) {
        this.workParamKey = workParamKey;
        this.workKey = workKey;
        this.paramName = paramName;
        this.paramValue = paramValue;
    }

    // =========================================================================
    // Static Factory
    // =========================================================================

    /**
     * 신규 엔티티 생성 팩토리
     * - Unique Key(work_key, param_name)를 기반으로 초기화한다.
     */
    public static TcWorkParamEntity newEntity(long workKey, String paramName) {
        if (workKey <= 0) {
            throw new IllegalArgumentException("workKey must be > 0");
        }
        if (paramName == null || paramName.isBlank()) {
            throw new IllegalArgumentException("paramName must not be null/blank");
        }

        TcWorkParamEntity e = new TcWorkParamEntity();
        e.setWorkKey(workKey);
        e.setParamName(paramName);
        return e;
    }

    // =========================================================================
    // Getters & Setters
    // =========================================================================

    public Long getWorkParamKey() {
        return workParamKey;
    }

    public void setWorkParamKey(Long workParamKey) {
        this.workParamKey = workParamKey;
    }

    public Long getWorkKey() {
        return workKey;
    }

    public void setWorkKey(Long workKey) {
        this.workKey = workKey;
    }

    public String getParamName() {
        return paramName;
    }

    public void setParamName(String paramName) {
        this.paramName = paramName;
    }

    public String getParamValue() {
        return paramValue;
    }

    public void setParamValue(String paramValue) {
        this.paramValue = paramValue;
    }
}
