package com.nori.tc.db.jpa.common.entity.work;

import java.time.OffsetDateTime;

import com.nori.tc.db.domain.common.work.TcWorkState;
import com.nori.tc.db.jpa.common.entity.base.AbstractCreatedUpdatedEntity;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import jakarta.persistence.UniqueConstraint;

/**
 * tc_work 테이블 매핑 엔티티.
 *
 * <p>
 * [DB 스키마]
 * - work_key    : bigint generated by default as identity (PK)
 * - eqp_key     : bigint NOT NULL (tc_eqp FK)
 * - work_id     : varchar(64) NOT NULL
 * - operator_id : varchar(64) NULL
 * - step_seq    : int NULL (CHECK >= 0)
 * - work_state  : varchar(20) NOT NULL (QUEUED/RUNNING/COMPLETED/ABORTED)
 * - start_time  : timestamptz NULL
 * - end_time    : timestamptz NULL
 * - mes_message : text NULL
 * - created_at  : timestamptz NOT NULL
 * - updated_at  : timestamptz NOT NULL
 * </p>
 *
 * <p>
 * [제약/인덱스]
 * - PK: work_key
 * - UK: (eqp_key, work_id)
 * - INDEX: eqp_key, work_state, created_at
 * </p>
 *
 * <p>
 * [설계 포인트]
 * 1. MapStruct 호환성:
 * - public 생성자를 제공하여 Mapper가 객체를 생성할 수 있게 합니다.
 *
 * 2. Identity Strategy:
 * - PK(work_key)는 DB 자동 생성(Identity)을 따릅니다.
 * </p>
 */
@Entity
@Table(
        name = "tc_work",
        uniqueConstraints = {
                @UniqueConstraint(
                        name = "uk_tc_work_eqp_key_work_id",
                        columnNames = {"eqp_key", "work_id"}
                )
        }
)
public class TcWorkEntity extends AbstractCreatedUpdatedEntity {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "work_key", nullable = false)
    private Long workKey;

    @Column(name = "eqp_key", nullable = false)
    private Long eqpKey;

    @Column(name = "work_id", length = 64, nullable = false)
    private String workId;

    @Column(name = "operator_id", length = 64)
    private String operatorId;

    @Column(name = "step_seq")
    private Integer stepSeq;

    @Enumerated(EnumType.STRING)
    @Column(name = "work_state", length = 20, nullable = false)
    private TcWorkState workState;

    @Column(name = "start_time")
    private OffsetDateTime startTime;

    @Column(name = "end_time")
    private OffsetDateTime endTime;

    @Column(name = "mes_message", columnDefinition = "text")
    private String mesMessage;

    // =========================================================================
    // Constructors (MapStruct & JPA)
    // =========================================================================

    /**
     * 기본 생성자 (필수)
     */
    public TcWorkEntity() {
    }

    /**
     * 전체 인자 생성자
     */
    public TcWorkEntity(
            Long workKey,
            Long eqpKey,
            String workId,
            String operatorId,
            Integer stepSeq,
            TcWorkState workState,
            OffsetDateTime startTime,
            OffsetDateTime endTime,
            String mesMessage
    ) {
        this.workKey = workKey;
        this.eqpKey = eqpKey;
        this.workId = workId;
        this.operatorId = operatorId;
        this.stepSeq = stepSeq;
        this.workState = workState;
        this.startTime = startTime;
        this.endTime = endTime;
        this.mesMessage = mesMessage;
    }

    // =========================================================================
    // Static Factory
    // =========================================================================

    public static TcWorkEntity newEntity(long eqpKey, String workId) {
        if (eqpKey <= 0) {
            throw new IllegalArgumentException("eqpKey must be > 0");
        }
        if (workId == null || workId.isBlank()) {
            throw new IllegalArgumentException("workId must not be null/blank");
        }
        TcWorkEntity e = new TcWorkEntity();
        e.setEqpKey(eqpKey);
        e.setWorkId(workId);
        return e;
    }

    // =========================================================================
    // Getters & Setters
    // =========================================================================

    public Long getWorkKey() {
        return workKey;
    }

    public void setWorkKey(Long workKey) {
        this.workKey = workKey;
    }

    public Long getEqpKey() {
        return eqpKey;
    }

    public void setEqpKey(Long eqpKey) {
        this.eqpKey = eqpKey;
    }

    public String getWorkId() {
        return workId;
    }

    public void setWorkId(String workId) {
        this.workId = workId;
    }

    public String getOperatorId() {
        return operatorId;
    }

    public void setOperatorId(String operatorId) {
        this.operatorId = operatorId;
    }

    public Integer getStepSeq() {
        return stepSeq;
    }

    public void setStepSeq(Integer stepSeq) {
        this.stepSeq = stepSeq;
    }

    public TcWorkState getWorkState() {
        return workState;
    }

    public void setWorkState(TcWorkState workState) {
        this.workState = workState;
    }

    public OffsetDateTime getStartTime() {
        return startTime;
    }

    public void setStartTime(OffsetDateTime startTime) {
        this.startTime = startTime;
    }

    public OffsetDateTime getEndTime() {
        return endTime;
    }

    public void setEndTime(OffsetDateTime endTime) {
        this.endTime = endTime;
    }

    public String getMesMessage() {
        return mesMessage;
    }

    public void setMesMessage(String mesMessage) {
        this.mesMessage = mesMessage;
    }
}
