package com.nori.tc.db.jpa.common.entity.work;

import com.nori.tc.db.jpa.common.entity.base.AbstractUpdatedEntity;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import jakarta.persistence.UniqueConstraint;

/**
 * tc_work_carrier 테이블 매핑 엔티티.
 *
 * <p>
 * [DB 스키마]
 * - work_carrier_key : bigint generated by default as identity (PK)
 * - work_key         : bigint NOT NULL (FK)
 * - carrier_id       : varchar(64) NOT NULL
 * - port_id          : varchar(20)
 * - slot_map         : varchar(255)
 * - total_qty        : integer (CHECK >= 0)
 * - good_qty         : integer (CHECK >= 0)
 * - scrap_qty        : integer (CHECK >= 0)
 * - updated_at       : timestamptz NOT NULL (AbstractUpdatedEntity 상속)
 * - Constraints      : UNIQUE (work_key, carrier_id)
 * </p>
 *
 * <p>
 * [설계 포인트]
 * 1. MapStruct 호환성:
 * - public 생성자를 제공하여 Mapper가 객체를 생성할 수 있게 합니다.
 *
 * 2. Identity Strategy:
 * - PK(work_carrier_key)는 DB 자동 생성(Identity)을 따릅니다.
 * </p>
 */
@Entity
@Table(
        name = "tc_work_carrier",
        uniqueConstraints = {
                @UniqueConstraint(name = "uk_tc_work_carrier_work_key_carrier_id", columnNames = {"work_key", "carrier_id"})
        }
)
public class TcWorkCarrierEntity extends AbstractUpdatedEntity {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "work_carrier_key", nullable = false)
    private Long workCarrierKey;

    @Column(name = "work_key", nullable = false)
    private Long workKey;

    @Column(name = "carrier_id", length = 64, nullable = false)
    private String carrierId;

    @Column(name = "port_id", length = 20)
    private String portId;

    @Column(name = "slot_map", length = 255)
    private String slotMap;

    @Column(name = "total_qty")
    private Integer totalQty;

    @Column(name = "good_qty")
    private Integer goodQty;

    @Column(name = "scrap_qty")
    private Integer scrapQty;

    // =========================================================================
    // Constructors (MapStruct & JPA)
    // =========================================================================

    /**
     * 기본 생성자 (필수)
     * - JPA 프록시 생성용
     * - MapStruct 타겟 객체 생성용 (public 필수)
     */
    public TcWorkCarrierEntity() {
    }

    /**
     * 전체 인자 생성자
     * - MapStruct가 Domain -> Entity 변환 시 모든 필드를 한 번에 주입할 때 사용
     */
    public TcWorkCarrierEntity(Long workCarrierKey, Long workKey, String carrierId,
                               String portId, String slotMap,
                               Integer totalQty, Integer goodQty, Integer scrapQty) {
        this.workCarrierKey = workCarrierKey;
        this.workKey = workKey;
        this.carrierId = carrierId;
        this.portId = portId;
        this.slotMap = slotMap;
        this.totalQty = totalQty;
        this.goodQty = goodQty;
        this.scrapQty = scrapQty;
    }

    // =========================================================================
    // Static Factory
    // =========================================================================

    
    /**
     * DB JPA 계층 규약에 맞게 데이터를 변환/구성합니다.
     *
     * <p>엔티티 생명주기 콜백과 컬럼 매핑 규칙을 기준으로 처리합니다.</p>
     * @param workKey 대상 키 값
     * @param carrierId DB JPA 계층 처리에 사용하는 입력 값
     * @return DB JPA 계층 처리 결과
     */
    public static TcWorkCarrierEntity newEntity(long workKey, String carrierId) {
        if (workKey <= 0) {
            throw new IllegalArgumentException("workKey must be > 0");
        }
        if (carrierId == null || carrierId.isBlank()) {
            throw new IllegalArgumentException("carrierId must not be null/blank");
        }
        TcWorkCarrierEntity entity = new TcWorkCarrierEntity();
        entity.setWorkKey(workKey);
        entity.setCarrierId(carrierId);
        return entity;
    }

    // =========================================================================
    // Getters & Setters
    // =========================================================================

    
    /**
     * DB JPA 계층의 현재 값을 조회합니다.
     *
     * <p>엔티티 생명주기 콜백과 컬럼 매핑 규칙을 기준으로 처리합니다.</p>
     * @return DB JPA 계층 처리 결과
     */
    public Long getWorkCarrierKey() {
        return workCarrierKey;
    }

    
    /**
     * DB JPA 계층 설정 값을 반영합니다.
     *
     * <p>엔티티 생명주기 콜백과 컬럼 매핑 규칙을 기준으로 처리합니다.</p>
     * @param workCarrierKey 대상 키 값
     */
    public void setWorkCarrierKey(Long workCarrierKey) {
        this.workCarrierKey = workCarrierKey;
    }

    
    /**
     * DB JPA 계층의 현재 값을 조회합니다.
     *
     * <p>엔티티 생명주기 콜백과 컬럼 매핑 규칙을 기준으로 처리합니다.</p>
     * @return DB JPA 계층 처리 결과
     */
    public Long getWorkKey() {
        return workKey;
    }

    
    /**
     * DB JPA 계층 설정 값을 반영합니다.
     *
     * <p>엔티티 생명주기 콜백과 컬럼 매핑 규칙을 기준으로 처리합니다.</p>
     * @param workKey 대상 키 값
     */
    public void setWorkKey(Long workKey) {
        this.workKey = workKey;
    }

    
    /**
     * DB JPA 계층의 현재 값을 조회합니다.
     *
     * <p>엔티티 생명주기 콜백과 컬럼 매핑 규칙을 기준으로 처리합니다.</p>
     * @return DB JPA 계층 처리 결과
     */
    public String getCarrierId() {
        return carrierId;
    }

    
    /**
     * DB JPA 계층 설정 값을 반영합니다.
     *
     * <p>엔티티 생명주기 콜백과 컬럼 매핑 규칙을 기준으로 처리합니다.</p>
     * @param carrierId DB JPA 계층 처리에 사용하는 입력 값
     */
    public void setCarrierId(String carrierId) {
        this.carrierId = carrierId;
    }

    
    /**
     * DB JPA 계층의 현재 값을 조회합니다.
     *
     * <p>엔티티 생명주기 콜백과 컬럼 매핑 규칙을 기준으로 처리합니다.</p>
     * @return DB JPA 계층 처리 결과
     */
    public String getPortId() {
        return portId;
    }

    
    /**
     * DB JPA 계층 설정 값을 반영합니다.
     *
     * <p>엔티티 생명주기 콜백과 컬럼 매핑 규칙을 기준으로 처리합니다.</p>
     * @param portId DB JPA 계층 처리에 사용하는 입력 값
     */
    public void setPortId(String portId) {
        this.portId = portId;
    }

    
    /**
     * DB JPA 계층의 현재 값을 조회합니다.
     *
     * <p>엔티티 생명주기 콜백과 컬럼 매핑 규칙을 기준으로 처리합니다.</p>
     * @return DB JPA 계층 처리 결과
     */
    public String getSlotMap() {
        return slotMap;
    }

    
    /**
     * DB JPA 계층 설정 값을 반영합니다.
     *
     * <p>엔티티 생명주기 콜백과 컬럼 매핑 규칙을 기준으로 처리합니다.</p>
     * @param slotMap DB JPA 계층 처리에 사용하는 입력 값
     */
    public void setSlotMap(String slotMap) {
        this.slotMap = slotMap;
    }

    
    /**
     * DB JPA 계층의 현재 값을 조회합니다.
     *
     * <p>엔티티 생명주기 콜백과 컬럼 매핑 규칙을 기준으로 처리합니다.</p>
     * @return DB JPA 계층 처리 결과
     */
    public Integer getTotalQty() {
        return totalQty;
    }

    
    /**
     * DB JPA 계층 설정 값을 반영합니다.
     *
     * <p>엔티티 생명주기 콜백과 컬럼 매핑 규칙을 기준으로 처리합니다.</p>
     * @param totalQty DB JPA 계층 처리에 사용하는 입력 값
     */
    public void setTotalQty(Integer totalQty) {
        this.totalQty = totalQty;
    }

    
    /**
     * DB JPA 계층의 현재 값을 조회합니다.
     *
     * <p>엔티티 생명주기 콜백과 컬럼 매핑 규칙을 기준으로 처리합니다.</p>
     * @return DB JPA 계층 처리 결과
     */
    public Integer getGoodQty() {
        return goodQty;
    }

    
    /**
     * DB JPA 계층 설정 값을 반영합니다.
     *
     * <p>엔티티 생명주기 콜백과 컬럼 매핑 규칙을 기준으로 처리합니다.</p>
     * @param goodQty DB JPA 계층 처리에 사용하는 입력 값
     */
    public void setGoodQty(Integer goodQty) {
        this.goodQty = goodQty;
    }

    
    /**
     * DB JPA 계층의 현재 값을 조회합니다.
     *
     * <p>엔티티 생명주기 콜백과 컬럼 매핑 규칙을 기준으로 처리합니다.</p>
     * @return DB JPA 계층 처리 결과
     */
    public Integer getScrapQty() {
        return scrapQty;
    }

    
    /**
     * DB JPA 계층 설정 값을 반영합니다.
     *
     * <p>엔티티 생명주기 콜백과 컬럼 매핑 규칙을 기준으로 처리합니다.</p>
     * @param scrapQty DB JPA 계층 처리에 사용하는 입력 값
     */
    public void setScrapQty(Integer scrapQty) {
        this.scrapQty = scrapQty;
    }
}
